### ISSUE TITLE
discuss what to call EOL maintenance period of "Current" release lines

### ISSUE THREAD

**Issue by Fishrock123** [nodejs/Release#101]
Was sparked today by confusion on what to call the v5.x OpenSSL update.

v5.x is now the only "Stable" so we may continue to call it "(Stable)", but we will need to decide what to do v7, v9, etc.

Possible options (moving from Current to..):
- Current (keep the name)
  - potentially confusing, having more than one "Current"
- Stable
  - another term to remember
  - not respective of what this term was previously used for
- Maintenance  
  - makes sense with what the period actually represents
  - gives us one end point that release lines transition to before EOL
  - potentially confusing, timeframes for "Maintenance " will vary between stable and lts

cc @nodejs/lts .. any other options?

**Comment by jasnell** [comment]
Thus far we have used the label "Maintenance" to specifically identify the LTS branches that are in LTS Maintenance mode (specifically v0.10 and v0.12). v4 Will also go into Maintenance a year from now. For me, calling something Maintenance implies that it falls under the LTS plan, which v5 does not.

When the odd numbered branches fall out of being `Current`, I'd recommend that we simply drop back to calling those `Stable`... which means there would be no change at all in what we call v5 releases.

Specifically:

* `Current` == The current primary release line (implies active ongoing development).
* `Stable` == Old release lines that are no longer Current but do not fall under the LTS plan (implies few changes if any without assumption of long term support).
* `LTS` == An Active LTS release line (implies that the release line falls under the LTS plan).
* `Maintenance` == A Maintenance LTS release line (implies that the release line falls under the LTS plan).

This would be the most logical and, more importantly, least confusing path forward.

**Comment by rvagg** [comment]
How about we not call it anything? I'd vote for "Maintenance" but see your point on that.

**Comment by jasnell** [comment]
I'm definitely good with not giving it any label.

**Comment by Fishrock123** [comment]
> This would be the most logical and, more importantly, least confusing path forward.

I Disagree, having different EOL period names does not seem logical / seems more confusing to me.

> How about we not call it anything?

I guess we could do that?

**Comment by mhdawson** [comment]
I'd vote for nothing at all.  Right now continued updates after the next stable seems pretty vaguely defined.  If there is to be an expectation of updates (and what kind) after the next stable is cut we probably need to document that somewhere like we do for LTS releases.

**Comment by TheAlphaNerd** [comment]
Are we happy with the status quo or should we bring this to the working group again? If everyone is satisfied we should close this issue

**Comment by Fishrock123** [comment]
I'm still unsatisfied with the fact that we refer to it as "just maintenance" and they say "but it's not officially **'Maintenance'**".

**Comment by MylesBorins** [comment]
Closing as status quo seems to be sufficient
