### ISSUE TITLE
Current status of LTS group/ backporters

### ISSUE THREAD

**Issue by marco-ippolito** [nodejs/Release#1012]
Quoting documentation https://github.com/nodejs/Release/blob/main/GOVERNANCE.md:

LTS:
```
For releasing on LTS release lines, releasers must:

Be added as members of the GitHub [LTS team](https://github.com/orgs/nodejs/teams/lts)
Fully release at least one Current Node.js release; for practice, and to help promote the new GPG key to the user ecosystem prior to it being required to verify an LTS release
```
Backporters https://github.com/nodejs/Release?tab=readme-ov-file#lts-staging-branches:
```
Only members of @nodejs/backporters should land commits onto staging branches.
```
Currently we are not enforcing both of these rules.
I think we should remove the LTS team and keep only releasers, and keep the backporters for people who want to start getting involved with the release working group and can prepare current releases.

**Comment by richardlau** [comment]
There's some previous discussion in https://github.com/nodejs/Release/pull/912. That also proposed removing backporters.

As I mentioned in https://github.com/nodejs/Release/pull/912#discussion_r1327454085 the `LTS` team has never been, as far as I am aware, an access control team. `releasers` and `backporters` are access control teams (e.g. being in `releasers` would get you access to the release CI and `backporters` have permissions to push to the LTS staging branches).

I think it's fair to have a discussion as to whether the `LTS` team serves a purpose today. Our README currently says: https://github.com/nodejs/Release/blob/17c98b429783838c7c19471c598a03082fcf4f7b/README.md?plain=1#L93-L95
and I guess it's debatable whether you can manage the process/content for releases without being a releaser or backporter. You could certainly have an opinion on what could/should be in a LTS release line and how often releases should happen as a general consumer of Node.js.

One thing I would stress is that membership of the Release WG does not equate to being a releaser:
https://github.com/nodejs/Release/blob/17c98b429783838c7c19471c598a03082fcf4f7b/README.md?plain=1#L81-L87

**Comment by marco-ippolito** [comment]
In meeting https://github.com/nodejs/Release/issues/1026 we had consensus about removing the @nodejs/lts team, and merge it into @nodejs/releasers
