### ISSUE TITLE
Working group meetings

### ISSUE THREAD

**Issue by richardlau** [nodejs/Release#1038]
@nodejs/Release, As per https://github.com/nodejs/admin/issues/923 the old Node.js calendar has disappeared. A [new calendar](https://nodejs.org/calendar) has been created, and @mhdawson has attempted to reconstruct the repeating entries. 

For the Release WG, the new calendar has the next meeting scheduled for the 17 October 2024, and then every three weeks after that. However that puts us on a collision course with the Security WG, who have the timeslot every two weeks. For example, the current calendar entries has us clashing on 7 November. We avoided the clash before, so the schedule is probably wrong.

Does anyone remember what our cadence for Release WG meetings was? I don't recall if it was every x weeks, or something like nth Thursday of the month (last?) but I think we ended up with one meeting per month?

Do we need to have a meeting before 17 October, given that Node.js 23 is supposed to be released on 15 October (next week(!))?

**Comment by richardlau** [comment]
I did look at https://github.com/nodejs/Release/blob/main/GOVERNANCE.md#wg-meetings, which says:

> The WG meets regularly, check the foundation calendar for details.

🤣

**Comment by marco-ippolito** [comment]
Once a month

**Comment by UlisesGascon** [comment]
Confirmed (Every 4 weeks on Thursday) at the same time as the Security WG (no collision due the frequency). I had a copy of the calendar in my working email :sweat_smile:. Last meeting was on Sep 19th, next one in Oct 17th

**Comment by mhdawson** [comment]
@richardlau done.
