### ISSUE TITLE
Off-boarding Bethany Griggs (@BethGriggs)

### ISSUE THREAD

**Issue by RafaelGSS** [nodejs/Release#1042]
The following steps should be taken as part of the offboarding process:

* [x] Be removed from the GitHub [releasers team](https://github.com/orgs/nodejs/teams/releasers) in the Node.js organizations.
* [x] Be removed from the GitHub [security-release team](https://github.com/orgs/nodejs/teams/security-release) in the Node.js and nodejs-private organizations.
* [x] Ensure their SSH key is removed from the `dist` user on the primary www server.
* [x] Move their GPG key in nodejs/node [README.md](https://github.com/nodejs/node/#release-keys) to the 'Other keys used to sign some previous releases' section.
* [x] Open a PR in [nodejs/docker-node](https://github.com/nodejs/docker-node/) to remove their GPG key from [node.keys](https://github.com/nodejs/docker-node/blob/main/keys/node.keys).
* [x] Ensure they are moved to 'Emeritus - Releasers team' in the nodejs/release [README](https://github.com/nodejs/Release/blob/main/README.md).
* [x] Remove them from the `#nodejs-release-private` team on the OpenJS Slack.

Refs: https://github.com/nodejs/Release/issues/1036

**Comment by aduh95** [comment]
It looks like all the action items have been ticked off, closing as completed. Let's reopen if I missed something.
