### ISSUE TITLE
create-release-proposal Roadmap

### ISSUE THREAD

**Issue by RafaelGSS** [nodejs/Release#1061]
As I've mentioned in https://github.com/nodejs/node/pull/55993#issuecomment-2504664438. Let's use this issue to discuss the next steps of `create-release-proposal.yml`.

We have run it with success for the last v22.x proposal https://github.com/nodejs/node/pull/56040 and now it's time to improve it.

### Issues

* [x] 1 - Since the script is using `actions/checkout` to checkout the staging branch it becomes a problem if you don't cherry-pick all `create-release-proposal.yml` commits to the staging branch as it will run an outdated version (and in the case of v20, it doesn't have the action yet). It's necessary to be in the staging branch to run `git node release --prepare`, so a possible resolution would be:
  * 1 - Run `actions/checkout` on main and copy the `./tools/create-release.sh` content
  * 2 - Run `actions/checkout` on staging branch
  * 3 - Run the copied `./tools/create-release.sh` instead of local create-release.sh
 But I don't know if I like this approach. Any suggestion?
* [x] 2 - Attribution of work to the releaser. All the work is now attributed to the bot, ideally we can keep authorship attribution in at least three diff places:
  * 1 - The user handler that gets add to the PR description title, along with the user handler added to the `doc/changelogs/CHANGELOG_V<version>.md` file needs to point to the handler of the current release manager for that proposal
  * 2 - The PR should ideally be opened on behalf of the release manager
  * 3 - The release commit authorship needs to be properly attributed to the release manager

**Comment by ruyadorno** [comment]
Added the attribution of work to the discussion since that's a major departure that I noticed from using the GH Action.

**Comment by RafaelGSS** [comment]
> Added "attribution of work" to the discussion since that's a major departure that I noticed from using the GH Action.

To fix that I believe we just need to find a way to get the release username and email and replace them on https://github.com/nodejs/node/blob/main/.github/workflows/create-release-proposal.yml#L77. Possibly this is already available via GitHub workflow variables.

**Comment by aduh95** [comment]
I can work on the attribution issue once https://github.com/nodejs/node/pull/56054 have landed (https://github.com/nodejs/node-core-utils/pull/876 is also related)

**Comment by ljharb** [comment]
If the workflow is initiated using workflow_dispatch, then it can always use the workflow on main, and then you don’t have to keep them updated on staging/release branches?

**Comment by aduh95** [comment]
ncu expects you to be on the staging branch, it would require quite some work to change that. FWIW I solved it in https://github.com/nodejs/node/pull/56054 using a `curl` call: https://github.com/nodejs/node/pull/56054/files#diff-251665e4043845a7862783d8b38684b05b7237bdedfec2d6c45fc57cf1bb0edbR84-R87

**Comment by ljharb** [comment]
@aduh95 right, but i mean that the workflow that's initiated from the staging branch can serve only to dispatch to a workflow on main, and that workflow can check out staging before running ncu.
