### ISSUE TITLE
Mention odd-number release has eight months support as Current.

### ISSUE THREAD

**Issue by lijunle** [nodejs/Release#113]
In the [schedule png](https://github.com/nodejs/LTS/blob/master/schedule.png), it shows the odd-number releases (v5, v7) has 9 months as _Current_ stage. However, I don't find the words mentioning this policy. Do I miss something somewhere?

---

**Update**

Check the [v5 release note](https://nodejs.org/en/blog/release/v5.0.0/), it mentions v5 will be supported for 8 months. This words should be mentioned in README.

BTW, the date should be list in the schedule picture, it looks like 6 + 3 = 9 months.

> According to our new LTS (Long-term Support) plan, Node.js v4 Argon will continue to be supported for 30 months, ending in April 2018. **This new version of Node.js, however, will only be supported for 8 months**, with a new major version, v6, being released in April 2016.

**Comment by rvagg** [comment]
Yeah, we need to fix our language here, it's only recently gone from something we've had a vague agreement about to having a formal plan in place. I'm pretty sure *8 months* is where we landed for support lifetime, @nodejs/lt please correct me if I'm getting that wrong. To be honest I can't recall where the notes are for this agreement but it needs to make it on to the README.

**Comment by Fishrock123** [comment]
@rvagg It was never official, but we are effectively doing 8 months afaik

**Comment by mhdawson** [comment]
Agreed I don't remember an official agreement, but the 6 + 2 does sound in the ballpark of what it sounded like would occur.

**Comment by rvagg** [comment]
CTC reaffirmed today that it's 6 + 2 months for non-LTS majors. So v5 is EOL tomorrow. I'm going to get a post up on nodejs.org about it and I'll see about getting the graphic cleaned up so it doesn't send the wrong message.

**Comment by TheAlphaNerd** [comment]
@rvagg is this being mentioned in your new readme?

**Comment by rvagg** [comment]
yes @ https://github.com/nodejs/LTS/blob/readme-rework/README.md#support-timeframes
