### ISSUE TITLE
Show more releases in the schedule image

### ISSUE THREAD

**Issue by mgol** [nodejs/Release#125]
The LTS schedule image is good at presenting the relation between old 0.10 & 0.12 lines and the new 4+ ones and it nicely shows how an LTS & a non-LTS version support look like but it's still not possible to see how exactly will various versions support overlap over time.

I'd like the image to show the full support situation at the moment when one of the new-type LTS releases support ends completely; i.e. I'd like the graph to show Node 8, 9 which will be released before Apr 2018 when Node 4 ends its life and maybe even Node 10 which starts support at this moment (the graph doesn't have to show the full Node 10 life line, just the beginning).

I think it'd make the whole schedule more clear; you'd be able to see what configurations of active/maintenance/current support periods may coexist.

**Comment by TheAlphaNerd** [comment]
@rvagg is there movement on an updated image?

**Comment by rvagg** [comment]
Yeah, I've been doing variations of it for my own presentations, here's one that includes v8 (missing the maintenance period of Current releases tho)

![screenshot 2016-11-17 10 29 44](https://cloud.githubusercontent.com/assets/495647/20370086/d3b2d3b0-acb0-11e6-871a-5cc9828c4678.png)

I'll get a more relevant one done for https://github.com/nodejs/LTS/pull/121 ASAP, I really want to close that out.

**Comment by MylesBorins** [comment]
Closing as I think we do this. Let me know to reopen if mistaken

**Comment by mgol** [comment]
I confirm the graph is being updated, thanks!
