### ISSUE TITLE
Update Table and Chart

### ISSUE THREAD

**Issue by jasnell** [nodejs/Release#132]
The LTS table and chart need to be updated to show the v7 and v8 timelines.
/cc @nodejs/lts @rvagg

**Comment by TheAlphaNerd** [comment]
ping @rvagg

**Comment by cjihrig** [comment]
When it comes time to update the schedule again, the LTS team might find [this](https://www.npmjs.com/package/lts) module helpful. It consumes the JSON file from this repo and outputs the schedule for a given range of dates. Example output is [here](https://talks.continuation.io/nodeweek-4-17/images/lts.png).
