### ISSUE TITLE
Clarify what is a "current LTS release"

### ISSUE THREAD

**Issue by mgol** [nodejs/Release#147]
At the end of the README the "current LTS release" term appears:

> It should be stated that the abstraction layer (currently NAN) should support all current LTS releases. Given that Active LTS will overlap for a period of 6 months, this means that the abstraction layer will, at any given point in time, fully support a maximum of 2 LTS releases.

Nowhere else in the README it's stated what it means for an LTS release to be "current". From the context I guess it's about being (one of) the Active LTS but it shouldn't have to be guessed.

**Comment by netsup99** [comment]
Hi,

I cleaned cache and installed again NPM install, but it did not help.

My temporary workaround to start  learn typescript in this case was to load solution from 
https://olepetterdahlmann.com/2016/08/19/angular-2-startup-project-in-visual-studio-code-and-visual-studio/
This solution(package.json) uses  typescript": "^1.8.10",

 I tried with same configuration to use typescript": "^2.0.3", It did not load bootstrap.

//...Mike

**Comment by mgol** [comment]
@netsup99 It seems you posted that in a wrong issue.

**Comment by mtheoryx** [comment]
@mgol Does it make more sense to use 'Active LTS' in this case?

> It should be stated that the abstraction layer (currently NAN) should support all currently Active LTS releases. Given that Active LTS will overlap for a period of 6 months, this means that the abstraction layer will, at any given point in time, fully support a maximum of 2 LTS releases.

**Comment by mgol** [comment]
Sounds good to me.

-- 
Michał Gołębiowski

**Comment by TheAlphaNerd** [comment]
I'm going to close this for now, please let me know if you have any other questions

**Comment by mgol** [comment]
@TheAlphaNerd This was not just a question, I think the README is confusing as it is now and that "current LTS" mentions should be replaced with "Active LTS".

**Comment by mgol** [comment]
(unless that was not the intended meaning but then it still should be corrected IMO)

**Comment by mhdawson** [comment]
I think it could be clarified to:

```
all LTS releases that have not yet reached the end of the Maintenance mode.
```

**Comment by mgol** [comment]
...which means I understood it incorrectly? :) Sounds good to me if that's the intention.

**Comment by Fishrock123** [comment]
This seems like poor wording on our part, it should be "Active LTS Release", correct?
