### ISSUE TITLE
Backport WHATWG URL to 6.x?

### ISSUE THREAD

**Issue by jasnell** [nodejs/Release#208]
Now that the WHATWG URL implementation is close to [graduating from Experimental status](https://github.com/nodejs/node/pull/12710), I would like to open a discussion about whether it makes sense to backport the implementation to 6.x..

/cc @targos @TimothyGu @watilde @joyeecheung @nodejs/lts

**Comment by TimothyGu** [comment]
New features don't seem to be covered by the range of accepted changes in the [LTS Plan](https://github.com/nodejs/LTS#lts-plan)…

**Comment by jasnell** [comment]
They can on a case by case basis during the Active LTS phase.

**Comment by TimothyGu** [comment]
Okay, rules notwithstanding personally I think it is a great addition. As a maintainer of [node-fetch](https://www.npmjs.com/package/node-fetch), the availability of a high-performance standard-compliant URL parser in all supported Node.js versions would be a boon for tricky bugs like https://github.com/bitinn/node-fetch/issues/245.

**Comment by MylesBorins** [comment]
+1

**Comment by joyeecheung** [comment]
Can't see any harm in the idea...so +1

**Comment by gibfahn** [comment]
+1, seems reasonable once it's graduated.

**Comment by targos** [comment]
SGTM

**Comment by watilde** [comment]
Sounds good to me as well.

**Comment by sam-github** [comment]
+1 once not experimental

**Comment by kumar303** [comment]
It looks like it's graduated from experimental status now, right? https://github.com/nodejs/node/pull/12710

**Comment by jasnell** [comment]
Yes. It's no longer experimental

**Comment by gibfahn** [comment]
This has plenty of +1s, so I guess it's just waiting for someone to raise a backport PR.

**Comment by TimothyGu** [comment]
Backport PR: https://github.com/nodejs/node/pull/17365

**Comment by mhdawson** [comment]
+1 from me as well.

**Comment by MylesBorins** [comment]
Coming out in 6.13.0
