### ISSUE TITLE
Protected branches can't be force pushed

### ISSUE THREAD

**Issue by MylesBorins** [nodejs/Release#209]
So this is obviously by design / a feature... but it introduces a hiccup in the release flow. generally be rebase the staging branch against the release branch after a release. After doing this we force push.

This has been a bit of annoyances for backports... as they all end up requiring a rebase after a release.

Alternatively we could look at cherry-picking from the release branch to staging... but I also cringe at the idea of staging + release constantly drifting. Rebasing staging is by far the more elegant approach for keeping a clean history... but at a cost.

This release I simply unprotected the branch, force pushed, and then re-protected. This would not be possible for releasers who are not owners.

What do people think we should do?

**Comment by gibfahn** [comment]
Interesting that you can't choose whether protected branches can be force pushed to, maybe something we should raise with GitHub.

I think the rebasing is necessary though, if we start trying to cherry pick across then we lose the benefit of staging, as we can no longer trust that the staging branch is exactly the same as the vN.x branch.

Maybe a bot or a CI job that automated the process of [removing](https://developer.github.com/v3/repos/branches/#remove-branch-protection), rebasing, and re-adding branch protection would work for non-owners.

**Comment by MylesBorins** [comment]
the CI job would have to be an owner which I think is a non starter. We could also just leave it to owners to rebase... which isn't soooo unreasonable.
