### ISSUE TITLE
New Label ~ baking-for-lts

### ISSUE THREAD

**Issue by MylesBorins** [nodejs/Release#211]
https://github.com/nodejs/node/labels/baking-for-lts

I'm going to add this to things that we want to backport but require more time to bake. LMK if ya'll think we should rename / document this

**Comment by gibfahn** [comment]
What's the difference between this and `lts-watch`? Wouldn't you have to recheck all the baking ones anyway? Happy to have it, but not clear on the use-case.

I think the act of documenting it will probably help us work out what the use-case is anyway, so +1 on documenting.

**Comment by mhdawson** [comment]
+1 on documenting and we can understand the use case as we do that.

**Comment by MylesBorins** [comment]
I'll document next week.

lts-watch is for things that we are considered. baking is something we know will land but needs more time. This is useful when filtering commits to backport when we don't want to have commits that are baking show up, but we do want to show the lts-watch commits
