### ISSUE TITLE
Proposal: Asynchronous semver-minor backporting review

### ISSUE THREAD

**Issue by gibfahn** [nodejs/Release#212]
It was suggested in [the last LTS meeting](https://github.com/nodejs/LTS/issues/201) that it might be worth trying to decide about semver-minor backports asynchronously (i.e. in Github), the same way we decide on PRs or `ctc-review` items.

Here's the first thing that occurred to me, feel free to suggest alternatives.

We might also just decide that this is too slow/inefficient, and that we should just keep doing what we're currently doing. I think it's worth having the discussion even if the answer is "let's not do this".

### Strawman proposal:

If a PR seems obviously unsuited for backporting then someone can just add the `dont-land-on` tags and cc/ @nodejs/lts in a comment. If anyone disagrees then it becomes an `lts-review` PR.

Otherwise same rules as for landing PRs, if someone adds the `lts-review` tag to the landed PR, then LTS members can vote in the issue.

| Response | Result |
| --- | --- |
| All `+1`s | Good to backport |
| All `-1`s | `dont-land-on` |
| Both `+1`s and `-1`s | Review at next meeting |
| `+1` but needs to bake | `baking-for-lts` |

We can have a 48/72 hour timeline, but try to leave it a lot longer by default.

**Comment by jasnell** [comment]
Perhaps this: semver-patch commits can be cherry-picked in to LTS staging branches at any time so long as they do not have the `dont-land-*` labels. semver-minor commits *require* a backport pull request that must be signed off by at least two LTS WG members before it can land in an LTS staging branch following a 48/72 hour rule. For such PRs, a new commit metadata line `LTS-Reviewed-By: ...` can be added distinguishing who signed off.

**Comment by sam-github** [comment]
I like @jasnell 's idea of using the PR process and PR approvals to approve semver-minor backports, where only with lack of consensus does it need to be raised to the LTS WG for discussion (probably rare).

Would we need a new metadata type? There was some discussion recently, and I think we'd decided on backported PRs using a system where the original PR metadata would be indented, and the backport PR would get the normal PR metadata.

I'm having trouble finding that discussion, though.

**Comment by gibfahn** [comment]
>semver-minor commits require a backport pull request

So I guess this would be the key change, raising PRs even if the change cherry-picks cleanly.

+1 to that idea.

**Comment by gibfahn** [comment]
>Would we need a new metadata type? There was some discussion recently, and I think we'd decided on backported PRs using a system where the original PR metadata would be indented, and the backport PR would get the normal PR metadata.

Don't think it was finalised, but we discussed in the [last LTS meeting](https://github.com/nodejs/LTS/issues/201).

**Comment by MylesBorins** [comment]
We should discuss this today. I'm not sure that this is worthwhile tbqh. We are only doing a single semver minor release per month, there has never really been a timecrunch or blocking on getting semver minors in. We need a single meeting to discuss and agree on which ones should land, and this hasn't proven to be a blocking issue in the past (imho).

**Comment by sam-github** [comment]
I think async might get wider participation than just the few people we get into the LTS meeting, and if anyone (even one person) objects (or even just wants it discussed), or it fails some kind of quorum, it can always fallback to the meeting.

**Comment by MylesBorins** [comment]
that's a really good point @sam-github 

Should we try it for the next round?

**Comment by gibfahn** [comment]
Taking this off the agenda, we discussed and agreed to try it.

**Comment by MylesBorins** [comment]
We did this last time, but having a group to review at the end was v effective
