### ISSUE TITLE
remove protection on staging branches

### ISSUE THREAD

**Issue by MylesBorins** [nodejs/Release#219]
If we make rules about always signing commits on staging branches I think we can avoid needing to have it locked. Not being able to force push, with lease of course, is frustrating.

**Comment by hbetts** [comment]
Not directly related to the frustrations of force pushing changes, but I wanted to say that I really like the idea of adopting a culture of signing commits.

**Comment by gibfahn** [comment]
When you say signing commits, do you mean gpg signing?

**Comment by MylesBorins** [comment]
indeed

**Comment by gibfahn** [comment]
SGTM
