### ISSUE TITLE
Meeting schedule

### ISSUE THREAD

**Issue by rvagg** [nodejs/Release#224]
We have a meeting schedule for 12 hours from now. Unfortunately I have an overlap so can't make it but I also don't see anyone spearheading these meetings. It seems like we need to have a discussion about frequency and who is going to take facilitation responsibility for them (and have them announced at least 12 hours in advance). At a minimum we need to get the [calendar](https://nodejs.org/calendar) in sync with what we actually do.

**Comment by gibfahn** [comment]
I'm pretty new to the LTS WG, but I'd be happy to take on raising the issues and doing the minutes.

We have been meeting at the times in the calendar this year (I think we missed one).

**Comment by gibfahn** [comment]
Meeting: https://github.com/nodejs/LTS/issues/225
