### ISSUE TITLE
Potential v4.x backports

### ISSUE THREAD

**Issue by gibfahn** [nodejs/Release#231]
We have a couple of requested backports for v4.x, so opening this issue to track them. Please add to the list as you find them.

Things like the `exitedAfterDisconnect` backport may generate enough discussion that it's worth spinning out a separate issue, we can do that as it becomes necessary.

### Semver-minor
- **cluster:** alias suicide to exitedAfterDisconnect [#7998](https://github.com/nodejs/node/pull/7998) (Refs: [#13684](https://github.com/nodejs/node/pull/13684))

### Semver-patch

- [ ] **deps:** upgrade OpenSSL to version 1.0.2l [#13233](https://github.com/nodejs/node/pull/13233) (Refs: [#12913](https://github.com/nodejs/node/pull/12913) and  [#12691](https://github.com/nodejs/node/issues/12691))
- [ ] **deps:** cherry-pick 18ea996 from c-ares upstream [#13883](https://github.com/nodejs/node/pull/13883#issuecomment-317256463)

**Comment by MylesBorins** [comment]
we could modify #7998 to create an alias for exitedAfterDisconnect with no warning... this would be able to land as a patch

**Comment by mhdawson** [comment]
+1 on Myles suggestion for an alias.

**Comment by gibfahn** [comment]
>we could modify [#7998](https://github.com/nodejs/node/pull/7998) to create an alias for exitedAfterDisconnect with no warning... this would be able to land as a patch

I don't understand, AFAICT  [#7998](https://github.com/nodejs/node/pull/7998) doesn't have a warning, isn't this just an alias:

![image](https://user-images.githubusercontent.com/15943089/27170346-7587b766-51a5-11e7-9176-6319e4209730.png)

Also isn't adding an alias (i.e. a new property) `semver-minor`?

**Comment by MylesBorins** [comment]
closing as v4.x is not likely to get another release
