### ISSUE TITLE
Release Schedule can now be found in the wiki

### ISSUE THREAD

**Issue by MylesBorins** [nodejs/Release#236]
https://github.com/nodejs/LTS/wiki

Please review and let me know if you have any questions... I've made the schedule for both q3 and q4. I currently schedule the next Semver-Minor release to take place November 7th, as there are 5 Tuesdays in October. We could alternatively schedule the next minor release for September 5th, as August has 5 Tuesdays as well. I am leaning towards November as I'll be out of town for a good chunk of August, and I think we need a bit more of a backlog.

As long as everyone is ok with the current schedule I think we should add a link in the readme.

**Comment by gibfahn** [comment]
LGTM, would review PR

**Comment by bnb** [comment]
@MylesBorins Is it possible to add a section about EOL LTS? For future proofing (since in a few years we'll start accumulating more) and to ensure there's messaging around v4?

**Comment by MylesBorins** [comment]
Afaik that is included in the readme... More information regarding EOL also
makes sense in the readme. This was only put in the wiki to make it easier
to make changes

**Comment by sam-github** [comment]
@MylesBorins I thought that every other month (about) would be semver-minor LTS release, but it looks like the 6.x semver-minors are about every 4 months. This is about 6 months to go from merge to master to  availability in LTS.

Is it the right balance of speed vs stability?

**Comment by MylesBorins** [comment]
Every other month is far too often imho. Once a quarter seems pretty
reasonable to me.

**Comment by sam-github** [comment]
Once a quarter seems OK to me, too, but are we doing 4 times a year, or is it 3 or less?

Also, 4.x release schedules aren't on the wiki, is that because they are as-needed not that its out of active maintenance?

**Comment by MylesBorins** [comment]
indeed. There are no more planned 4.x releases. We will likely do another maintenance release before it is EOL… but would prefer to not really make changes that are not fixing experience breaking bugs

**Comment by Fishrock123** [comment]
I recommend linking to it from the readme.

**Comment by mhdawson** [comment]
Once a quarter for the minors seems reasonable to me.  We can probably add the link to the readme and update if it needs updating later.
