### ISSUE TITLE
backport updates to windows build script to v6.x

### ISSUE THREAD

**Issue by MylesBorins** [nodejs/Release#238]
A couple changes have landed upstream, it would be nice to track all three being backported

/cc @refack @joaocgreis

- [ ] [build,windows: Implement python detection](https://github.com/nodejs/node/pull/13900)
- [ ] [build,win: use latest installed VS by default and respect VS version for building addons](https://github.com/nodejs/node/pull/13911)
- [ ] [build,windows: fix vcbuild.bat](https://github.com/nodejs/node/pull/13969)

**Comment by MylesBorins** [comment]
ping @refack there seems to be quite a few more of these including https://github.com/nodejs/node/pull/15056

would you be able to do an audit?

**Comment by MylesBorins** [comment]
ping @refack

**Comment by refack** [comment]
Auditing.
