### ISSUE TITLE
Should backport PRs target `v6.x` instead of `v6.x-staging`?

### ISSUE THREAD

**Issue by MylesBorins** [nodejs/Release#240]
Perhaps backport PRs should target the release branch rather than the staging branch.

We may find that less PRs require rebases as the tree underneath isn't getting rebased away after the release.

They may get stale against the staging branch, but it is generally prepared in a short sprint, so I don't think that really matters.

Thoughts?

**Comment by sam-github** [comment]
In my experience many PRs depend on earlier PRs, usually for cosmetic textual reasons (changes were close to each other) and targeting the -staging branch decreases conflicts, and the rebase against -staging when staging is rewritten is trivial/automatic. Even if we targeted the non-staging branch, rebase is still required before fast-forwarding onto -staging.

But you have more experience than me, I'm willing to try another work flow.

**Comment by gibfahn** [comment]
What's the benefit? I don't see how this would improve the workflow, and it means we can't land stuff on staging then (for example) do a security release.

Not 100% against it, I just don't see the gain.

**Comment by addaleax** [comment]
If the goal is just less rebasing, then what would make the most sense is to still *target* v6.x-staging, but *base* the branch off v6.x while backporting. That would work and should still keep us updated about possibly required rebases.

**Comment by MylesBorins** [comment]
That's exactly what I was thinking

The prs would target 6.x but be landed on 6.x-staging minimizing the need
for ongoing rebasing

**Comment by sam-github** [comment]
Unless the PR lands clean on 6.x but conflicts against v6.x-staging, in which case it has to target -staging. But maybe that's uncommon, lets try and see.

**Comment by MylesBorins** [comment]
Closing for now, things have not been as hard for people submitting PRs lately
