### ISSUE TITLE
v4.x maintenance release

### ISSUE THREAD

**Issue by MylesBorins** [nodejs/Release#241]
Seems like the backlog is getting big enough to justify a release. Should we aim to get it out with the v6.x release in Sept? Or push until Oct?

**Comment by Fishrock123** [comment]
Let's push to Oct - are you still down to be doing this?

**Comment by MylesBorins** [comment]
I'm up for it. I'll aim to get an rc out this week

**Comment by MylesBorins** [comment]
rc is out
