### ISSUE TITLE
Rename the repo to Release

### ISSUE THREAD

**Issue by mhdawson** [nodejs/Release#242]
Now that the charter has landed in https://github.com/nodejs/LTS/pull/223 we should rename the repo from LTS to Release.

Just polling for things that we need to do in advance.  I think we will get redirects from the old name.

**Comment by gibfahn** [comment]
+1 to pulling the trigger and changing things.

We should get redirects, but changing the links in docs would probably be a good idea anyway.

**Comment by mhdawson** [comment]
We also need to do some updates on the website as well.

**Comment by mhdawson** [comment]
@nodejs/lts @nodejs/release one last reminder to object otherwise I'll pull the trigger when I get a chance.

**Comment by gibfahn** [comment]
@mhdawson ping, also could you get the calendar updated as well?

**Comment by Fishrock123** [comment]
Seems good to me.

**Comment by mhdawson** [comment]
Calendar updated, still need to update Website.

**Comment by mhdawson** [comment]
PR to Website and TSC repo submitted, renamed the repo closing.
