### ISSUE TITLE
Release WG meeting Tuesday 19th September 2017

### ISSUE THREAD

**Issue by gibfahn** [nodejs/Release#244]
## Present

@nodejs/lts, maybe @nodejs/release if they're interested

## When

- 8PM Tuesday September 19th UTC, or [in your local timezone](
https://www.timeanddate.com/worldclock/fixedtime.html?msg=Node.js+LTS+Working+Group+Meeting&iso=20170920T20)
- Previous meetings: https://github.com/nodejs/LTS/issues/243 https://github.com/nodejs/LTS/issues/235

## Where

Hangouts on Air:
- Observers: https://www.youtube.com/watch?v=Y01b-pMIp8E
- Participants: https://hangouts.google.com/hangouts/_/ytl/FAKQ2SljNZeUb3zyu1Xn9fjys9nJPuijeuILWsADe1E=?eid=100598160817214911030&hl=en_US&authuser=0
- [Events page](https://www.youtube.com/my_live_events)
- [Minutes](https://docs.google.com/document/d/1aDehI4n6tLNi1Y5qSiEl0PCUCXoUG3E4SCaphBPeYnQ/edit?usp=sharing)

### nodejs/LTS

[CTC `lts-agenda` issues](https://github.com/nodejs/CTC/issues?q=is%3Aopen+is%3Aissue+label%3Alts-agenda) and [LTS `lts-agenda` issues](https://github.com/nodejs/LTS/issues?q=is%3Aopen+is%3Aissue+label%3Alts-agenda)

### nodejs/node

https://github.com/nodejs/node/pulls?utf8=%E2%9C%93&q=is%3Aopen%20is%3Apr%20label%3Av6.x%20

https://github.com/nodejs/node/pulls?q=is%3Apr+label%3Alts-watch-v6.x+label%3Asemver-minor+is%3Aclosed

* lib: var to const [#13756](https://github.com/nodejs/node/pull/13756)
* (v6.x backport) process: add --redirect-warnings command line argument [#14480](https://github.com/nodejs/node/pull/14480)
* \[v6.x backport\] doc,assert: document stackStartFunction in fail [#14427](https://github.com/nodejs/node/pull/14427)
* tracking issue: full VS2017 support [#13052](https://github.com/nodejs/node/issues/13052)
* (v6.x backport) src: allow CLI args in env with NODE_OPTIONS [#12677](https://github.com/nodejs/node/pull/12677)
* inspector: enable --inspect-brk in v6 [#12615](https://github.com/nodejs/node/pull/12615)
* Review semver-minor backports [#228](https://github.com/nodejs/LTS/issues/228)
### other

*Any questions in #node-dev on IRC or comments in this thread*

@nodejs/lts Please 👍 if you can make the meeting, and 👎 if you cannot.

**Comment by gibfahn** [comment]
I've left the `semver-minor` commits on the agenda because I think it'd be good to agree on them now, we could wait another 3 weeks, but then we're getting very close to the 6.12.0 rc. Given that some of these have been waiting for ~5 months, and are IMO needed on v6.x, I'd rather we got them locked in now.

**Comment by MylesBorins** [comment]
+1 to discussing the semver minors on monday

We want to add discussing V8 6.1 on 8.x LTS as well.

Unfortunately I'm going to be on a flight at the time of the meeting, would people be opposed to pushing it forward a couple hours?

**Comment by gibfahn** [comment]
So 7 pm UTC? Fine by me.

**Comment by MylesBorins** [comment]
I was thinking forward rather than back.

Might even be easier to push by 24 hours if people are open.

If the scheduling doesn't work that is totally fine. I'm on flights from 8:40 am UTC -> 9:30 pm

**Comment by jasnell** [comment]
Have a specific time in mind?

**Comment by MylesBorins** [comment]
The simplest thing I could suggest would be pushing exactly 24 hours

**Comment by Fishrock123** [comment]
I should be able to make it to either

**Comment by gibfahn** [comment]
Tuesday 19th at 21:00 UTC SGTM. There's nothing else on in the calendar then. Given that pretty much everything on the agenda is v6.x backports, having you in the meeting seems pretty key @MylesBorins 😁 .

I'll change the agenda, we can change back if people can't make it.

**Comment by sam-github** [comment]
That's 2pm pst, right? Works for me, though I have to walk out my door at exactly 3pm to meet the school bus at the end of the block.

**Comment by jasnell** [comment]
If we're pushing to Tuesday, I have a conflict at 2pm PST. 1pm is open, however.

**Comment by sam-github** [comment]
On Tuesday, anytime from 6am-8am, 9am-5pm PST works for me.

**Comment by gibfahn** [comment]
Okay, pushed back an hour for James.

Is there anyone who can't make this time?

**Comment by hbetts** [comment]
@gibfahn 
* Issue title, `18th` => `19th`
* Under _When_, `Monday` => `Tuesday`

**Comment by sam-github** [comment]
@MylesBorins @jasnell  @mhdawson do you have power to update the meeting time in the node calendar?

**Comment by gibfahn** [comment]
@hbetts updated, I _think_ it's correct now.

**Comment by Fishrock123** [comment]
This might be early for @rvagg? I forget what time it was at before.

**Comment by gibfahn** [comment]
>This might be early for @rvagg? I forget what time it was at before.

It's an hour earlier than it was before. Agreed that might be too early for @rvagg

**Comment by addaleax** [comment]
> 8PM Tuesday September 19th UTC, or in your local timezone

The link there is wrong, no?

**Comment by Fishrock123** [comment]
@addaleax appears to be, fixed it (I hope)

**Comment by mhdawson** [comment]
Creating hangout since it does not look like there is one.

**Comment by mhdawson** [comment]
https://hangouts.google.com/hangouts/_/ytl/oA5pbaRTQbV0jh-20XrXhqPYc0O8PBDDymD341-fCUU=?eid=100598160817214911030

**Comment by mhdawson** [comment]
Looks like I missed it, removing the links I added

**Comment by mhdawson** [comment]
Did the meeting happen, I don't see a link to meeting minutes ?

**Comment by sam-github** [comment]
@mhdawson check the issue history, the meeting got bumped to tomorrow, 8PM Tuesday September 19th UTC

**Comment by MylesBorins** [comment]
New time works for me

**Comment by rvagg** [comment]
Shifting by a day works better for me (normal slot no longer works for me) but we're down to 6am, so I'm not going to commit but I'll _try_.

**Comment by mhdawson** [comment]
@sam-github thanks, I caught the change in time but not the date.

**Comment by MylesBorins** [comment]
Do we have a link for the hangout?

**Comment by sam-github** [comment]
was just about to ask, seems not yet. @mhdawson can make one, or one of us could

**Comment by sam-github** [comment]
I'm doing it.

**Comment by sam-github** [comment]
https://hangouts.google.com/hangouts/_/ytl/FAKQ2SljNZeUb3zyu1Xn9fjys9nJPuijeuILWsADe1E=?eid=100598160817214911030&hl=en_US&authuser=0 <--- participants. looking for youtube link still

**Comment by abernix** [comment]
https://www.youtube.com/watch?v=Y01b-pMIp8E

**Comment by sam-github** [comment]
We often seem to go half an hour over, I wonder if we should just officially make the meeting longer when its next scheduled? Alternatively, we could try to have meetings more often. The long discussion about V8 6.1 might be considered a one-off, but unless my memory fails me, the last two meetings also went half an hour over, there always seems to be something to discuss.

**Comment by gibfahn** [comment]
@sam-github probably worth raising a separate issue to discuss that.
