### ISSUE TITLE
How long before LTS date should we cut off Semver-Minor Releases

### ISSUE THREAD

**Issue by MylesBorins** [nodejs/Release#245]
Currently we land Semver-Minor releases until the cutoff date of LTS. Should we consider cutting this off sooner to allow the branch to stabilize?

**Comment by addaleax** [comment]
I don’t think semver-ness is a reasonable way to judge the risk of introducing bugs that comes with changes.

**Comment by mhdawson** [comment]
I'd agree it more about risk than strictly semver-ness (except for major which we already exclude).

Once in LTS we do use semver-minor to decide what to review, but I expect that if there was a particularly large/risky patch PR that would end up in the LTS meeting for review as well (but we have no formal process for that).

**Comment by gibfahn** [comment]
I think it is up to the person doing the releases to evaluate the dangerousness of the commits, and to put anything they're not sure of up for review by @nodejs/lts

**Comment by danielgindi** [comment]
Did the biweekly release cycle stop?

**Comment by MylesBorins** [comment]
This seems to have been ok in the last couple releases
