### ISSUE TITLE
backport http: Eliminate ClientRequest capture by Agent socket listeners

### ISSUE THREAD

**Issue by drewfish** [nodejs/Release#247]
At Yahoo we have a custom branch with a few internal changes. We've also backported https://github.com/nodejs/node/pull/10134. I see that it's labelled `dont-land-on-v6.x` since it doesn't land cleanly. However the code delta reduces heap usage so might be valuable for everyone.

Let me know if you'd like me to attempt a PR on `v6.x-staging` (or whatever makes sense).

**Comment by MylesBorins** [comment]
@drewfish if you can make a backport PR we would 100% be open to landing it. Thanks.

**Comment by drewfish** [comment]
https://github.com/nodejs/node/pull/15500

**Comment by gibfahn** [comment]
@drewfish thanks for raising the PR. As a general principle if something hasn't been backported and you think it's worth having (makes life easier, fixes bugs etc), then it's just a question of someone being willing to raise the backport PR.

If it's `semver-minor` then `Release` have to review, but our basic question is "will this benefit anyone", so a comment in the original PR saying "this fixes an issue for us" is really helpful.

So let us know what else you have in your internal branch, hopefully we can get everything in that you guys need.

I'll close, as I think this is resolved, but as I said please do comment on other issues that you'd like backported.
