### ISSUE TITLE
Tentative date for 8.x to go LTS

### ISSUE THREAD

**Issue by MylesBorins** [nodejs/Release#249]
During the last meeting we discussed a date of October 31st for 8.x LTS.

Can we use this issue to reach consensus. Once consensus is reached I can work with the foundation marketing team to get comms out around the date

**Comment by gibfahn** [comment]
LGTM, with the understanding that we'll try to have the final builds done by a week before, so we just do the final promotion on the 31st. That's what we agreed at the meeting anyway.
