### ISSUE TITLE
should we make the WG meetings longer?

### ISSUE THREAD

**Issue by sam-github** [nodejs/Release#251]
We often seem to go half an hour over, I wonder if we should just officially make the meeting longer when its next scheduled? Alternatively, we could try to have meetings more often. The long discussion about V8 6.1 might be considered a one-off, but unless my memory fails me, the last two meetings also went half an hour over, there always seems to be something to discuss.

From: https://github.com/nodejs/Release/issues/244#issuecomment-330679452

**Comment by gibfahn** [comment]
I'd be +1 on scheduling it to be 90 minutes, once we have nothing less to discuss we just end it anyway, so it shouldn't cause any issues.

**Comment by MylesBorins** [comment]
Since we don't have regular meeting this is no longer needed to be discussed
