### ISSUE TITLE
npm 3.10.10 (bundled with nodejs 6.11.3) installed module graceful-fs dependency is incorrect

### ISSUE THREAD

**Issue by dusura** [nodejs/Release#252]
Not sure if here is the correct place for this.

npm 3.10.10 that comes bundled with nodejs 6.11.3 (Windows MSI x64 version) has graceful-fs module version 4.1.9 installed when the npm dependency specifies "~4.1.9" and graceful-fs version 4.1.11 has been available since before the release.

**Comment by gibfahn** [comment]
The npm bundled with node is checked into the node source tree at [`deps/npm/`](https://github.com/nodejs/node/tree/v6.x/deps/npm), including it's [`node_modules`](https://github.com/nodejs/node/tree/master/deps/npm/node_modules) directory. It's nearly always updated by pull requests from the npm team.

Therefore the dependency versions won't change unless someone raises a Pull Request to update them. Is there a compelling reason to update `graceful-fs` (or any of the other dependencies)?

cc/ @nodejs/npm 

[nodejs/node](https://github.com/nodejs/node/) would be the right place for this FWIW.

**Comment by dusura** [comment]
Thanks for the info. Yes, there is a compelling reason to update `graceful-fs`. npm does not work reliably on Windows systems with AntiVirus when installing modules because it copies module files to a temporary location before completing installation and AntiVirus software can lock these files causing npm to fail when trying to move the module files to their permanent location. `graceful-fs` 4.1.11 has a fix for this.

**Comment by iamstarkov** [comment]
@gibfahn should it be closed?
