### ISSUE TITLE
Update at TSC Meeting

### ISSUE THREAD

**Issue by mhdawson** [nodejs/Release#254]
We've added a section to the TSC meeting where Working Groups will give an update.  It would be good to cover:

* Highlights of major activities under way
* Current problems/risks facing the group
* Ways that the TSC could further support the activities of the WG

@nodejs/lts, @nodejs/release, @nodejs/citgm we need a volunteer.

@MylesBorins, @gibfahn given the short notice maybe it would make sense for one of you two to do this first update ?

**Comment by gibfahn** [comment]
So this is for the meeting in two days time?

**Comment by MylesBorins** [comment]
I can do the update

**Comment by MylesBorins** [comment]
@gibfahn if you would like to attend the meeting to give this update instead please lmk

Things to include in update

* Current date for LTS
* Discussions we are having around LTS stability and cut offs for certain types of changes
* Release cadence for LTS
* V8 6.1 / 6.2 for 8.x

Anything else people can think of?

**Comment by mhdawson** [comment]
We should probably at least mention the transition to Gibson doing the LTS releases ?

**Comment by MylesBorins** [comment]
Absolutely!

**Comment by mhdawson** [comment]
We might want to mention Citgm as I think we are challenge keeping it as green as we'd like.

**Comment by jasnell** [comment]
Given the effort that @gibfahn has been putting in, I think it would be worthwhile to invite him to do the update if he'd like. He definitely deserves the recognition for the work he's been doing.

**Comment by gibfahn** [comment]
I'd be happy to join in and maybe add any info, maybe we could work on it together @MylesBorins ? Given that you've been doing the 6.x releases, I think you probably know more about the main backporting/LTS stuff.
