### ISSUE TITLE
Sync README with GitHub teams

### ISSUE THREAD

**Issue by Trott** [nodejs/Release#256]
The people listed as LTS folks here do not correspond with the people who are members of the @nodejs/lts team. The two lists should be in synch, no?

**Comment by sam-github** [comment]
I'd think so, the https://github.com/orgs/nodejs/teams/lts/members list doesn't look accurate at all, it doesn't even look like a merge of LTS and Release

**Comment by sam-github** [comment]
Fwiw, I think that https://github.com/nodejs/Release#lts-team-members is accurate, is there anyone in @nodejs/lts who disagrees?

**Comment by gibfahn** [comment]
Now would be a good time to refactor the teams, we should really have:

- `Release` - top level team, everything else is a sub-team of this
  - `LTS`
  - `releasers`
  - `citgm`

And I agree that the lists in the README should be accurate (they were the ones that were just reviewed as part of @mhdawson's PR).

**Comment by mhdawson** [comment]
+1 to syncing up the teams with the README as it should be the most accurate.

**Comment by MylesBorins** [comment]
AFAIK this has been done

**Comment by gibfahn** [comment]
Not sure if it should be in this issue or another, but I don't think there is a nodejs/Release top-level team.

**Comment by richardlau** [comment]
We could also use [ncu-team](https://github.com/nodejs/node-core-utils/blob/master/docs/ncu-team.md) as other repos are.
