### ISSUE TITLE
Clarify that releases in maintenance are still LTS

### ISSUE THREAD

**Issue by mcollina** [nodejs/Release#257]
In the README we talk about _active_ LTS vs maintenance. I think we should call both of them LTS, one active and one in maintenance. I think this was the spirit of the document, but it could be read in the wrong way, e.g. node 4 is not LTS anymore.

We are still supporting node 4 until April 2018.

**Comment by hbetts** [comment]
This has occasionally caused some confusion, yet it also seems, from my
reading, that _Active_ and _Maintenance_ are equally mentioned as stages of
an LTS release.

Therefore, it seems, in my opinion, that it could be more of a messaging
problem. Maybe we just aren't consistently communicating that 'maintenance'
is a later stage of LTS.

**Comment by gibfahn** [comment]
>2: The 8.x Maintenance LTS cycle is currently scheduled to expire early on December 31, 2019 to align with the scheduled End-of-Life of OpenSSL-1.0.2. Note that this schedule may change if the version of OpenSSL is upgraded to 1.1.x before 8.x enters the Active LTS cycle.

<br/>

>Every major version covered by the LTS plan will be actively maintained for a period of 18 months from the date it enters LTS coverage. Following those 18 months of active support, the major version will transition into "maintenance" mode for 12 additional months.
>
>exact date that a release stream will be moved to LTS, moved between LTS modes, or deprecated will be chosen no later than the first day of the month. If it is to be changed, it will be done with no less than 14 days notice.
>
>Given this schedule, there will be no more than two active LTS releases at any given time, overlapping for a maximum period of six months.

Are these the lines you find unclear? For me they seem to be clearly talking about Active vs Maintenance LTS modes, but please do raise a PR if you think it could be more unambiguous (I find it hard to read these docs from the point of view of a newcomer to Node).

**Comment by mhdawson** [comment]
I agree both that the intent is that a release is LTS throughout the 30 months and that the text above seems ok.  BUt as @gibfahn if you can propose something that migth be clearer to people not quite as close to the process that would be great.

**Comment by hbetts** [comment]
I actually really like @jasnell's tweet - https://mobile.twitter.com/jasnell/status/829353751748042752

It clearly states the stage transition - `Active LTS to Maintenance LTS`

It also clearly states what people should expect as a result of the transition - `This means updates will be less frequent...`

Perhaps one item that could help would be to update the schedule diagram. Either remove `ACTIVE` from `ACTIVE LTS`, or add `LTS` after `MAINTENANCE`.

I'll see if I can't reach out to people and see what else could help improve the messaging around LTS stages.

**Comment by gibfahn** [comment]
>Perhaps one item that could help would be to update the schedule diagram.

+1, seems like a good idea.
