### ISSUE TITLE
Release WG meeting Monday 9th October 2017

### ISSUE THREAD

**Issue by Fishrock123** [nodejs/Release#261]
Since there is no issue open yet, and idk how to do the full HOA setup, I'm just opening this.

This meeting falls on the Thanksgiving Day for Canada. I may not be available.

Edit: Update - I _should_ be available, I think.

---

## Present

@nodejs/lts, maybe @nodejs/release if they're interested

## When

- 9PM Monday September 9th UTC, or [in your local timezone](
https://www.timeanddate.com/worldclock/fixedtime.html?msg=Node.js+Release+Working+Group+Meeting&iso=20171009T21)
- Previous meetings: https://github.com/nodejs/Release/issues/244

## Where

Hangouts on Air:
- [Observers]
- [Participants]
- [Events page](https://www.youtube.com/my_live_events)
- [Minutes]

### nodejs/LTS

[CTC `lts-agenda` issues](https://github.com/nodejs/CTC/issues?q=is%3Aopen+is%3Aissue+label%3Alts-agenda) and [LTS `lts-agenda` issues](https://github.com/nodejs/LTS/issues?q=is%3Aopen+is%3Aissue+label%3Alts-agenda)

### nodejs/node

https://github.com/nodejs/node/pulls?utf8=%E2%9C%93&q=is%3Aopen%20is%3Apr%20label%3Av6.x%20

https://github.com/nodejs/node/pulls?q=is%3Apr+label%3Alts-watch-v6.x+label%3Asemver-minor+is%3Aclosed

### other

*Any questions in #node-dev on IRC or comments in this thread*

@nodejs/lts Please 👍 if you can make the meeting, and 👎 if you cannot.

**Comment by gibfahn** [comment]
>Since there is no issue open yet, and idk how to do the full HOA setup, I'm just opening this.

Mostly just copy it from the previous meeting.

**Comment by gibfahn** [comment]
I'll attempt to attend this, but I'll be at the airport so 🤷‍♂️ . Also it's on in 3 hours, FYI @nodejs/lts.

**Comment by MylesBorins** [comment]
I think we should talk about V8 6.2

that being said if it is going to be super light attendence should we simply push a week?

**Comment by gibfahn** [comment]
>that being said if it is going to be super light attendence should we simply push a week?

Happy to push a week, why don't we see how many people join, and push if it's light.

**Comment by Fishrock123** [comment]
Let's push a week then - I'm going out after all.

**Comment by gibfahn** [comment]
Okay, let's treat this as postponed.
