### ISSUE TITLE
Proposed LTS Dates For 8.x Q4 2017 & Q1 2018 6.x + 8.x

### ISSUE THREAD

**Issue by MylesBorins** [nodejs/Release#263]
I'm scheduling for a minor release of the 8.x release line for January. It gives us three weeks to run the rc, and is a good target for landing V8 6.2 (🎉 escape analysis). I did not schedule a minor for 6.x, but I think that we could revisit this depending on what kind of requests for 6.x come down the pipeline.

@gibfahn does the schedule look good to you?

## Q4 2017 Carbon (8.x) Release Schedule

Date | Release
------------ | -------
October 31st | v8.9.0
November 21 | v8.9.1-rc
December 5th | v8.9.1
December 19th | v8.9.2-rc

## Q1 2018 Carbon (8.x) Release Schedule

Date | Release
------------ | -------
January 3rd | v8.9.2
January 17th | v8.10.0-rc
February 7th | v8.10.0
February 21st | v8.10.1-rc
March 7th | v8.10.1
March 21st | v8.10.2-rc
April 4th | v8.10.2

## Q1 2018 Boron (6.x) Release Schedule

Date | Release
------------ | -------
January 3st | v6.12.2
January 17th | v6.12.3-rc
February 7th | v6.12.3
February 21st | v6.12.4-rc
March 7th | v6.12.4
March 21st |v6.12.5-rc
April 4th | v6.12.5

**Comment by MylesBorins** [comment]
/cc @nodejs/lts @nodejs/tsc based on this calendar April 4th would be the date we would be moving Node.js v6.x into maintenance mode.

Any objections?

**Comment by mcollina** [comment]
No objections on Node.js v6 going into maintenance on April 4th. We should note that Node 6 is still supported for a full year after that.

When will V8 6.2 be ready for us to use?

**Comment by MylesBorins** [comment]
@mcollina it is already on master 🎉

So my assumption is that it will land in 9.x and we will have 2 months of it running in the wild (and time to figure out ABI compat 😅)

**Comment by bricss** [comment]
I were thinking that V8 6.2 backport will land in 8.x right before LTS 🙄

**Comment by mhdawson** [comment]
+1 to the suggested schedule.

**Comment by cjihrig** [comment]
SGTM!

**Comment by drewfish** [comment]
What about 4.x End-of-Maintenance? (Perhaps that should be discussed a separate issue.)

**Comment by MylesBorins** [comment]
good call @drewfish opening a PR with proposed dates

**Comment by rvagg** [comment]
@mylesborins do we have a Q4 schedule for Boron somewhere?

**Comment by MylesBorins** [comment]
Already in the wiki

Dates are the same as carbon

**Comment by MylesBorins** [comment]
I've updated the wiki. We may revisit for another minor on 6.x in January

**Comment by MylesBorins** [comment]
I've updated the wiki. We may revisit for another minor on 6.x in January
