### ISSUE TITLE
Release WG meeting Monday 30th October 2017

### ISSUE THREAD

**Issue by gibfahn** [nodejs/Release#269]
## Present

@nodejs/lts, maybe @nodejs/release if they're interested

## When

- 9PM Monday September 9th UTC, or [in your local timezone](
https://www.timeanddate.com/worldclock/fixedtime.html?msg=Node.js+Release+Working+Group+Meeting&iso=20171030T21)
- Previous meetings: https://github.com/nodejs/Release/issues/261

## Where

Hangouts on Air:
- [Observers]
- [Participants]
- [Events page](https://www.youtube.com/my_live_events)
- [Minutes]

### nodejs/LTS

[CTC `lts-agenda` issues](https://github.com/nodejs/CTC/issues?q=is%3Aopen+is%3Aissue+label%3Alts-agenda) and [LTS `lts-agenda` issues](https://github.com/nodejs/LTS/issues?q=is%3Aopen+is%3Aissue+label%3Alts-agenda)

### nodejs/node

https://github.com/nodejs/node/pulls?utf8=%E2%9C%93&q=is%3Aopen%20is%3Apr%20label%3Av6.x%20

https://github.com/nodejs/node/pulls?q=is%3Apr+label%3Alts-watch-v6.x+label%3Asemver-minor+is%3Aclosed

### other

*Any questions in #node-dev on IRC or comments in this thread*

@nodejs/lts Please 👍 if you can make the meeting, and 👎 if you cannot.

**Comment by rvagg** [comment]
Won't be able to join due to meeting clash in this time slot each week. If this stays fixed to UTC then it should free up for me when the US does its DST shift.

**Comment by gibfahn** [comment]
Is anyone able to host?

**Comment by MylesBorins** [comment]
What's the link for the meeting?

**Comment by gibfahn** [comment]
Don't think anyone who is able to host is here, so looks like we'll have to cancel this one.

**Comment by Fishrock123** [comment]
Oh, I have access but idk how to set it up. We could run it on uberconference?

**Comment by gibfahn** [comment]
>Oh, I have access but idk how to set it up. We could run it on uberconference?

Whatever works should be fine.

**Comment by MylesBorins** [comment]
I don't think we have quorum, and not much of an agenda, not a huge deal to punt imho

**Comment by Fishrock123** [comment]
Aight. When should we schedule this next then? Just in the usual 3 weeks?

**Comment by gibfahn** [comment]
>Aight. When should we schedule this next then? Just in the usual 3 weeks?

SGTM
