### ISSUE TITLE
Plan v8.x release for November 7

### ISSUE THREAD

**Issue by MylesBorins** [nodejs/Release#280]
Currently we have a 6.x and 4.x release planned for next tuesday. I'd like to propose that we also schedule a semver patch release of 8.x to patch the collection of problems that we found in 8.9.0

If we find that the openssl release is not time sensitive I think it makes sense to fold it in to the tuesday release instead of rushing something out on friday

thoughts?

/cc @nodejs/lts @gibfahn

**Comment by gibfahn** [comment]
> the collection of problems that we found in 8.9.0

Can we keep a list of them here?

- Possible openssl release
- process.release.lts [#16656](https://github.com/nodejs/node/pull/16656)
- revert "refactor to use http internals" [#16660](https://github.com/nodejs/node/pull/16660)

**Comment by MylesBorins** [comment]
We will also want to include

https://github.com/nodejs/node/pull/16724

**Comment by MylesBorins** [comment]
Change all the lists to check marks, everything is currently up to date as to which patches are currently on v8.x-staging

**Comment by MylesBorins** [comment]
Closing this out for a meta release issue
