### ISSUE TITLE
November 7th release for all lines

### ISSUE THREAD

**Issue by MylesBorins** [nodejs/Release#282]
So we have the openssl security release to do which we have deemed low-severity and as such is going out with the regularly scheduled releases on November 7th. We have LTS releases covered, but need someone to step up to handle the 9.x release. The openSSL changes have already been staged on v9.x-staging. although we may want to roll more stuff into the release. The various patches for breakages from v8.9.0 have been staged, there should not any other commits included in the release AFAIK. 

- [v4.8.6](https://github.com/nodejs/node/pull/16500) by @MylesBorins
- [v6.12.0](https://github.com/nodejs/node/pull/16263) by @MylesBorins
- [v8.9.1](https://github.com/nodejs/node/pull/16783) by @gibfahn 
- v9.0.1 or v9.1.0 by ???

Who can take care of the 9.x release? /cc @cjihrig @evanlucas @jasnell @Fishrock123 @rvagg

**Comment by MylesBorins** [comment]
ping @nodejs/release is someone picking up the 9.x release?

**Comment by cjihrig** [comment]
I *think* I can pick up the 9.x release.

**Comment by rvagg** [comment]
I'll do it if it's a problem for you @cjihrig, let me know

**Comment by cjihrig** [comment]
Thanks @rvagg!
