### ISSUE TITLE
Can not shutdown nodejs in Win8

### ISSUE THREAD

**Issue by Mabinogiysk** [nodejs/Release#289]
I want to install hexo on my computer. I executed command `npm install -g hexo-cli` in PowerShell and it stop download hexo at some point.
I terminated this command with `Ctrl + C`, it failed. Then I terminated it with Task Manager, it also failed.
I even could not shutdown my computer. I have tried twice and nothing different.
![image](https://user-images.githubusercontent.com/12441989/33162231-4d7f1466-d063-11e7-94b0-142c908f4bcb.png)
![image](https://user-images.githubusercontent.com/12441989/33162240-6d668584-d063-11e7-9cc7-a35740974329.png)
nodejs version: v8.9.1
npm version: v5.5.1
PowerShell version: v4.0

**Comment by mhdawson** [comment]
I think you may have opened this in the wrong repository as I don't understand how it relates to the Release WG.  Possibly you want to open in https://github.com/nodejs/help
