### ISSUE TITLE
LTS/Release repo naming

### ISSUE THREAD

**Issue by bnb** [nodejs/Release#296]
I'm working on some writing right now and I came across the [Ember.js LTS Support blog post](https://www.emberjs.com/blog/2016/09/07/ember-node-lts-support.html). In this blog post, there's a link to nodejs/LTS - the former name of this repo, which was the intended target at time of writing (September 2016).

With the introduction of the _current_ nodejs/lts repo, there's a possibility for easy confusion there - the subject matter is similar, but the actual content is different. I also believe that, previously, any link to nodejs/lts would have appropriately redirected to this repo.

Not sure if this is something that the Release WG is interested in fixing, or if it even _is_ fixable, but I did want to raise it to let y'all know in case it _was_ something you want to fix 👍

**Comment by MylesBorins** [comment]
🙃

i'd like to propose the following

* change the name of the current `nodejs/lts` to `nodejs/lts-schedule`
* include a copy of the current schedule in the readme
* temporaryily change `nodejs/release` back to `nodejs/lts`
* revert that change immedietely

This should "theoretically" recreate the redirect behavior that we were expecting.

**Comment by gibfahn** [comment]
Whoops! +1 to what @MylesBorins suggests, I don't think that was intentional and we should fix linking.

**Comment by cjihrig** [comment]
SGTM

**Comment by mhdawson** [comment]
SGTM

**Comment by cjihrig** [comment]
The plan in https://github.com/nodejs/Release/issues/296#issuecomment-354373040 is done, minus adding a copy of the schedule to the lts-schedule repo.
