### ISSUE TITLE
Creating release schedule for Current line

### ISSUE THREAD

**Issue by MylesBorins** [nodejs/Release#299]
Hey all,

Up until now we've gotten away without an explicit release schedule for our current release line. Generally this has worked, but lately it has been a bit of a problem. There was a 1 month gap between v9.3.0 and the v9.4.0 proposal, which in turn can block our ability to do an LTS release (no commits to audit, no LTS release)

I'd like to propose that we at the very least plan bi-weekly releases and have the release managers volunteer for the specific releases in advance

thoughts @nodejs/release?
  
edit: there was also a 1 month gap between 9.2.0 and 9.3.0, 9.2.1 was a security release

**Comment by evanlucas** [comment]
Works for me. Sorry I haven't been as available to cut releases lately due to work and vacation :]

**Comment by Fishrock123** [comment]
This is seeming more and more like a good idea to me.

**Comment by mhdawson** [comment]
I like the idea, but will leave it up to those doing the Current releases :)

**Comment by gibfahn** [comment]
Big +1 on this, at this point it seems necessary. Otherwise Myles ends up maintaining two release lines.

**Comment by MylesBorins** [comment]
I'd like to propose that we commit to bi-weekly releases on the first and third Tuesday of the month as this will align with the LTS release / RC schedule.

We can batch by quarter and have release managers sign up in advance for the releases they want to handle. I'd personally like to see every active release manager handle at least 1 release per quarter.

Thoughts?

**Comment by jasnell** [comment]
Assuming there are people to make it happen, then ok.

BTW, my current plan is to release Node.js 10.0.0 on April 24th

**Comment by jasnell** [comment]
Also, keep in mind that a significant reason for the delay been 9.3 and 9.4 was the holiday that interceded in the middle of that. Whatever schedule is chosen needs to account for reasonable delays, and I believe the holidays count as such

**Comment by MylesBorins** [comment]
@jasnell there was a month between 9.2 and 9.3 as well, fwiw
