### ISSUE TITLE
Revising changelog

### ISSUE THREAD

**Issue by mhdawson** [nodejs/Release#307]
Review and make decision on https://github.com/nodejs/node/pull/17062

**Comment by mhdawson** [comment]
I'm -0 as well.

**Comment by BridgeAR** [comment]
Any conclusion here?

**Comment by mhdawson** [comment]
@nodejs/release any other thoughts?

**Comment by gibfahn** [comment]
I agree with @MylesBorins in general, although I don't think it makes much difference as the changelogs also include the PR numbers.

**Comment by MylesBorins** [comment]
I'll move my stance to -1 if it simplifies things

Update the notable changes all day, do not change then commit messages for
anything other than escaping special characters

**Comment by BridgeAR** [comment]
Since this is now a -1 I went ahead and closed the PR. I think this is resolved now and should be closed.

**Comment by cjihrig** [comment]
I agree with https://github.com/nodejs/Release/issues/307#issuecomment-370249979
