### ISSUE TITLE
Delaying v8.x semver-minor release

### ISSUE THREAD

**Issue by MylesBorins** [nodejs/Release#308]
There are two semver minor PRs against 8.x that we would like to land (they are finally green), but have not had time to do a proper r.c.

https://github.com/nodejs/node/pull/16413 (update V8 to 6.2)
https://github.com/nodejs/node/pull/18622 (add support for openssl 1.1.0)

The release is planned for next Tuesday. I think we should delay.

We have a couple options

* Backout semver minor commits from 8.x and do a semver patch release
* Delay release by 1 - 2 weeks
* Skip this release and make the March release of 8.x semver minor.

Thoughts?

**Comment by richardlau** [comment]
Agreed that we should allow time for a proper release candidate for the two mentioned semver-minors. I guess the question is whether the remaining semver patch commits warrant a semver patch release.

cc @kasicka re. https://github.com/nodejs/node/pull/16509#issuecomment-363143369 and https://github.com/nodejs/node/pull/18625

**Comment by richardlau** [comment]
What about releasing the semver-minors that are in the current rc as planned and delay the two mentioned commits to the next semver-minor (possibly make March also semver-minor)?

**Comment by MylesBorins** [comment]
@richardlau we've actively avoided doing multiple semver minors for LTS in the past. The next scheduled minor would be next quarter... we could do this but I don't like the precedent it sets

**Comment by mhdawson** [comment]
My preference would be to delay by 1-2 weeks.

**Comment by MylesBorins** [comment]
@mhdawson I am open to that

The current schedule has the 20th as the date for the next r.c, how do you think we should go about that?

**Comment by gibfahn** [comment]
>The current schedule has the 20th as the date for the next r.c, how do you think we should go about that?

We've already delayed a week right? So in total this release would be 3 weeks late. In that case we probably just want to drop the March 6th release and do 8.10.1 on April 3rd instead.

Date | Release
------------ | -------
January 2nd | v8.9.4
January 23th | v8.10.0-rc
~February 13th~ | ~v8.10.0~
February 27th | v8.10.0
~February 20th~ | ~v8.10.1-rc~
~March 6th~ | ~v8.10.1~
March 20th | v8.10.~2~1-rc
April 3rd | v8.10.~2~1

**Comment by MylesBorins** [comment]
@gibfahn would we potentially just want to push the release until the 6th?

**Comment by gibfahn** [comment]
>@gibfahn would we potentially just want to push the release until the 6th?

You mean the v8.10.0 release? I'm not opposed to doing that.

**Comment by MylesBorins** [comment]
I think that is what we should do to keep calendar simple

**Comment by mhdawson** [comment]
+1 to pushing to the 6th as well.

**Comment by gibfahn** [comment]
Done in https://github.com/nodejs/Release/wiki/Home/947ac13a5365e28aa8117aa2be40cd5347ffe7ca
