### ISSUE TITLE
Breaking change landed in v9.6.0

### ISSUE THREAD

**Issue by MylesBorins** [nodejs/Release#312]
https://github.com/nodejs/node/pull/17403#issuecomment-367814130 for reference

TLDR a commit landed that should have arguably been semver major. Should we do another release today or wait until next week?

**Comment by gibfahn** [comment]
I think the quicker the better. Reverting this is arguably a semver-major change too, so the longer it's out there as latest the worse it is.

Obviously if no-one has the bandwidth to do another release right now then next week hopefully isn't the end of the world.

@watson could you give an idea of how many people you think this might break?

**Comment by MylesBorins** [comment]
we have a fix open https://github.com/nodejs/node/pull/18944

If CI is green I'll put together a release and get it out tonight

**Comment by MylesBorins** [comment]
v9.6.1 is out the door
