### ISSUE TITLE
Don't pull in single commits from a multi commit PR

### ISSUE THREAD

**Issue by BridgeAR** [nodejs/Release#313]
There were a couple of occasions where the backporting tool seemed to pull in single commits from a multi commit PR even though other commits did not land cleanly (e.g. https://github.com/nodejs/node/pull/17615). This could result in weird states. I am currently not sure what tool is used for getting in all the commits and how it is used. So it would be great if someone could have a look at this (and maybe also provide me with some useful links / info? :-) ).

**Comment by gibfahn** [comment]
Looking at that PR I think you're talking about what is used for current release?

If so @MylesBorins has a manual process that he currently follows.

The tool we use is `branch-diff`, you can read about the LTS process [in releases.md](https://github.com/nodejs/node/blob/master/doc/releases.md).

Basically it's a manual process to revert the other commits if a cherry-pick fails halfway through.

We should have a tool though, see https://github.com/nodejs/node-core-utils/issues/194 for that.

**Comment by gibfahn** [comment]
What we do for current is:

> - Run branch-diff to generate a list of shas:
>   ```bash
>   branch-diff --reverse --sha
>   ```
> - For each commit try to cherry-pick it, if it fails:
>   - Open PR in browser.
>   - Either fix conflicts and backport, or don't fix and bail.
>   - If PR had multiple commits, `git cherry-pick --quit` and `git reset --hard` to
> get rid of any previous commits from that PR.
>   - Add a comment to PR either requesting a backport or saying it's
> `dont-land`.
>

**Comment by BridgeAR** [comment]
Since the current structure should already cover my case, I am going to close this issue. Seems like it was a accident.
