### ISSUE TITLE
[question] What's the plan for release 9.x?

### ISSUE THREAD

**Issue by ozbillwang** [nodejs/Release#315]
I do notice `release 9.x` is not planned with active status and its end of life is June 2018 (earlier than release 8.x)

I have an application running in 7.2, and plan to upgrade  it. 

Should I upgrade it to release 9.x or release 8.x?

Need your input.

**Comment by MylesBorins** [comment]
Hey Bill,

Generally we advise moving to an LTS release. Do moving to 8.x would make
the most sense at the moment. That branch has support until the end of 2019

**Comment by ozbillwang** [comment]
Thanks for so quick response. @MylesBorins 

My feeling is, I should upgrade to release with even numbers, such as 4, 6, 8 and 10 in the future.
