### ISSUE TITLE
Delay April LTS by 1 week for security release

### ISSUE THREAD

**Issue by MylesBorins** [nodejs/Release#316]
Hey All,

Thoughts on delaying the LTS release by a week to account for the security release going out next Tuesday?

**Comment by renanbastos93** [comment]
Hey @MylesBorins ,

I agree your suggestion, it's better one release going that include security.

**Comment by MylesBorins** [comment]
@renanbastos93 I was not suggesting to delay the security release. We have another LTS release planned for the following week, I was suggesting we move that release forward a week.

We generally keep the security releases to only include the security related commits to ensure that people who need to upgrade can do so with minimal changes. This also makes it easier to figure out which patches are related to security and float only those.

**Comment by cjihrig** [comment]
SGTM

**Comment by renanbastos93** [comment]
@MylesBorins Oh, I understand sorry for my mistake. I'm anxious for this release going.

**Comment by MylesBorins** [comment]
@renanbastos93 for which release line? Is something in particular broken you are waiting on? We could push out a release on wednesday if something is problematic

**Comment by gibfahn** [comment]
SGTM

**Comment by renanbastos93** [comment]
@MylesBorins It's nothing troublesome, thanks for the concern.
