### ISSUE TITLE
Pick the next ten codenames or something like that

### ISSUE THREAD

**Issue by Trott** [nodejs/Release#317]
As proposed by @ofrobots: It would be great if @nodejs/Release could select and publish the next 3, 4, 5, 10, 100 codenames so that we don't have a big discussion every time a destined-for-LTS release comes around. See https://github.com/nodejs/Release/issues/291 for a pretty good example of how out-of-hand this gets. Maybe it's just me, maybe this sort of discussion is fine, but I think it runs the risk of burying pretty much any other topic that needs to be talked about in a release.

Not sure if Release WG rules allow me to put this on the meeting agenda, but I'll label it as such and hope the answer is "yes". (There are Release-agenda and lts-agenda labels. Not sure if there's a difference.)

**Comment by Trott** [comment]
Oh, and once picked, publish, of course.

**Comment by Trott** [comment]
Here's my suggestion. Rubber-stamp it and I'll PR it into a document.

* Dubnium (10.x 2018)
* Erbium (12.x 2019)
* Fermium (14.x 2020)
* Gold (16.x 2021)
* Hydrogen (18.x 2022)
* Iron (20.x 2023)
* Krypton (22.x 2024)
* Lithium (24.x 2025)

By this point, we'll have hopefully decided to stop with the elements theme and let go of all the problems it entails: Many letters not represented, irksome to avoid poisons etc., often difficult or impossible to get a name that is familiar to the average English speaker ("Isn't Dubnium a music genre that is always at 114 bpm? Erbium? Was that named after Airbnb?")...

Maybe we can make a tradition of switching themes halfway through the alphabet every time.

**Comment by ofrobots** [comment]
Those code-names sound good enough for me. A rose by any other name...

Specially if there is no conclusion on #127, or if conclusion is for the status-quo (continue using code names), I would much prefer that we decide the names upfront, instead of drowning out release planning conversation with bike shedding on the code name.

**Comment by richardlau** [comment]
No objections here to those names.

**Comment by olstenlarck** [comment]
> By this point, we'll have hopefully decided to stop with the elements theme and let go of all the problems it entails

It's cool that it isn't too late to switch theme now. I even think that it's better to switch it now than in 2025.

I don't know how this theme is chosen, but feels like it wasn't thought for these problems back then.

But anyway, i'm not against anything :) Just 2c.

**Comment by cjihrig** [comment]
@Trott ship it :shipit:

**Comment by mhdawson** [comment]
+1 from me on the proposed codenames.

**Comment by jimmont** [comment]
* **Dextrous**
* Existential
* Fractionated
* Generalized
* Hermetic
* Institutionalized
* Judicious
* Kosher
* Loquacious
* Manifest
* Nomenclature
* Occurred
* Prevalent
* Quixotic
* Redeeming
* Sincere
* Terse
* Universal
* Varicose
* Waxed
* Xenophilic
* Yoked
* Zealous

**Comment by rauschma** [comment]
@Trott Slight caveat w.r.t. Gold: could be misconstrued as saying something about the version (gold master, …). Alternative: Gallium

**Comment by Trott** [comment]
> @Trott Slight caveat w.r.t. Gold: could be misconstrued as saying something about the version (gold master, …). Alternative: Gallium

@rauschma Good point. I'll make the change.

**Comment by jasnell** [comment]
While I'm fine with the general idea, I'd prefer for 10.x to be the last of the element named lines and to pick a different theme for 12.x and on. And if we can agree to a new theme in time, I'd prefer to use a different name for 10.x also

**Comment by fivdi** [comment]
@jasnell Has your last comment something to do with the fact that it's the 1st of April?

**Comment by jasnell** [comment]
Not at all.

**Comment by shelleyp** [comment]
Why change from elements? Why go with an inconsistent naming theme?

Why introduce inconsistency for something that is, ultimately, not that important. 

And I support Gallium over gold. Gold does have unique connotations. Other than that, be bold...be daring...accept the list and move on.

**Comment by Trott** [comment]
>  I'd prefer for 10.x to be the last of the element named lines and to pick a different theme for 12.x and on. 

@jasnell Land #318 anyway because there's no guarantee that a new theme will be picked for 12.x. If it is, then great. Update that file at that time. If it isn't, then 12.x Hydrogen it is!

**Comment by jaredreich** [comment]
More for future reference:
```
J...
Krypton
Lithium
Mercury
Neon/Nickel/Nitrogen
Oxygen
Platinum/Plutonium
Q...
Radon
Silver/Silicon/Sodium
Titanium/Tungsten
Uranium
Vanadium
W...
Xenon
Yttrium
Zinc
```

**Comment by MikeRalphson** [comment]
@jaredreich in line with the characters in the seminal science-fiction series [Sapphire & Steel](https://en.wikipedia.org/wiki/Sapphire_%26_Steel#Characters) I propose including gemstones, alloys and other compounds for J, Q and W where necessary.

**Comment by armarti** [comment]
Maybe consider cool-sounding compounds that are solid at room temperature for LTS releases and liquid at room temperature for the rest?
