### ISSUE TITLE
Proposal: Switching LTS Naming Scheme to Cities of the World

### ISSUE THREAD

**Issue by jasnell** [nodejs/Release#319]
See https://docs.google.com/spreadsheets/d/1XcINhFnRLEXu-KK5fvlqlr9YuCv7iG_hH-QcO2M1_FQ/edit?usp=sharing

There are plenty of names for each starting letter. A quick script can come up with a list of names in advance per @Trott's suggestion, and we can use this as a way of celebrating Node.js' international community.

**Comment by MylesBorins** [comment]
We could do spices too 😄 

https://twitter.com/MylesBorins/status/950959290470236161

I'm +1 on anything that we know we have coverage of

**Comment by targos** [comment]
See https://github.com/nodejs/Release/pull/318
We now have codenames ready until Iron (20.x 2023). Let's revisit in five years.
