### ISSUE TITLE
Event stream for new releases and gpg keys

### ISSUE THREAD

**Issue by MylesBorins** [nodejs/Release#322]
Having an event stream that providers can subscribe to for important release information would be a++

**Comment by shaunwarman** [comment]
That would be great. I know our team would love to trigger a CI on new releases for our internal community. Are there ongoing talks about this or ways of doing this now?

**Comment by indutny** [comment]
I think it might be fun to have a service on @rauchg 's Zeit for this :grin:

**Comment by joshuapage2017** [comment]
Watch new movies for free

**Comment by lawnsea** [comment]
I have the same usecase as @shaunwarman. We maintain a set of docker images that we want to rebuild when Node releases. We're ok with it taking hours, but not days to notice that we need to rebuild.

**Comment by BridgeAR** [comment]
I put this on the release agenda to discuss how we can better progress further with this.
