### ISSUE TITLE
Update v8.x implementation of http2

### ISSUE THREAD

**Issue by MylesBorins** [nodejs/Release#324]
Hey All,

So the http2 implementation in 8.x is fairly far behind master / 9.x

Here is a rough list of missing PRs

https://gist.github.com/MylesBorins/372674e5b7f5370ccf03445d819afa90

Here is an attempt to start backporting

https://github.com/MylesBorins/node/tree/update-http2

/cc @nodejs/http2 @jasnell @addaleax

**Comment by MylesBorins** [comment]
I stopped at 5abb60933e because things got weird

**Comment by jasnell** [comment]
Define "weird"

**Comment by kjin** [comment]
I'm going to try taking a stab at this today/tomorrow

**Comment by jasnell** [comment]
@kjin ... awesome. Let me know if you get stuck. My next 2.5 weeks is pretty much all travel so it's going to be difficult for me to do much, but definitely want to help where I can.

**Comment by MylesBorins** [comment]
Thanks for the hard work @kjin
