### ISSUE TITLE
blog post for 4.x EOL?

### ISSUE THREAD

**Issue by drewfish** [nodejs/Release#326]
Hi,

I've notice that when a major version goes EOL a bunch of folks in our community don't tend to hear about it for a while. As well, I've had folks ask me "can you give me proof of the EOL, so that I can give something to my managers that we need to spend time on upgrading?"

I suspect there might be benefit to a post in https://nodejs.org/en/blog/ announcing the EOL. It can be very simple, a "4.x is no longer supported" kind of thing.

If it's helpful I can attempt an initial draft.

**Comment by MylesBorins** [comment]
Already being worked on 😁

**Comment by richardlau** [comment]
I think this can be closed? There's a banner across the middle of https://nodejs.org/en/ linking to https://medium.com/the-node-js-collection/april-2018-release-updates-from-the-node-js-project-71687e1f7742.
