### ISSUE TITLE
[Tracking] Node.js 11.0.0 Release

### ISSUE THREAD

**Issue by jasnell** [nodejs/Release#328]
Might as well get this kicked off as early as possible given that 10.0.0 is going out the door tomorrow.

I will do the 11.0.0 release in October. 

I'm proposing **Tuesday, October 23rd** as the target release date, with **October 1st** as a target soft semver-major cut off date, and **October 15th** as a target hard semver-major cut off date ("soft" == this is what folks should be targeting for, "hard" == absolutely no semver-major's unless they're critical for the release).

This gives us one week to slip the release if absolutely necessary.

**Comment by mhdawson** [comment]
+1

**Comment by targos** [comment]
+1. Chromium 70 is scheduled for Oct 16th so timing is perfect

**Comment by MAPESO** [comment]
EsModule 🎉

**Comment by targos** [comment]
@jasnell Yes. That will be V8 7.0

**Comment by loretoparisi** [comment]
@targos I thought we were at V8 release v6.6...

**Comment by jasnell** [comment]
Right now in 10.0.0 we are. This thread is discussing Node.js 11.0.0, however. We'll be at V87 by October.

**Comment by xnox** [comment]
And this release will require OpenSSL 1.1.1 with TLS1.3 right? Given that it is out.

**Comment by richardlau** [comment]
> 
> 
> And this release will require OpenSSL 1.1.1 with TLS1.3 right? Given that it is out.

Current state of OpenSSL 1.1.1 integration with Node.js is in https://github.com/nodejs/node/issues/18770. It sounds like there are issues on the Node.js side supporting TLS1.3.
