### ISSUE TITLE
Bringing back regular meetings

### ISSUE THREAD

**Issue by MylesBorins** [nodejs/Release#333]
I think that moving to no longer having meetings was a good idea at the time, but a few things have shifted since then and it feels like there is a need for some sort of regular cadence sync.

Would people be open to spinning up a monthly meeting for the WG?

**Comment by mhdawson** [comment]
+1

**Comment by mhdawson** [comment]
Bump @nodejs/release

**Comment by MylesBorins** [comment]
ping @nodejs/release

**Comment by mhdawson** [comment]
@MylesBorins should we just schedule a meeting to get started?

**Comment by richardlau** [comment]
Another PR with lts-agenda tag: https://github.com/nodejs/node/pull/22633

**Comment by mhdawson** [comment]
@MylesBorins are you still in favor or restarting regular meetings?  @BethGriggs if @MylesBorins answers yes would you be able to volunteer to help choose a time and setup the meeting (I can help with adding to Node.js calendar etc.)

**Comment by MylesBorins** [comment]
I am very +1 on starting this up again

**Comment by targos** [comment]
I am +1 as well

**Comment by BethGriggs** [comment]
Initially thinking of meeting every two weeks? I set up a doodle to start to try and find a regular day/time for us to meet - https://doodle.com/poll/95b6f5zdgxzy75n9

@nodejs/release

**Comment by mhdawson** [comment]
@nodejs/release looks like we could use more people to fill in the doodle.

**Comment by targos** [comment]
Ping @nodejs/release

**Comment by BridgeAR** [comment]
I am also +1 for meetings.

The doodle is outdated, so I did not fill it out. I believe it's best to open up a new and smaller one which contains exactly one week which we use as reference for all weeks?

**Comment by MylesBorins** [comment]
I have alternating bi weekly meetings. So imho it does make sense to have
two weeks on the doodle.

**Comment by MylesBorins** [comment]
Alternatively, does anyone object to 11 ET on Thursdays?

(Figured if we can all agree on that time perhaps we don't need to do a
doodle)

**Comment by targos** [comment]
11 ET is OK for me, if we start in January

**Comment by rvagg** [comment]
3am for me, I'm not quite that excited, so it's a no for me

**Comment by BridgeAR** [comment]
11 ET on Thursdays would be fine for me. But since that does not work for @rvagg maybe we could move it either three hours earlier or three hours later (while I could not participate well three hours later).

**Comment by rvagg** [comment]
don't bother, ET + Europe makes it tough to include APAC

**Comment by MylesBorins** [comment]
Based on the above I'd like to propose we have a first meeting on the 17th and meet biweekly afterwards

**Comment by MylesBorins** [comment]
Based on the above I'd like to propose we have a first meeting on the 17th and meet biweekly afterwards

**Comment by MylesBorins** [comment]
I've added it to the Calendar and the Zoom

**Comment by MylesBorins** [comment]
They are back!
