### ISSUE TITLE
Current failures on 10.x to dig into

### ISSUE THREAD

**Issue by MylesBorins** [nodejs/Release#340]
* yeoman-generator
* bson
* node-weak
* radium

**Comment by richardlau** [comment]
Is the node-weak failure the same as reported in https://github.com/nodejs/citgm/issues/558?

(And should this issue have been opened over in the citgm repo?)

**Comment by BridgeAR** [comment]
The `yeoman-generator` failures got fixed by https://github.com/yeoman/generator/commit/b4f1bfcc5466e3aed004cff8c86e5bf5306195e6.

**Comment by BridgeAR** [comment]
I guess the radium failures are also resolved. See https://github.com/FormidableLabs/radium/issues/990. If not, I am going to continue to investigate that.

**Comment by BridgeAR** [comment]
I also already opened PRs for `bson` but the maintainers did not yet respond.
