### ISSUE TITLE
PR for 8.x semver minor release has been opened

### ISSUE THREAD

**Issue by MylesBorins** [nodejs/Release#350]
https://github.com/nodejs/node/pull/21593

from PR

> trying a bit of a different approach here.
> 
> This is a release based on all the commits that are currently on v8.x-staging
> 
> There is a backlog of around 1200 commits that have not been audited for this release 
> 
> https://gist.github.com/MylesBorins/078554dfc521fe945a6f45324206ec0e
> 
> This is a semver-minor release... as such we are going to want to bake longer with an r.c. process.
> 
> If you know of specific 8.x bugs that we should fix, any commits / prs from the above list, or features you want to be considered for this minor please comment on this issue and the @nodejs/lts and @nodejs/backporters team will review and land as appropriate.
> 
> If individuals don't see anything pressing for 8.x we'll ship it with what is in this PR. Assume that all currently open backport PRs are going to be triages, if they land this PR will be updated accordingly.

Trying a reactive rather than proactive approach for this release. Please chime in if there are things we need to land on 8.x

**Comment by MylesBorins** [comment]
@nodejs/backporters please push any changes that qualify for LTS directly to the staging branch

**Comment by richardlau** [comment]
Closing as the referenced v8.12.0 PR has been merged.
