### ISSUE TITLE
Ubuntu and Debian Package Maintainence

### ISSUE THREAD

**Issue by huanghe2015** [nodejs/Release#356]
I have a little question:who or which team is working for package on Debian and Ubuntu?Anyone here can give an answer?

**Comment by refack** [comment]
AFAIK @chrislea in https://github.com/nodesource/distributions
But the official Debian and Ubuntu releases pack their own.

**Comment by chrislea** [comment]
Yes, it's mostly me.

**Comment by huanghe2015** [comment]
I just want to know what is happening in official apt respority,but you give an answer from two sides,because the version in Ubuntu and Debian apt package is too old.Thanks @refack
