### ISSUE TITLE
Release and Backporting Roatations

### ISSUE THREAD

**Issue by MylesBorins** [nodejs/Release#357]
Would anyone be up for this? Perhaps we can open up a schedule a month in advance and let people sign up to take responsibility for 

a) a specific release
b) auditing / backporting during a certain period of time.

Thoughts?

**Comment by targos** [comment]
Yes please!

**Comment by BethGriggs** [comment]
Would there be any time to discuss or get things started with this at the collaborator summit?

**Comment by MylesBorins** [comment]
First pass at this proposed in https://github.com/nodejs/Release/issues/390
