### ISSUE TITLE
Discussion of Release and LTS at collaborator summit

### ISSUE THREAD

**Issue by MylesBorins** [nodejs/Release#358]
What should we talk about?

**Comment by targos** [comment]
I would like to talk again about backporting. Even on the Current release line, where conflicts are usually easy to fix, it is very difficult to get backports done. We need to come up with a clear strategy around backports and I think tooling can be developed to ease the process.

**Comment by MylesBorins** [comment]
@targos would this be a seperate session from Release / LTS?

I think we may benefit from designing policy for all lines where the only difference is "what lands" not how it is managed.

**Comment by richardlau** [comment]
I won't be at the summit, but perhaps those that are could get together with the n-api team and discuss what how our LTS policy might be altered to accomodate n-api changes (see https://github.com/nodejs/node/pull/22633#issuecomment-420450955).

**Comment by joyeecheung** [comment]
@targos @MylesBorins We have a session about automation. Maybe if move the release session forward before that one, we can discuss about automation of releases/backports at the automation session?

**Comment by ErisDS** [comment]
I think there needs to be a discussion around using available funding to lock down the release process into something more formal and managed.

The fact that discussions [like this](https://github.com/nodejs/Release/issues/361) happen after the stated release cause problems for software that depends on the LTS process - like Ghost - as well as reinforcing the "toy framework" reputation, which is a genuine marketing problem.

There's no way to sanely schedule work around the Node.js LTS process at the moment, and it bites us almost every time. 

It feels a lot like the release & backporting processes are not given the attention or resources they deserve.
