### ISSUE TITLE
Defining a word for all current releases

### ISSUE THREAD

**Issue by bnb** [nodejs/Release#359]
In discussing with a friend, I realized that we don't have an actual word for the corpus of releases that are currently being worked on / not EOL.

Here's a sentence as an example:

> Node.js versions 6, 8, 10 are the only [word] releases currently. Soon Node.js version 11 will be be too.

Both of us instinctively reached for "Active" but that's currently a word used as a part of LTS terminology.

> Node.js versions 6, 8, 10 are the only active releases currently. Soon Node.js version 11 will be be too.

As far as I know, we don't have a word that defines this. I think it's a useful word to define, as I've reached for some kind of word like this several times.

Some possibilities:
* Circulated
* Supported
* Operating
* Effective

**Comment by vsemozhetbyt** [comment]
"Supported" seems to be the most exact and substantial word? Others seem a bit evaluative and fuzzy.

**Comment by MylesBorins** [comment]
I always say maintained

**Comment by targos** [comment]
I say supported.

**Comment by BridgeAR** [comment]
Both, supported and maintained sounds good.

**Comment by joyeecheung** [comment]
I'd go for supported instead of maintained to avoid confusion about "maintenance mode"

**Comment by mhdawson** [comment]
I prefer supported.

**Comment by DrEVILish** [comment]
Current Releases
Maintained Releases

**Comment by bnb** [comment]
@joyeecheung valid point, agreed!

@DrEVILish extending @joyeecheung's point, we have the "Current" release line which is the release line that's in active development. Current releases (and maintained releases) could theoretically get easily confused.

Seems like `Supported` is the only word that doesn't collide with another term and has... support? 😁

**Comment by targos** [comment]
@bnb what's the next step? Would you like to document this somewhere?

**Comment by bnb** [comment]
@targos yes, documenting that somewhere would be ideal. It would be awesome if we could have a `Glossary` section of the `README.md` that included all the terms we use (including this) 🤔

**Comment by rvagg** [comment]
I say "actively supported release lines" whenever I do security releases that need to cover them all. I think also if you're going to clarify this terminology you should be clear about "releases" and "release lines" too cause that gets messy.

**Comment by BridgeAR** [comment]
I added this to the release agenda to decide on a specific wording that we then use consistently.

**Comment by Trott** [comment]
"actively-supported release lines" seems good, although it raises the question what the "inactively-supported" or "passively-supported" release lines are. Does it mean "maintenance" release lines are covered or not?

For that reason, I think my preference is for "supported release lines" or "currently-supported release lines" as that's what the user cares about--that a particular release line is supported.

**Comment by mhdawson** [comment]
We settled on "maintained" here: https://github.com/nodejs/package-maintenance/blob/master/docs/drafts/PACKAGE-SUPPORT.md

So my preference would be to us `maintained`

The definition there was "Node.js versions which are not EOL"

**Comment by Trott** [comment]
> We settled on "maintained" here: https://github.com/nodejs/package-maintenance/blob/master/docs/drafts/PACKAGE-SUPPORT.md
> 
> So my preference would be to us `maintained`
> 
> The definition there was "Node.js versions which are not EOL"

Maybe, but isn't that for packages rather than package **versions**?. It is definitely idiomatic to say that a package (or other piece of software) is _maintained_ rather than _supported_. IMO it is less idiomatic for a runtime **version** (or an OS **version** or package **version**) to be described as "maintained" rather than "supported".

I also think "maintained" implies less of a commitment to overall quality than "supported". That may be a feature rather than a bug, depending on your perspective. But "maintained' does make it sound like "we're keeping it running but not much more".

I won't say people don't ever use that terminology differently (because they totally do). And I won't argue against "maintained" strenuously. It's adequate for this situation. But I think "supported" is more idiomatic and a little bit better.

One last bit of evidence for the idiomatic nature of "supported". I typed "Versions of Node.js that are currently" into Google to see what the autocomplete would be. Sure enough: "supported". Same with "Windows" and "CentOS" substituted for "Node.js".

**Comment by BethGriggs** [comment]
I think I prefer "supported" to "maintained" - partially due to the overlap with our terminology "maintenance".  I also think "supported" works well with our use of "long-term support"- where LTS versions are a subset of the "supported" versions.

**Comment by mhdawson** [comment]
We discussed in the package-maintenance meeting today and I've submitted a PR to change `maintained` to `supported` based on this feedback.

**Comment by mhdawson** [comment]
PR also clarifies a bit what 'all' means as it's intended to cover support all versions regardless of EOL status.

**Comment by mhdawson** [comment]
@BethGriggs happy to volunteer, will look at it next week. @dominykas I agree will look to see how I can fit the list in.

**Comment by mhdawson** [comment]
Sorry for the delay, still have this on my list.

**Comment by mhdawson** [comment]
I went through the existing doc a while back to find if there were any references in ndoejs/node  and nodejs/release that needed to be updated and did not find any.  

I guess the next step is to create a new section with the terminology.

**Comment by mhdawson** [comment]
For reference this is the list in the PACKAGE-SUPPORT.md section based on the feedback from this discussion: https://github.com/nodejs/package-maintenance/blob/master/docs/drafts/PACKAGE-SUPPORT.md#support-target

**Comment by tw875768** [comment]
reply@reply.github.com

電子郵件為t0919170301@yahoo.com.tw的用戶已發送邀請給您，邀請您加入MEGA。

""

點擊下方連結，與t0919170301@yahoo.com.tw一同使用MEGA：

https://mega.nz/#newsignupcmVwbHkrYWt6NHBwd3BnNW0zbnJucXhvcXE3YWYzcmQyNGJldmJuaGhiazdwNW95QHJlcGx5LmdpdGh1Yi5jb20F3mSVrKqFDw

獻上最誠摯的祝福，
— MEGA團隊 敬上

**Comment by BethGriggs** [comment]
We've updated our documentation in the README to state that we will use the word 'supported':
> The term 'supported release lines' will be used to refer to all release lines that are not End-of-Life.

Package Maintenance are also adopting this terminology.
