### ISSUE TITLE
out of sync with GitHub teams

### ISSUE THREAD

**Issue by Trott** [nodejs/Release#360]
The list of LTS folks here is way out of synch with @nodejs/lts. I'm not sure if the README here needs to be updated, or the team, or both, or they're not the same thing despite having the same name, or what. But it's confusing. Please help!  :-D

**Comment by richardlau** [comment]
Synced by https://github.com/nodejs/Release/commit/19985fe7c16c764805bed84ea4901488bec35cbf.
