### ISSUE TITLE
Incorrect start date in schedule.json

### ISSUE THREAD

**Issue by bnb** [nodejs/Release#361]
The `schedule.json` file asserts that Node.js v10 is LTS today. As far as I know (?), this isn’t the case.

Historically it seems we trend more toward the end of the month. If truly incorrect, would it be acceptable/more accurate to update it to the 31st and adjust down if needed? Happy to create a PR if the answer is yes.

For what it’s worth, I discovered this last night while working on [node-release-lines](https://GitHub.com/nw/node-release-lines), which uses the data from `schedule.json` rather heavily.

**Comment by mhdawson** [comment]
@jasnell, @MylesBorins can you two comment if we have a specific date to update it to yet?
