### ISSUE TITLE
Doing another Semver Minor on 8.x

### ISSUE THREAD

**Issue by MylesBorins** [nodejs/Release#364]
Hey All,

We have an open PR to get the http2 implementation up to date on 8.x... this PR does include semver-minor changes to http. I'd like to propose we do another semver-minor release of the 8.x line

https://github.com/nodejs/node/pull/22850

**Comment by BridgeAR** [comment]
:+1:

**Comment by mhdawson** [comment]
+1 from me.  It seems important for http2 adoption.

**Comment by BridgeAR** [comment]
Is there a specific part that we should likely also backport? I do have some time that I could invest into that at the moment.

**Comment by kjin** [comment]
Current status -- the PR should be complete for backportable changes to http2 up to Node 10.9. I'm currently working through additional commits up to 10.11.

It shouldn't be too hard to remove the semver-minor change to http in this PR... if that helps it land.

**Comment by MylesBorins** [comment]
We have approval for another minor. Let's get everything in that makes
sense!

**Comment by kjin** [comment]
Just updated nodejs/node#22850
