### ISSUE TITLE
Coordinate major releases with node-pre-gyp

### ISSUE THREAD

**Issue by ofrobots** [nodejs/Release#384]
We released Node.js 11.0.0 but it seems that `node-pre-gyp` still doesn't [support it](https://github.com/mapbox/node-pre-gyp/issues/421). This means that users trying to run their applications - that depend on native modules - may not work out of the box against Node 11.

It would be great to coordinate with `node-pre-gyp` to make sure we are offering the best user experience for Node.js users.

**Comment by refack** [comment]
I'd be happy to help from the `node-gyp` side if needed.

**Comment by mhdawson** [comment]
There are probably other tools we should consider as well.  Makes sense to me to build a list that we co-ordinate with.

**Comment by nicolasnoble** [comment]
cc @springmeyer.

**Comment by springmeyer** [comment]
Thanks for ticketing this out and for the cc. I've moved jobs at @mapbox and now have very little time to maintain node-pre-gyp. So, I would love to do whatever is possible to make sure my absence does not cause hardship for the node community. @nicolasnoble thank you so much for https://github.com/mapbox/node-pre-gyp/pull/422 and https://github.com/mapbox/node-pre-gyp/pull/428. Would you be interested in getting commit and publish access to node-pre-gyp to run these fixes out into the wild?

**Comment by springmeyer** [comment]
> perhaps node-pre-gyp could be reworked to pick up the data from https://nodejs.org/dist/index.json instead of having to be manually updated

👍 Yes, this would be a good improvement and one I've thought of but not had the time to invest in. Maybe @nicolasnoble could pick that up? 

I should mention however that if you don't need or use the `--target=11.0.0` flag to node-pre-gyp then it will support new major versions of node without needing to be updated. It is only when you are needing to target different version, via the `--target=` flag, that the crosswalk is needed.

**Comment by nicolasnoble** [comment]
We actually talked about this feature with @murgatroid99, where we just issue a request in case the data isn't found in the local database. This way the software still mostly works offline, but also has an online fallback.

**Comment by nicolasnoble** [comment]
No, we just need some time to achieve it.

**Comment by rvagg** [comment]
FYI I'm working on a `NODE_MODULE_VERSION` registry that may be helpful when combined with index.json for node-pre-gyp and similar tools. See #24114. I need to do some more refinements of the idea but hope to have this in `master` soon.

**Comment by BridgeAR** [comment]
Closing as oudated.

The latest node-gyp release supports v12 even though there was a test failure at the time of release. We track all modules that fail major releases by now and try to get them ready up until the actual release, so there does not seem anything actionable left here. Please feel free to reopen of I'm wrong.

**Comment by nicolasnoble** [comment]
@bridgear: you are mixing up node-gyp and node-pre-gyp.

**Comment by BridgeAR** [comment]
@nicolasnoble thanks. The rest still seems valid though and I don't see anything actionable.
