### ISSUE TITLE
Why 4.x status is still Maintenance LTS?

### ISSUE THREAD

**Issue by mputilin** [nodejs/Release#385]
Accoring to Release schedule (https://github.com/nodejs/Release/blob/643af71ee8365efbdccaa134690425ea05931279/README.md#release-schedule) NodeJS 4.3 should be `End-of-Life`, but still `Maintenance LTS`. AWS Lambda also sill supports it, but shouldn't, according to Runtime Support Policy (https://docs.aws.amazon.com/lambda/latest/dg/runtime-support-policy.html). Why?

**Comment by richardlau** [comment]
That's an older version of this repository's README.md. The current https://github.com/nodejs/Release/blob/20ff702661d11d5ceeeb495764e575ba13e5fc17/README.md#release-schedule has Node.js 4 in the End-Of-Life section.
