### ISSUE TITLE
Upcoming LTS release plans?

### ISSUE THREAD

**Issue by rvagg** [nodejs/Release#389]
@MylesBorins I know you used to put together proposed dates for releases but I can't find a recent one. Is this not a thing you're doing anymore? I'd be happy to work on one of them, maybe a 10.x bump since @BethGriggs is working on the 8.x, but I need to figure out where to slot in.

**Comment by MylesBorins** [comment]
@rvagg I've been slowly stepping back from release duties and attempting to mentor new folks to take on responsibilities. I was thinking that @codebytere might want to prep the next 10.x release.

Overall we might do best by coming up with a release schedule for the next couple months and get people to volunteer for the specific releases... thoughts?

**Comment by codebytere** [comment]
I'd be interested in taking this on!

**Comment by MylesBorins** [comment]
@rvagg I've opened https://github.com/nodejs/Release/issues/390 with proposed dates for releases until the end of Q1
