### ISSUE TITLE
Sync with Debian releases

### ISSUE THREAD

**Issue by lucab** [nodejs/Release#39]
Just FYI, this is the current proposed timeline for next Debian stable:
http://lists.alioth.debian.org/pipermail/pkg-javascript-devel/2015-September/011202.html

Due to tight timings (and unless other changes of plans), we will probably target 4.4.1.

**Comment by thefourtheye** [comment]
@lucab FYI, 4.4.1 is just an example. Please check #40

**Comment by kapouer** [comment]
@lucab indeed, now i'm maintaining 4.2.x on our packaging master-4.2, uploaded to unstable/testing and >= 5 on master, uploaded to experimental. I think the reasonnable choice for next debian release is to keep nodejs 4.2 - that's open to discussion. The good new is that version 4.2 is available on all official debian ports.

**Comment by TheAlphaNerd** [comment]
@lucab would you be up for having a discussion about Node LTS and improving the situation on debian / apt?

**Comment by kapouer** [comment]
Hello,
currently either nodejs 4 or 6 will be in the next debian release.

**Comment by BridgeAR** [comment]
Closing as outdated.
