### ISSUE TITLE
Plan for Node.js 11 Current releases

### ISSUE THREAD

**Issue by targos** [nodejs/Release#397]
Week | Approximative date | Release | Releaser
------------ | :-------: | ------ | ---- 
2018 - 49 | 2018-12-07 | v11.4.0 |@BridgeAR
2018 - 51 |   2018-12-18  | v11.5.0 | @BethGriggs
2018 - 52 |   2018-12-26  | v11.6.0 | @MylesBorins
2019 - 03 | 2019-01-18 | v11.7.0 | @BridgeAR 
2019 - 04 | 2019-01-24 | v11.8.0 | @MylesBorins 
2019 - 05 | 2019-01-30 | v11.9.0 | @targos
2019 - 07 | 2019-02-14 | v11.10.0 | @targos
2019 - 09 | 2019-02-28 | v11.10.1 | @rvagg 
2019 - 10 | 2019-03-05| v11.11.0 | @BridgeAR 
2019 - 11 | 2019-03-14| v11.12.0 | @BridgeAR 
2019 - 13 | 2019-03-28 | v11.13.0 | @targos 
2019 - 15 | 2019-04-11 | v11.14.0 | @BethGriggs 
2019 - 16 | 2019-04-30 | v11.x.y | @codebytere 

/cc @nodejs/releasers 

I propose this plan for the next Node.js 11 Current releases, until the week before Node.js 12 is supposed to be released.
It's a simple rule: one release every two weeks, with an exception of three weeks during end of year holidays. I always put Tuesday as approximative date but the release could happen any day of the week, depending on releaser's availability.
We already have a [volunteer](https://github.com/nodejs/Release/issues/395) to do the next release. @BethGriggs is week 51 OK for you?

**Comment by targos** [comment]
@MylesBorins  OK, I changed the dates... But those should not be considered fixed. I personally have more time to do releases on Wednesdays or Thursdays.

**Comment by BridgeAR** [comment]
I suggest to use the dates as recommendation and let the releasing person be flexible with the actual day while trying to prevent releases on Fridays.

I am fine to volunteer for e.g., each even 11 release. That way I know when to take some time for it.

**Comment by MylesBorins** [comment]
@BridgeAR I generally push for releases on Tuesday for 2 reasons

1. Give external teams appropriate time during the week to adopt the new release
2. Give us a large buffer in case of release problems. We have had releases that broke stuff, it wasn't pointed out until wednesday / thursday, we then in turn still had time to respond and get a new release out during the week without requiring a firedrill during the weekend.

> I personally have more time to do releases on Wednesdays or Thursdays.

While I totally understand the timing issue here, my hope would be that the majority of release work has been done in advance, a least multiple days in advance. So, for example, a release can be prepared and proposed on a Thursday so that testing can begin. This was the only work to be done on tuesday is promotion... which "shouldn't" take more than an hour.

**Comment by targos** [comment]
I volunteer for 2019-01-22

**Comment by targos** [comment]
Ping @nodejs/releasers do we have a volunteer for this week? It would be nice to have a patch release with npm 6.5.0 stable.

**Comment by BridgeAR** [comment]
I'll prepare the release tomorrow.

**Comment by ljharb** [comment]
how goes today's patch release? :-D

**Comment by BridgeAR** [comment]
@ljharb currently there are lots of conflicts between master and 11.x and I did not get to resolve all of these and I have to get some sleep but I'll try to finish it tomorrow.

It's likely that we should backport a couple of older commits first though. Otherwise each release is going to become more complicated.

**Comment by ljharb** [comment]
I'm most interested in seeing https://github.com/nodejs/node/pull/25234 make it into an 11.6 patch release; as long as it doesn't get delayed to an 11.7, i'm more than happy to wait til you have time :-) Thanks!

**Comment by MylesBorins** [comment]
@ljharb that one is already on staging 🎉

**Comment by MylesBorins** [comment]
@BridgeAR are you still able to do this?

**Comment by BridgeAR** [comment]
I opened a release proposal for 11.7.0 (should this be a semver-patch release? If so, it'll we a tiny release as we had quite some issues backporting things and it would require more time to resolve further conflicts. Right now we are back on track with the conflicts and have only few backport requests to 11.x).

https://github.com/nodejs/node/pull/25537

**Comment by ljharb** [comment]
My hope is for a patch release.

**Comment by MylesBorins** [comment]
@ljharb why a patch release? We have brotli and a number of semver-minor commits

I'm personally -1 on doing a patch release, it isn't the process we've done in the past for current and will significantly complicate landing a bunch of stuff.

**Comment by ljharb** [comment]
I mean obv if there’s additions it should be a minor; it’s just disappointing since a patch release with the npm fix should have been able to go out before landing those.

**Comment by BridgeAR** [comment]
@targos since the release took somewhat longer due to backporting a lot of things that caused conflicts: it's probably best to move the release after 11.7.0 by one week or skip the release.

**Comment by targos** [comment]
OK, I shifted everything by one week. In the future, I think it will be better to stick with the schedule and avoid blocking on pending backports. Current releases happen often enough that we can postpone backports to the next one.

**Comment by targos** [comment]
Can anyone prepare a release for this week?

**Comment by targos** [comment]
I found some time to do it today: https://github.com/nodejs/node/pull/26098

**Comment by BridgeAR** [comment]
Should we release the next current (v11) version next week or the week after? It was originally planned to release it this week but it was postponed due to the security release.

I personally suggest to release it on next Tuesday but I do not know how everyone else feels about it.

**Comment by targos** [comment]
I have no objection to doing releases two weeks in a row (if there are enough commits to warrant it).

**Comment by MylesBorins** [comment]
Next week sounds good to me. In general a weekly cadence for Current is
absolutely fine I'd there are enough commits

**Comment by BridgeAR** [comment]
I updated the staging branch today to get a release proposal together but that took quite a bit due to lots of conflicts and bisecting in-between.

I would like to release a new version tomorrow if no one is against it, since a fix for jest just landed. Any opinions @nodejs/releasers?

**Comment by sam-github** [comment]
FYI, I linked to this from https://github.com/nodejs/Release/wiki

**Comment by targos** [comment]
@codebytere During yesterday's meeting, we decided to move the last active release of v11.x to 2019-04-16 so it doesn't happen the same week as 12.0.0. Is it still OK for you?

**Comment by BethGriggs** [comment]
Currently prepping today's release, aim to open the PR later this evening and have it go out tomorrow

**Comment by targos** [comment]
@codebytere Do you have time to prepare this week's release? If not I can do it.

**Comment by BethGriggs** [comment]
For now, I've based the v12.0.0 release changelog on the diff between v11.14.0 and v12.x. Some PRs have landed on 11.x-staging that would be good to ship (even if that happens to be after v12.x goes out).

**Comment by BridgeAR** [comment]
@BethGriggs just for understanding since I somewhat read both: is it only about the changelog or are commits missing that landed on the 11 branch?

**Comment by BethGriggs** [comment]
Ah sorry, in regards to Node 12 it is just the changelog. As far as I know, all new commits currently on v11.x-staging are manual v11.x backports.

**Comment by BethGriggs** [comment]
The final _planned_ release is next week. I'm thinking that if there is a demand or a request for some specific fixes/backports we could do another release before v11.x goes End-of-Life on 2019-06-01 to tie up any loose ends.

**Comment by targos** [comment]
+1
