### ISSUE TITLE
special release for all release lines to fix regressions from last security release

### ISSUE THREAD

**Issue by MylesBorins** [nodejs/Release#401]
The last security release included a regression in 6 / 8 / 10 in HTTP binary response body. There was also no CLI option to change the maximum header size in 6 / 8 / 10 / 11.

I've proposed releases for all release lines to account for this, planning to push them out next Wednesday the 26th. They are Semver-Minor and include no other commits (aside from 10 that required a single commit to fix a regression in test suite)

11: https://github.com/nodejs/node/pull/25175
10: https://github.com/nodejs/node/pull/25176
8: https://github.com/nodejs/node/pull/25177
6: https://github.com/nodejs/node/pull/25178

If anyone has concerns please lmk

**Comment by mcollina** [comment]
sgtm

**Comment by mhdawson** [comment]
Closing since releases are out.
