### ISSUE TITLE
[Tracking] Additional semver minor to 8.x during maintenance

### ISSUE THREAD

**Issue by MylesBorins** [nodejs/Release#405]
There are a couple different features that we might want to ship before 8.x goes EOL

* [tsfn support for n-api](https://github.com/nodejs/node/pull/25002)
* various crypto features (/cc @tniessen)
* [namespaces](https://github.com/nodejs/node/pull/21551)

As such I think it does make sense for us to do one more Semver-Minor relase of the 8.x release line.

Thoughts?

**Comment by mhdawson** [comment]
@MylesBorins I assume you mean 8.x in your original post as opposed to 10.x.

**Comment by MylesBorins** [comment]
@mhdawson fixed, thanks

**Comment by richardlau** [comment]
I'd like to get https://github.com/nodejs/node/pull/25447 in if we do another 8.x release. Let me know if it needs a manual backport.

**Comment by MylesBorins** [comment]
@richardlau can you please backport?

**Comment by richardlau** [comment]
> 
> 
> @richardlau can you please backport?

Done! https://github.com/nodejs/node/pull/25521

**Comment by mhdawson** [comment]
@MylesBorins what timing are you thinking for the release.  Just want to make sure we sync with @gabrielschulhof to see if there is any chance it can also include the PR to make tsfn non-experiemental as wel as opposed that coming later.

**Comment by MylesBorins** [comment]
Removing label as we had consensus to do this release.

We should keep this open for tracking

**Comment by ljharb** [comment]
It would be *really* nice to backport the `instanceof Array` fixes from https://github.com/nodejs/node/pull/20250/files#diff-286202fdbdd74ede6f5f5334b6176b5cL320 into 8 (and even 6). It breaks jest, and cross-realm use cases, and I can't conceive of how the fix would cause any trouble.

**Comment by MylesBorins** [comment]
@nodejs/collaborators quick ping. Is there anything specific you would like to see on 8.x?

**Comment by BridgeAR** [comment]
I would like to include https://github.com/nodejs/node/pull/26599.

**Comment by lpinca** [comment]
https://github.com/nodejs/node/pull/25938

**Comment by Trott** [comment]
From https://github.com/nodejs/Release#release-plan:

> Once a major version enters LTS coverage, new features (semver-minor) may only be landed with consent of the Release working group. 

And...

> Changes in an LTS-covered major version are limited to:
> 
> 1. Bug fixes;
> 2. Security updates;
> 3. Non-semver-major npm updates;
> 4. Relevant documentation updates;
> 5. Certain performance improvements where the risk of breaking existing
   applications is minimal;
> 6. Changes that introduce large amount of code churn where the risk of breaking
   existing applications is low and where the change in question may
   significantly ease the ability to backport future changes due to the
   reduction in diff noise.

This would seem to preclude things like namespaces or new CLI flags.

If the material quoted above is accurate, then I assume Release WG will reject adding `--unhandled-rejections` to 8.x (or for that matter 10.x).

If the material quoted above is not accurate, then can we please update it? (Pro-tip: When feasible, removing wrong text is easier than trying to correct text that isn't necessary.)

**Comment by Trott** [comment]
(For the record, I'm fine one way or the other with `--unhandled-rejections` in LTS. I just want the quoted document to be correct.)

**Comment by MylesBorins** [comment]
@Trott we likely need to update the language in the second area. We've mostly run with "we land whatever we agree as a group to land". That list is more for pointing people at when we agree not to land something...

We have landed new flags in prior LTS minors afaik

**Comment by gabrielschulhof** [comment]
https://github.com/nodejs/node/pull/25648 is semver-minor and needed for N-API and https://github.com/nodejs/node/pull/26060 is the backport of a N-API bug fix.

**Comment by Trott** [comment]
@MylesBorins This paragraph probably also needs to go, since here we are talking about landing all sorts of non-critical stuff in a maintenance release.

> Once a release moves into Maintenance mode, only ***critical*** bugs,
***critical*** security fixes, documentation updates, and updates to ensure
consistency and usability of the N-API across LTS releases will be permitted.
Unless a change is ***urgent*** it will be planned into a release once per
quarter. Such releases will only be made when necessary.

**Comment by MylesBorins** [comment]
@Trott we need to discuss this as a team and figure out what we want to do here.

That paragraph is important and has generally been a guiding start... keep in mind that 8.x had a shortened maintenance release cycle... we have not decided on exactly which PRs we are going to land. It initially started due to the need for specific n-api stuff... and we have documentation somewhere (unsure where) about n-api updates themselves being different.

We might want to scale back how ambitious we are going to be about this maintenance LTS release, but we still haven't had a WG meeting to review and discuss.  Alternatively it might be time to sit down and rethink how we are doing LTS based on past experience and the new folks working on it.

**Comment by mcollina** [comment]
I think @BethGriggs included https://github.com/nodejs/node/pull/25351 already.

**Comment by mhdawson** [comment]
This 

```
Once a release moves into Maintenance mode, only critical bugs, critical security fixes, documentation updates, and updates to ensure consistency and usability of the N-API across LTS releases will be permitted. Unless a change is urgent it will be planned into a release once per quarter. Such releases will only be made when necessary.
```
Is the text related to N-API and is 2 paragraphs below the text @Trott referenced in the README.md

**Comment by MylesBorins** [comment]
PR is open

https://github.com/nodejs/node/pull/26933

Anything missing?

**Comment by mhdawson** [comment]
@gabrielschulhof can you take a quick look to verify the list as well?

**Comment by BethGriggs** [comment]
v8.16.0 was released https://github.com/nodejs/node/pull/26933
