### ISSUE TITLE
Final 6.x release before EOL? [Discussion]

### ISSUE THREAD

**Issue by BethGriggs** [nodejs/Release#414]
There are currently 8 commits on [v6.x-staging](https://github.com/nodejs/node/commits/v6.x-staging), and [2 open backport PRs](https://github.com/nodejs/node/pulls?q=is%3Aopen+is%3Apr+label%3Av6.x) targetted at Node 6. 

I think we should discuss whether we should do a final release including all or a subset of the commits/PRs.

**Comment by richardlau** [comment]
@ljharb also [asked in IRC](http://logs.libuv.org/node-dev/2019-02-06) and https://github.com/nodejs/Release/issues/405#issuecomment-461164134 whether the `instanceof Array` fixes from https://github.com/nodejs/node/pull/20250/files#diff-286202fdbdd74ede6f5f5334b6176b5cL320 could be backported.

**Comment by richardlau** [comment]
These are the commits on [v6.x-staging](https://github.com/nodejs/node/commits/v6.x-staging) that are not in a release:
https://github.com/nodejs/node/commit/bc916e971ec90189c3c04985316a8c55f56f4585 tools,gyp: fix regex for version matching
https://github.com/nodejs/node/commit/16661e6636f00b70d5c5bed7fc027018a8d74b6e build: fix configure script for double-digits
https://github.com/nodejs/node/commit/33cd51e545a01b3dd36c65f0a77b4e627846692a tools: update tooling to work with new macOS CLI …
https://github.com/nodejs/node/commit/74d3f0bd780ec470b170b9e6943adc09e8eb1fb8 src: fix bootstrap_node on bsd
https://github.com/nodejs/node/commit/3c4949a6bb77bdae4ca5c2971ad8e61e381931fd doc: document that addMembership must be called once in a cluster
https://github.com/nodejs/node/commit/29748cb13f2a94a087e3a6f9a26360a0997749ac doc: simplify CODE_OF_CONDUCT.md
https://github.com/nodejs/node/commit/97d8bc854164604b8f46ce1ef3370d9335dbdbd7 build: only check REPLACEME & DEP...X for releases
https://github.com/nodejs/node/commit/e2faf8c82aa2fd8b4d86c673c39afecd4179073e test: fix test-repl-envvars

**Comment by richardlau** [comment]
My thoughts:
> [nodejs/node@bc916e9](https://github.com/nodejs/node/commit/bc916e971ec90189c3c04985316a8c55f56f4585) tools,gyp: fix regex for version matching
> [nodejs/node@16661e6](https://github.com/nodejs/node/commit/16661e6636f00b70d5c5bed7fc027018a8d74b6e) build: fix configure script for double-digits
> [nodejs/node@33cd51e](https://github.com/nodejs/node/commit/33cd51e545a01b3dd36c65f0a77b4e627846692a) tools: update tooling to work with new macOS CLI …

These commits are backports relating to fixing building Node.js on macOS with Xcode 10 however Xcode 10 has also removed `libstdc++` which Node.js 6 uses (Node.js 8 and above use `libc++`) which we can't switch from without risking ecosystem breakage for prebuilt addons: https://github.com/nodejs/node/issues/24648. It's questionable whether these commits on their own would actually fix anything.

> [nodejs/node@74d3f0b](https://github.com/nodejs/node/commit/74d3f0bd780ec470b170b9e6943adc09e8eb1fb8) src: fix bootstrap_node on bsd

Fixes a bad bsd-only backport https://github.com/nodejs/node/commit/77a405b92f768a22c2fc2201d9fac4408108e741 that landed in 6.14.2. We should include this if doing another release.

> [nodejs/node@3c4949a](https://github.com/nodejs/node/commit/3c4949a6bb77bdae4ca5c2971ad8e61e381931fd) doc: document that addMembership must be called once in a cluster

¯\\_(ツ)\_/¯

> [nodejs/node@29748cb](https://github.com/nodejs/node/commit/29748cb13f2a94a087e3a6f9a26360a0997749ac) doc: simplify CODE_OF_CONDUCT.md

Unnecessary IMO (does anyone read this on non-master?). doc changes (this and the one above) are reasonably low risk so could be included if another release was done, but not worth doing a release for. 

> [nodejs/node@97d8bc8](https://github.com/nodejs/node/commit/97d8bc854164604b8f46ce1ef3370d9335dbdbd7) build: only check REPLACEME & DEP...X for releases
> [nodejs/node@e2faf8c](https://github.com/nodejs/node/commit/e2faf8c82aa2fd8b4d86c673c39afecd4179073e) test: fix test-repl-envvars

These are only necessary if we actually do another release.

**Comment by richardlau** [comment]
Of the two pull requests:
https://github.com/nodejs/node/pull/22633 falls under the n-api process under review at https://github.com/nodejs/Release/pull/410 (currently no objections). 

https://github.com/nodejs/node/pull/25939 looks like it is related to the security fixes in the recent v6 releases so probably warrants a new release?

**Comment by richardlau** [comment]
There's also https://github.com/nodejs/node/pull/25447 for AIX which fixes a regression introduced by https://github.com/nodejs/node/pull/17604 which was backported to v6.14.2.

**Comment by BethGriggs** [comment]
@nodejs/releasers @nodejs/lts - are there any concerns about doing this release with the list (or subset) of commits.  I should be able to find time to prepare the release if there are any concerns about the labour involved.

**Comment by MylesBorins** [comment]
I'm +1 on a final release with the above changes.

**Comment by mhdawson** [comment]
@BethGriggs no concerns from me, but based on the comments it was not clear to me if all of the commits from the original list apply.  Can you clarify the specific list that would be included?

**Comment by BethGriggs** [comment]
Draft commit list: 

- [ ] [nodejs/node@bc916e9](https://github.com/nodejs/node/commit/bc916e971ec90189c3c04985316a8c55f56f4585) tools,gyp: fix regex for version matching
- [ ] [nodejs/node@16661e6](https://github.com/nodejs/node/commit/16661e6636f00b70d5c5bed7fc027018a8d74b6e) build: fix configure script for double-digits
- [ ] [nodejs/node@33cd51e](https://github.com/nodejs/node/commit/33cd51e545a01b3dd36c65f0a77b4e627846692a) tools: update tooling to work with new macOS CLI …
- [x] [nodejs/node@74d3f0b](https://github.com/nodejs/node/commit/74d3f0bd780ec470b170b9e6943adc09e8eb1fb8) src: fix bootstrap_node on bsd
- [x] [nodejs/node@3c4949a](https://github.com/nodejs/node/commit/3c4949a6bb77bdae4ca5c2971ad8e61e381931fd) doc: document that addMembership must be called once in a cluster
- [ ] [nodejs/node@29748cb](https://github.com/nodejs/node/commit/29748cb13f2a94a087e3a6f9a26360a0997749ac) doc: simplify CODE_OF_CONDUCT.md
- [x] [nodejs/node@97d8bc8](https://github.com/nodejs/node/commit/97d8bc854164604b8f46ce1ef3370d9335dbdbd7) build: only check REPLACEME & DEP...X for releases
- [x] [nodejs/node@e2faf8c](https://github.com/nodejs/node/commit/e2faf8c82aa2fd8b4d86c673c39afecd4179073e) test: fix test-repl-envvars
- [x] [[v6.x backport] src: add environment cleanup hooks  ](https://github.com/nodejs/node/pull/22633)
- [x] [[v6.x] http: fix error check in `Execute()`](https://github.com/nodejs/node/pull/25939)

And the the following if they land cleanly or a backport is raised 
- [ ] [http: refactor outgoing headers processing](https://github.com/nodejs/node/pull/20250/files#diff-286202fdbdd74ede6f5f5334b6176b5cL320) 
- [ ] [build: set `-blibpath:` for AIX](https://github.com/nodejs/node/pull/25447)

**Comment by BethGriggs** [comment]
I'm leaning against the macOS with xcode 10 fixes based on @richardlau's [comments](https://github.com/nodejs/Release/issues/414#issuecomment-461209683) - I have not seen any requests for those, and if those commits are not guaranteed to fix anything then perhaps it is not worth the risk?

**Comment by richardlau** [comment]
> And the the following if they land cleanly or a backport is raised
> 
>     * [x]  [build: set `-blibpath:` for AIX](https://github.com/nodejs/node/pull/25447)

https://github.com/nodejs/node/pull/25447 doesn't land cleanly on `v6.x-staging` but the [`v8.x` backport](https://github.com/nodejs/node/pull/25521) does. Raised https://github.com/nodejs/node/pull/26478.

**Comment by BethGriggs** [comment]
https://github.com/nodejs/node/pull/20250 requested by @ljharb doesn't land cleanly on v6.x so will need a backport. I'm a little concerned that the PR is referenced in some ecosystem breakages, do we want to risk breaking anyone on v6.x this late?  Does it need to land with https://github.com/nodejs/node/pull/24006? 

Thoughts @nodejs/lts @nodejs/backporters?

//cc @apapirovski

**Comment by ljharb** [comment]
@BethGriggs the references, i believe, are that the PR *fixes* an issue - by backporting the Array.isArray changes in particular (not the rest) you’ll be allowing the ecosystem to remove its workaround for node 6+.

**Comment by MylesBorins** [comment]
@ljharb that is not the case. This change did indeed cause ecosystem breakage... I'll dig in a but more but my current gut is leaning to not making such a disruptive change at the end of LTS

**Comment by ljharb** [comment]
@mylesborins i have no interest in the http header changes - only in the use of `Array.isArray` over `instanceof Array` - i can’t conceive of how that change alone could cause breakage. Could that alone be backportes?

**Comment by MylesBorins** [comment]
Beth's initial assessment was spot-on. The change broke monkey patching the header response from 10.1.0 to 10.15.1 it also broke other things that required folks to make changes like https://github.com/antongolub/reqresnext/commit/cf19b6d84cec803abed3024412b70a0b0b0e94b

If what Beth is saying, that the change requires manual rebasing with lots of changes I am unfortunately strongly -1 unless we can show that there is a significant regression fixed by this 

While I appreciate the concern regarding the 6, specifically regarding removing a work around, the risk of larger ecosystem breakage has me concerned as we have only just fixed this in 10.x

Is there an issue that better explains the work around?

**Comment by ljharb** [comment]
https://github.com/facebook/jest/issues/7700#issuecomment-457957682 and https://github.com/facebook/jest/pull/5995#issuecomment-457840107 are the comments that led me to pursue backporting it - it's a bug in jest that seems unlikely to get fixed, which means jest is broken in some cases in node < 10.

Obviously we can still backport it to 8; it's just nice if we can also do that for 6, since node 6 will be around for awhile (just like node 4's still around, EOL or not).

**Comment by mhdawson** [comment]
@ljharb I'll agree with Myles that we need to balance risk versus benefit.  If it's a nice to have but risky due to not landing cleanly, having backed in release it may not make sense.

One question I'd have is if it's important why is it unlikely to be fixed in jest?

**Comment by ljharb** [comment]
It’s impossible or impractical to fix it in jest, i assume, since `instanceof Array` inside node has a reference to the original Array, and jest provides a different Array (and has no access necessarily to the original one) - whereas Array.isArray in node would work on anything that’s a subclass of a proper array, across realms as well.

**Comment by BridgeAR** [comment]
@ljharb I just had a look at this and I am confused as it seems already fixed in the latest v6? See https://github.com/nodejs/node/blob/v6.x/lib/_http_outgoing.js

**Comment by ljharb** [comment]
I’m a bit confused too. I will admit i read the jest issue and assumed that instanceof Array was being used in all node versions prior to that fix; if in fact the bug was added after node 6, then i apologize for all the added noise here.

**Comment by BridgeAR** [comment]
Closing as outdated. The last v6 release is already out.
