### ISSUE TITLE
Preparation for Node.js 12 

### ISSUE THREAD

**Issue by BethGriggs** [nodejs/Release#417]
Issue for tracking the progress of Node 12. The current checklist is based on @jasnell's guide for major releases - https://github.com/nodejs/node/pull/25497.

- [x] Cut branches [v12.x](https://github.com/nodejs/node/tree/v12.x), [v12.x-staging](https://github.com/nodejs/node/tree/v12.x) and keep in sync with `master`
- [x] Create v12.x-proposal branch that tracks v12.x -  ETA February 23rd 2019
- [x] Create test builds from v12.x-proposal  - ETA March 12th 2019
- [x] Start cherry-picking commits manually - ETA  March 23rd 2019
- [x] Start creating RCs from v12.x-proposal - 1 per week from March 23rd 2019
- [ ] Release - ETA April 23rd 2019

**SemVer-Major cutoff - March 23rd 2019**

**Comment by mhdawson** [comment]
We should probably add a step for adding the release to the data captured on benchmarking.nodejs.org

**Comment by BethGriggs** [comment]
First test build - https://nodejs.org/download/test/v12.0.0-test1482547441/

**Comment by vsemozhetbyt** [comment]
Sorry, if this is a wrong place to ask.

We remove experimental warnings for `fs` and `dns` promisified API (see https://github.com/nodejs/node/pull/26581 and  https://github.com/nodejs/node/pull/26592). Is it worth to also remove such warnings for [`readable[Symbol.asyncIterator]()`](https://nodejs.org/api/stream.html#stream_readable_symbol_asynciterator) and [`rl[Symbol.asyncIterator]()`](https://nodejs.org/api/readline.html#readline_rl_symbol_asynciterator)?

**Comment by rvagg** [comment]
it's critical that @nodejs/build comes up with a final "support platforms" list as well as the base platforms for compiling releases, I don't believe we have this written up in a single place but there are some major changes that we need to lock in

**Comment by richardlau** [comment]
> 
> 
> it's critical that @nodejs/build comes up with a final "support platforms" list as well as the base platforms for compiling releases, I don't believe we have this written up in a single place but there are some major changes that we need to lock in

That really sounds like something that should be on the agenda for the Build WG meetings (next one being later today: https://github.com/nodejs/build/issues/1715).

**Comment by rvagg** [comment]
Assuming we need to bump `NODE_MODULE_VERSION`, we have to make sure we don't just straight increment, we have Electron making a claim on the next two numbers (69 and 70) so we just bump past that. See https://github.com/nodejs/TSC/issues/651#issuecomment-471807498 and the current "registry" (WIP) @ https://github.com/nodejs/node/pull/24114

**Comment by Trott** [comment]
@BethGriggs Is the `tsc-agenda` label here for visibility (that is, to make sure the TSC knows about this issue) or is there something the TSC needs to actually do or decide here?

**Comment by BethGriggs** [comment]
@Trott, yes, it was more for awareness

**Comment by Trott** [comment]
Mentioned at the TSC meeting today. Removing the `tsc-agenda` label. Feel free to re-add it if there's more for the TSC to do.

**Comment by rvagg** [comment]
Working through an infrastructure checklist @ https://github.com/nodejs/build/issues/1768, it's not very healthy this close to release unfortunately.

**Comment by BethGriggs** [comment]
Do the symlinks for https://nodejs.org/dist/latest-vN.x/ get created automatically? Or is that something @nodejs/build typically handles?

**Comment by jasnell** [comment]
That happens automatically
