### ISSUE TITLE
End of life date for 6.x

### ISSUE THREAD

**Issue by MylesBorins** [nodejs/Release#421]
Maybe April 30th?

**Comment by richardlau** [comment]
> 
> 
> Maybe April 30th?

No objections. It would be good to settle on a date before we push out the planned final v6.x release so we can include it in the release post.

FWIW it's currently pencilled in as 1 April: https://github.com/nodejs/Release/blob/eb91c94681ea968a69bf4a4fe85c656ed44263b3/schedule.json#L22-L28

**Comment by mhdawson** [comment]
April 30th sounds good to me.
