### ISSUE TITLE
Move next weeks meeting?

### ISSUE THREAD

**Issue by MylesBorins** [nodejs/Release#424]
Hey All,

I'm organizing TC39 at google next week and won't be able to make the meeting, but I think it is important for us to review the Semver-Minor changes for 10.x. While we did do the last Semver-Minor release out of band (landed and then reviewed after), it might be nice to review in the meeting.

Can we move the meeting to this friday or next monday?

**Comment by mhdawson** [comment]
I'm out on vacation next week (March 25-29)  so if the following Monday is an option that would be my preference. Having said that don't block on me in terms of finding a time that works for the rest of the team.

**Comment by richardlau** [comment]
I won't be able to make next Monday/Tuesday (March 25-26)

**Comment by BethGriggs** [comment]
@MylesBorins, perhaps we could arrange a separate meeting to review the SemVer Minors for v10.x while still keeping the Thursday general Release meeting? Does this Friday work?

**Comment by MylesBorins** [comment]
I can always try and sneak out next Thursday… I’m not sure I’m going to have time to review all the 10.x semver minors before Friday anyways. So let’s work under the assumption I’ll make next week

We can also move forward with landing things based on no immediate objections and review the release PR before promoting it… we did that for the last LTS semver-minor and it worked out quite well

**Comment by BridgeAR** [comment]
> We can also move forward with landing things based on no immediate objections and review the release PR before promoting it… we did that for the last LTS semver-minor and it worked out quite well.

I like that idea as it sounds like the most straight forward one.

**Comment by BridgeAR** [comment]
Closing as outdated.
