### ISSUE TITLE
What is the difference between Current and Active?

### ISSUE THREAD

**Issue by toymachiner62** [nodejs/Release#430]
I'm curious what the difference between the Current and Active statuses of a Node.js version are.

My team is currently on version 9 and trying to determine whether to move to 10, 11, or 12 but i'm not sure what the statuses actually mean and there is nothing documented on the README about them (at least that I skimmed through and found).

**Comment by BethGriggs** [comment]
Does this help? https://github.com/nodejs/node#release-types

**Comment by MylesBorins** [comment]
Current is actively updated on a weekly or bi-weekly basis. It will be Semver-Minor or Semver-Patch depending on the backlog on master.

Active LTS has a monthly release cadence and will only contain changes that have already gone out in a Current release.

For production services I do not advise ever using Current. I would have advised being on 10 until 12 goes to Active LTS. As you are already on 11 you may want to upgrade to 12 soon after release, and hold off on future upgrades until 14 is in LTS.

**Comment by cjihrig** [comment]
"Current" represents the current release line that receives all non-breaking changes that land in Node's master branch. The things that land in an active LTS or maintenance line are covered in https://github.com/nodejs/Release#release-plan.

> My team is currently on version 9

That version has been end of life for a while. Companies should generally stick to even numbered versions. I'd recommend moving to 10 now, and 12 once it goes LTS.

**Comment by toymachiner62** [comment]
> Does this help? https://github.com/nodejs/node#release-types

Only partially. It doesn't say anything about `Active`

**Comment by toymachiner62** [comment]
Closing as i've gotten my answer. Thanks all.

**Comment by maksymkp** [comment]
https://nodejs.org/en/about/previous-releases#previous-releases
