### ISSUE TITLE
Is it time to update release date information?

### ISSUE THREAD

**Issue by sam-github** [nodejs/Release#431]
Could the release dates for LTS, current, and next (12.x) get updated?

https://github.com/nodejs/Release/wiki has (or links to) the various locations of this information. I think it could be brought together a bit more, but as long as its findable, it works.

It would be nice to have the 10.x schedule extended to the next semver-minor (10.17). That would give me a target for TLS1.3 in 10.x (for example).

I think 10.16.0 is being done by @BethGriggs not @MylesBorins, so https://github.com/nodejs/Release/wiki#q2-2019-dubnium-10x-release-schedule-draft may need updating.

Now that 12.x is almost here, I think its time to extend https://github.com/nodejs/Release#release-schedule with 13.x and 14.x. I've been doing some extrapolating lately on when I thnk they'd be based on old dates to see if we will have a FIPS gap (see https://github.com/nodejs/TSC/pull/677). It would help to have the LTS group's expected dates here.

11.x had a good list in https://github.com/nodejs/Release/issues/397, but its almost to the end. I think it doesn't need to be extended because the very last release by @codebytere will be the last? Perhaps its EOL date should be added.

**Comment by MylesBorins** [comment]
@sam-github we just updated the dates in the wiki, does that look better to you?

**Comment by sam-github** [comment]
@MylesBorins It would help if the 10.x plan went until 10.17.0, and 13.x and 14.x had predictions.

This might seem far away, but its so I can predict when semver-minors might next be released on 10.x if they miss 10.16.0, and for 13.x & 14.x, without dates for them I can't predict the "fips gap" very accurately in https://github.com/nodejs/TSC/pull/677. 

If not now, perhaps when or shortly after 12.x and 10.16.0 are released, the next LTS and minor cycle (respectively) can be added?

**Comment by MylesBorins** [comment]
We’ve generally been doing this on a quarterly basis… we can plan out 10.17, but TBH there was an intention of thinking about that until the end of Q2.

We could just pick dates for 13 / 14 now if we want, easily enough.

**Comment by jasonkarns** [comment]
According to the schedule.json, 11 is in maintenance mode as of a week ago: https://github.com/nodejs/Release/blob/2e839d1e5921a509c9522054c7ad3bdf6a6ea126/schedule.json#L55 (2019-04-01), but 12 doesn't start until 2019-04-23. That puts us in a "temporal dead zone" from 4-1 to 4-23 where there is (strictly speaking) no "Current Release".

For users seeing "11.13.0 Current" on nodejs.org is no big deal for users. But it's problematic for tooling that consumes the schedule.json file directly.

I don't have any solutions or requests here. But the gap in the dates is causing a bit of a problem for nodenv/node-build whereby our tooling is attempting to warn users that 11.13.0 is in maintenance mode, but there isn't a "Current" release to point them to.

**Comment by BethGriggs** [comment]
I think all of this was covered by the updates in https://github.com/nodejs/Release/pull/434
