### ISSUE TITLE
Adding a "security" property to dist/index.json

### ISSUE THREAD

**Issue by bnb** [nodejs/Release#437]
Per a brief discussion in today's Node.js Security Working Group meeting, I wanted to bring up the possibility of adding a `security` property into the [dist/index.json](https://nodejs.org/dist/index.json).

To outline a possible structure/implementation for this property:
- add a `security` property to each new release object, from the date it's implemented and beyond
- this property has a key of `security` and a boolean as the value
	- if the release is a security release, this boolean will be `true`
	- if the release is not a security release, this boolean will be `false`

The intent is that this is similarly structured to `LTS`, providing a signal to consumers of the file that a release is a security release.

Theoretically, developers (us included!) could use this in a few ways:
- loop over every release in a release line until they encounter `true` – when they encounter true for the first time, they know that version is the minimum secure version
- create a log of all security releases, and tie those to blog posts (which can be programmatically linked thanks to our blog post structure)
- in lists displaying Node.js versions, indicate which versions are security releases (think something like Glitch or RunKit)

Hopefully this wouldn't be a massive burden for y'all when maintaining releases, but if it is that's 100% understandable ❤️

**Comment by richardlau** [comment]
Seems reasonable, although it would be reliant on the person doing the release to update the property. Security releases are typically not done by the regular releasers.

**Comment by sam-github** [comment]
It would have to be part of the release process, and it could also be part of the security release process. The person going through the sec release process often isn't doing the actual cutting of the release, so a step there of "check that the metadata was correct" could be useful as a double-check.

**Comment by richardlau** [comment]
The tool to generate `dist/index.json` is https://github.com/nodejs/nodejs-dist-indexer.

**Comment by richardlau** [comment]
I imagine it would be more the security release process, with the property defaulting to false like the `NODE_VERSION_IS_RELEASE` flag is.

**Comment by MylesBorins** [comment]
We may want to add a similar NODE_VERSION_IS_SECURITY_RELEASE tag in the build

**Comment by mhdawson** [comment]
Both adding it to the meta data and @MylesBorins suggestion makes sense to me. +1

**Comment by richardlau** [comment]
Raised https://github.com/nodejs/node/pull/27612 and https://github.com/nodejs/nodejs-dist-indexer/pull/8.

**Comment by richardlau** [comment]
Added to the Release agenda as this is a change to the release process.

**Comment by richardlau** [comment]
Rod has questioned the proposed approach and [suggested some alternatives](https://github.com/nodejs/node/pull/27612#issuecomment-490698922).

I've implemented the first alternative (parse commit message for `This is a security release.`) in https://github.com/nodejs/nodejs-dist-indexer/pull/9.

**Comment by richardlau** [comment]
The original proposal https://github.com/nodejs/node/pull/27612 has been closed.

Opened alternative approach https://github.com/nodejs/node/pull/27643 as a counterpart to https://github.com/nodejs/nodejs-dist-indexer/pull/9.

**Comment by richardlau** [comment]
Reopening because while the Node.js side is taken care of the property won't be added to the distribution index files until https://github.com/nodejs/nodejs-dist-indexer/pull/9 lands.

**Comment by bnb** [comment]
Thank you for your work on this @richardlau ❤️

**Comment by richardlau** [comment]
Index files now contain a security property as of https://github.com/nodejs/nodejs-dist-indexer/pull/9.
