### ISSUE TITLE
Prevent duplicated "Current Release"

### ISSUE THREAD

**Issue by BridgeAR** [nodejs/Release#439]
Both, v11.x and v12.x are both our "Current Release" right now and that seems confusing. I suggest we switch to `Current Maintenance` for v11.x from the date that v12.0.0 was released. That way it's clearer how we support the release line.

**Comment by BethGriggs** [comment]
+1, then it will match what we set in the `schedule.json`. We should add a note somewhere clarifying what Current Maintenance means in terms of our commitments (whether it is exactly the same as LTS Maintenence or not)

**Comment by mhdawson** [comment]
I agree we need to be careful with "Current Maintenance".  We've purposely kept the commitment of any maintenance for a Current after 6 months vague.  I think it may be most straight forward that we just have a single "current" and that current switch on the date of the new release.

**Comment by BridgeAR** [comment]
Seems like this is nothing we ever found a real solution for. It's not ideal and it would be great to improve this but we did not follow-up on it for a long time. Thus, I'm closing this as likely won't fix.
