### ISSUE TITLE
Berlin Collaborator Summit - Release session

### ISSUE THREAD

**Issue by BethGriggs** [nodejs/Release#442]
I've submitted for a session at the Berlin Collaborator Summit. I thought we could use this issue to build an agenda/list of items we would like to cover in the session should it happen. 

- Onboarding new releasers - formalise the process 
  -  shadowing 
  - Tierney / Manil
  - Action: 
- Change to the concept of _Done_  - PRs only get closed once an appropriate backport has been raised? 
- Discuss any changes to LTS policies - perhaps including https://github.com/nodejs/node/issues/25785
- Plan automation to reduce the effort of backporting/ creating releases
- Access to land on staging #388 
- Change meeting times? 
Feel free to add to the agenda.

**Comment by BethGriggs** [comment]
@nodejs/release, are there any further issues/topics that we should schedule for discussion at the summit?

**Comment by BridgeAR** [comment]
Closing, since the session is already over.
