### ISSUE TITLE
Should libuv upgrades be semver-minor?

### ISSUE THREAD

**Issue by MylesBorins** [nodejs/Release#443]
Refs: https://github.com/nodejs/node/pull/24332

I've added the label periodically here is an example of an earlier version marked semver-minor

https://github.com/nodejs/node/pull/18260

1.24.1 and 1.25.0 were both landed as patches as well

https://github.com/nodejs/node/pull/25571
https://github.com/nodejs/node/pull/25078

In general we have not landed these in semver-patch LTS releases, as such I think it would make sense to make it explicit that they are always semver-minor

thoughts?

/cc @cjihrig

**Comment by mhdawson** [comment]
My thought is that libuv updates should match the semver stated by libuv (ie patch if patch, minor if minor), unless there is a specific reason that warrants something different.

**Comment by BridgeAR** [comment]
I added it to the release agenda to discuss this in the next meeting.

I personally do not have a strong opinion but it's probably a good idea to idea to follow the libraries own semver version on our side to include it, if applicable. This can't be applied to dependencies that do not use semver and there might be exceptions where it makes sense to include an update in e.g., a patch release for security reasons or similar even though it's maybe semver-major for the dependency.

**Comment by BethGriggs** [comment]
The consensus from #509 was that we will follow the semverness of libuv. If there's a patch upgrade of libuv, this can be included in a patch release of Node.js.
