### ISSUE TITLE
Missing codenames after v10

### ISSUE THREAD

**Issue by DanielRuf** [nodejs/Release#447]
After NodeJS 10 there are no codenames listed at https://nodejs.org/en/about/releases/

https://github.com/nodejs/Release/blob/master/CODENAMES.md

**Comment by BridgeAR** [comment]
If I'm not mistaken we've never chosen a codename for v12. There was a very long discussion around this but I forgot where.

**Comment by targos** [comment]
There's a list of proposed codenames here: https://github.com/nodejs/Release/blob/master/CODENAMES.md. It is not set in stone, but unless somebody objects, v12 LTS will be called "Erbium".

**Comment by DanielRuf** [comment]
I am not aware of the process but I thought the codename is given before it becomes the current / stable release (we are at 12.3.0 for the current release channel).

**Comment by okuryu** [comment]
In my understanding, the codename is given after LTS starts (scheduled for 2019-10-22). v12 is still the current version not LTS version.

```
$ curl -s https://nodejs.org/dist/index.json | jq ".[0]|.version,.lts"
"v12.3.0"
false
$ curl https://resolve-node.now.sh/lts
v10.15.3
```

**Comment by DanielRuf** [comment]
> In my understanding, the codename is given after LTS starts

Ah ok, that makes sense then =)

> LTS releases

I will close this. Was just a bit confused because the table does not contain them and I wanted to reference it.

Sorry for that, was probably a bit unclear for me.
