### ISSUE TITLE
Release automation tooling 

### ISSUE THREAD

**Issue by BethGriggs** [nodejs/Release#451]
At the collaborator summit session, we discussed ideas for toolings for release including: 

- a tool that can automatically land backport PRs with the correct metadata, similar to `git node land`
- automatically open PRs for conflicts, that contributors can pick up and resolve

**Comment by boneskull** [comment]
Would this be potentially in the form of a GitHub Action?

As Mocha has joined the OpenJSF as a "growth" project, (ostensibly) one of the requirements is to enable LTS releases.

"Trunk-based development" (which is roughly what Node.js does, I think) seems like a good fit, but there's plenty of room for automating backports, cherry-picking, and PR cross-referencing.

**Comment by boneskull** [comment]
At any rate, uh, you have my axe.

**Comment by MylesBorins** [comment]
@boneskull I don't think there is a requirement for growth projects to have an LTS program unless they would like to support it.

**Comment by boneskull** [comment]
@MylesBorins Given Growth-stage projects "are expected to move out of the Growth stage within two years"--meaning they should eventually become impact projects--and a requirement of an impact project is "to have publicly documented release cycles and plans for 'Long Term Support' (LTS)," I was operating under the assumption that a Growth project would need this to "graduate."

**Comment by MylesBorins** [comment]
I think that is something we should bring up and discuss at the CPC. I'm
not 100% that all impact projects must have an LTS program. Would be good
to clarify that.

**Comment by BethGriggs** [comment]
I think this issue has gone a little stale. I think we should close this, and open individual issues for the specific pieces automation we wish to target in future.

> a tool that can automatically land backport PRs with the correct metadata, similar to git node land

Was been contributed by @andrewhughes101 and @AshCripps in https://github.com/nodejs/node-core-utils/pull/383 :tada:

> automatically open PRs for conflicts, that contributors can pick up and resolve

I don't think we have had (nor are chasing) consensus on this process change.
