### ISSUE TITLE
Node.js 11 is no longer Active

### ISSUE THREAD

**Issue by MatonAnthony** [nodejs/Release#453]
According to https://github.com/nodejs/Release/blame/master/README.md#L9 Node.js 11.x is a ´Current Release` with an `End-of-life` on the `2019-06-01`.

Today is `2019-06-01`, I am wondering if this should be removed from the table.
If yes, I am happy to make a pull request to remove it from the array and move it down to the `End-of-Life Releases`.

PS: Thank you for all the amazing work :)

**Comment by MylesBorins** [comment]
Hey @MatonAnthony 

if you would like to open a PR that would be amazing, would be happy to review
