### ISSUE TITLE
Document how and when to backport semver-major PRs

### ISSUE THREAD

**Issue by BridgeAR** [nodejs/Release#459]
We recently started to backport semver-major PRs in a semver-patch way. What we do not yet have is a documentation on what exactly should be backported and how. This would probably be valuable for other people.

Refs: https://github.com/nodejs/node/pull/27570 (as example)

**Comment by BethGriggs** [comment]
I don't think we've continued to do this by default. @BridgeAR do you still think this is still something worth considering/documenting?

**Comment by BethGriggs** [comment]
Closing for now, feel free to reopen if we should revisit this.
