### ISSUE TITLE
Final Node 8 scheduled release?

### ISSUE THREAD

**Issue by BethGriggs** [nodejs/Release#466]
Should we do a final Node 8 release to tidy up the remaining open Backport PRs? 

https://github.com/nodejs/node/pulls?q=is%3Aopen+is%3Apr+label%3Av8.x  

Please 👍 if you think we should. If we agree to do this, i'd suggest the release should be in August to do it as far in advance before EOL.

**Comment by bnoordhuis** [comment]
Big thumbs up from me. Certainly the V8 fix and the openssl upgrade should be released.

Open question: should we also update the built-in TLS root certificates? There's no open backp-ort PR right now but I could put one together.

**Comment by cjihrig** [comment]
> should we also update the built-in TLS root certificates?

Personally, I'd like to see that.

**Comment by BethGriggs** [comment]
Fair few +1's, I've gone ahead and scheduled the release for [27th August](https://github.com/nodejs/Release/wiki#q2-2019-carbon-8x-release-schedule). I'll start pulling in the open backports.

**Comment by bnoordhuis** [comment]
> update the built-in TLS root certificates

Just to close the loop: https://github.com/nodejs/node/pull/29137
