### ISSUE TITLE
Preparation for Node.js 13

### ISSUE THREAD

**Issue by BethGriggs** [nodejs/Release#475]
Issue for tracking the progress of Node 13. Checklist based on https://github.com/nodejs/node/blob/master/doc/releases.md#major-Releases

- [x] Cut branches v13.x, v13.x-staging and keep in sync with master
- [x] Create v13.x-proposal branch that tracks v13.x
- [x] Create test builds from v12.x-proposal - Sept 10th 2019
- [x] Start creating RCs from v12.x-proposal - ETA Sept 22nd 2012. These will happen each Tuesday until 15th October.
  - [x] rc0 - 24/09
  - [ ] rc1 - 1/10
  - [ ] rc2 - 8/10
  - [ ] rc3 - 15/10
- [ ] Release - Oct 22nd 2019

 Major cutoff - 22nd Sept 2019.

**Comment by richardlau** [comment]
Link to the PR: https://github.com/nodejs/node/pull/29504

**Comment by targos** [comment]
v13.0.0 was released 🎉
