### ISSUE TITLE
NodeJS_all_x64_Installer

### ISSUE THREAD

**Issue by saymoncoppi** [nodejs/Release#480]
Hello Guys!
Im making an all_x64_Installer script to automate the install/update NodeJS tasks.
This is based on the original [wiki](https://github.com/nodejs/help/wiki/Installation) plus some automation, nothing so fancy. But I guess the community will like.

You could check the results on:
https://github.com/saymoncoppi/NodeJS_all_x64_Installer

So... Due this I wanna know if my thoughts are right. 
Im extracting the latest LTS version from the [schedule.json](https://github.com/nodejs/Release/blob/master/schedule.json) file and I realized this pattern:

The current latest LTS has codename **filled** at the file and the next LTS not.
"v10": {
    "start": "2018-04-24",
    "lts": "2018-10-30",
    "maintenance": "2020-04-01",
    "end": "2021-04-01",
    "codename": "Dubnium"
},

...

"v12": {
    "start": "2019-04-23",
    "lts": "2019-10-22",
    "maintenance": "2021-04-01",
    "end": "2022-04-01", 
    "codename": ""
  },

Can I still considering this  behavior as a pattern? Make sense for you? Im asking this bc the script uses this info to get the node-vX.X.X-linux-x64.tar.xz file from https://nodejs.org/dist.

I have some work to mark as finished the script. But nowadays its already functional... Ok?

**TODO:** 
- Verify the current installed version; 
- Ask If the user really wanna update; 
- Offer the latest version, not only latest LTS; 
- Slim down the unnecessary files from NodeJS after instalation process.

**References:**
https://github.com/nodejs/Release/blob/master/CODENAMES.md
https://github.com/nodejs/Release/blob/master/schedule.json

**Comment by BethGriggs** [comment]
@saymoncoppi, the codename is only added when the release transitions from "Current" to "LTS" - I think you would be able to rely on that pattern.

**Comment by BridgeAR** [comment]
I guess there is nothing left for us here. I am closing this therefore. @saymoncoppi please leave a comment if you think this should be opened again.
