### ISSUE TITLE
Release plan - v13.x Current

### ISSUE THREAD

**Issue by targos** [nodejs/Release#487]
Week | Approximative date | Release | Releaser
------------ | :-------: | ------ | ---- 
2019 - 43 | 2019-10-22 | v13.0.0 | @BethGriggs
2019 - 43 | 2019-10-23 | v13.0.1 | @targos
2019 - 45 | 2019-11-05 | v13.1.0 | @targos
2019 - 47 | 2019-11-21 | v13.2.0 | @BridgeAR
2019 - 49 | 2019-12-03 | v13.3.0 | @BridgeAR
2019 - 51 | 2019-12-17 | v13.4.0 | @MylesBorins 
2019 - 51 | 2019-12-18 | v13.5.0 | @MylesBorins 
2020 - 02 | 2020-01-07 | v13.6.0 | @BridgeAR
2020 - 04 | 2020-01-21 | v13.7.0 | @codebytere
2020 - 06 | 2020-02-04 | v13.8.0 | @BethGriggs
2020 - 08 | 2020-02-18 | v13.9.0 | @codebytere
2020 - 10 | 2020-03-03 | v13.10.0 | @codebytere
2020 - 11 | 2020-03-11 | v13.11.0 | @MylesBorins 
2020 - 13 | 2020-03-26 | v13.12.0 | @MylesBorins
2020 - 16 | 2020-04-14 | v13.13.0 | @targos
2020 - 18 | 2020-04-29 | v13.14.0 | @BridgeAR

**Comment by targos** [comment]
Added to the agenda to discuss this week.
I went with a regular biweekly release, except for end of year holidays where I propose a 3 weeks break.

**Comment by targos** [comment]
Ping @BridgeAR in case you forgot about this week's release.

**Comment by BridgeAR** [comment]
@targos I am on it

**Comment by MylesBorins** [comment]
@BridgeAR lmk if you need help at all for today's release. It is really important to get it out today as it unflag esm

**Comment by BridgeAR** [comment]
I would like to pull in V8 7.9 but both, ARM and AIX have issues finishing CI tasks.

I just went ahead and opened a draft: https://github.com/nodejs/node/pull/30547

**Comment by MylesBorins** [comment]
Due to the current regressions in 13.x I'm aiming to get another release out tomorrow. @BridgeAR as you are scheduled to do a release next week lmk if you want to pick it up, but no expectations to make extra work on a week you didn't sign up for... I have the time to get it done

**Comment by BridgeAR** [comment]
@MylesBorins I won't be able to publish an extra release tomorrow, so please feel free to do so.

**Comment by MylesBorins** [comment]
Quick update, had a wildly busy day... but managed to get staging update to date and awaiting one more `backport-requested` to have a green CI and 13.x will be up to date with master!

Due to timing though I'm going to have to push the release to tomorrow. Will try and get a PR open today / tonight if possible so we can kick off building / testing

**Comment by BridgeAR** [comment]
As a heads up: I plan on delaying the release for one or two days to resolve https://github.com/nodejs/node/issues/32296

**Comment by BridgeAR** [comment]
I updated staging but there are only very few commits in for a new release (~30).

**Comment by targos** [comment]
@BridgeAR will you be able to prepare the next release (2020-04-28) so I can handle v12.16.3 on the same day?

**Comment by MylesBorins** [comment]
If @bridgear is not available I might be able to pick it up

**Comment by BridgeAR** [comment]
@targos I am available and I'll prepare the next update. I added myself to the list above accordingly.
