### ISSUE TITLE
Node.js Collab Summit - Release agenda

### ISSUE THREAD

**Issue by BethGriggs** [nodejs/Release#502]
- Discuss onboarding new releasers 
- Automation

**Comment by BethGriggs** [comment]
The meeting is happening in around 20mins time - https://zoom.us/j/680085630

https://github.com/openjs-foundation/summit/blob/master/2019-12-Montreal/agenda.md#agenda

Ping @nodejs/release in case anyone wants to join the Zoom call (sorry for the late notice)

**Comment by targos** [comment]
I'll join!

**Comment by sam-github** [comment]
@BethGriggs what's the agenda?

**Comment by BethGriggs** [comment]
We covered: 
 - What the release team do and their responsibilities 
 - Onboarding technique - action to arrange formal shadowing/mentoring #511, ask people to show interest. 
 - @MylesBorins walked through the release process documented in https://github.com/nodejs/node/blob/master/doc/releases.md 
 - Referenced open backports and how to backport to release lines - https://github.com/nodejs/node/blob/master/doc/guides/backporting-to-release-lines.md
- Call for volunteers - please mention your interest and likely available time over in #511
- Call for automation

**Comment by keywordnew** [comment]
As the event is over, can this be closed? :-)
