### ISSUE TITLE
Release Schedule JSON

### ISSUE THREAD

**Issue by wesleytodd** [nodejs/Release#508]
On the [package maintenance wg call today](https://github.com/nodejs/package-maintenance/issues/283) we were discussing one of our initiatives to keep users testing on up-to-date LTS lines.  In this effort we wanted to [standardize grammar around the lines](https://github.com/nodejs/package-maintenance/issues/236) and [build tooling around it](https://github.com/pkgjs/nv/).

In that tool I loaded the schedule from where I saw it in the website repo: 

https://raw.githubusercontent.com/nodejs/nodejs.org/master/source/schedule.json

But it looks like this repo

https://github.com/nodejs/Release/blob/master/schedule.json

Which is the canonical source?  Can we rely on this always existing?  Is there anything we need to know so we can support this long term?

**Comment by richardlau** [comment]
https://github.com/nodejs/Release/blob/master/schedule.json is canonical. The one in nodejs.org is a candiate for removal (https://github.com/nodejs/nodejs.org/pull/2773) as the website builds overwrites it with the one from this repository.

**Comment by wesleytodd** [comment]
Awesome.  I will update the tool to consume the one here.  Is there any guarantee around this file?  I would like to make sure that if changes are made we are aware and can update the tooling we provide.

**Comment by richardlau** [comment]
What kind of guarantees are you looking for? We do keep the file updated. Dates in the future are subject to change. Also codenames are only added to the schedule when the release becomes LTS (so, for example, `erbium` was only added to 12.x when 12.13.0 was released (https://github.com/nodejs/Release/pull/488)).

**Comment by wesleytodd** [comment]
All that is expected.  The only thing I want is that if the format and location of the file change we will know about it.  Obviously our tests will fail, but it would be nice to know before then I guess.

**Comment by BethGriggs** [comment]
It does not appear that there is anything further for us to do here, but please let me know if you disagree and we can reopen.
