### ISSUE TITLE
Node.js Release mentoring/streaming

### ISSUE THREAD

**Issue by BethGriggs** [nodejs/Release#511]
Zoom Webinar: https://zoom.us/j/818682337

Please post here if you're interested in joining release mentoring or shadowing. The releasers working group will try and schedule a few mentoring sessions that people can join.

**Comment by matchai** [comment]
Great initiative! 👍 
I'd love to get involved and help work toward automating parts of the process.
I'm in the EST (UTC-5) timezone for scheduling, and would be able to squeeze in an hour a week.

**Comment by thescientist13** [comment]
Hi team!

I would be interested in shadowing with an interest towards helping support automation opportunities / initiatives.

**Comment by danielleadams** [comment]
Thanks for the session today! I would also be interested in some shadowing. I'm in the EST zone. My schedule is pretty flexible, and I can probably do 1/2 hours per week.

**Comment by sxa555** [comment]
Also interested 😇

**Comment by BethGriggs** [comment]
We discussed this in the last Release WorkGroup Meeting (#512).

From the minutes: 

>  * (Myles) I want to help with this. We should pick some times as a working group.
>  * Use regular slot scheduled by Myles 11am EST alternate Tuesday. 
>  * Should steam live to YouTube using Zoom account? 
>  * Ask whether they’d prefer it to be live streamed or a private setting
>  * Start January 2020

The first session we're setting up is 11 am EST alternative Tuesday's starting January 7th 2020. We will discuss with the participants who join whether they're happy for the session to be streamed so that those who cannot make it can watch it back. I'll aim to set up the Zoom/Webinar logistics early next week. We'll also aim to arrange a few more session timeslots in future.

**Comment by BethGriggs** [comment]
The first session will be tomorrow (Tuesday 7th) at 11AM EST 
Zoom Webinar: https://zoom.us/j/818682337

I'm working on trying to get this added to the https://nodejs.org/calendar

**Comment by mhdawson** [comment]
@BethGriggs added to the calender. Let me know if it does not look right.

**Comment by BethGriggs** [comment]
Thanks @mhdawson. 

The first session we walked through the steps in https://github.com/nodejs/node/blob/master/doc/releases.md for the v12.x release. 

Next session is Tue, January 21, 11AM EST. I think it would be useful to use this time to go through and audit the minors for v12.x and v10.x

**Comment by BethGriggs** [comment]
Unfortunately, I will be unable to run tomorrows session. I will cancel in the calendar - unless someone else is available to host?

/cc @danielleadams

**Comment by danielleadams** [comment]
@BethGriggs No worries - thanks for the heads up!

**Comment by danielleadams** [comment]
It looks like the Zoom ID expired - is the one here still up to date?

**Comment by MylesBorins** [comment]
I'm on the call right now waiting to be promoted

**Comment by BethGriggs** [comment]
:wave: This weeks session overlaps with the OpenJS World conference, so I will not be able to host. I will cancel in the calendar for this week and resume on 7th July. But, please feel free to reach out async.

**Comment by BethGriggs** [comment]
👋 My calendar is pretty difficult these days, and I am not sure I can continue to make a regular slot. My thoughts are to end the scheduled sessions, unless someone else would like to take over as the host? I can still offer time to pair on specific releases 1-1 or as a small group - it's just committing to a regular slot that is difficult.

/cc @nodejs/release

**Comment by danielleadams** [comment]
I am okay with forgoing these for now. I'd be happy to pick up the slot maybe in the new year too 😄
