### ISSUE TITLE
Flatpak support

### ISSUE THREAD

**Issue by aberba** [nodejs/Release#514]
[Flatpak](flatpak.org) is a next-generation technology for building and distributing desktop applications on Linux with support for all major Linux distributions. Create one app and distribute it to the entire Linux desktop market. Flatpak apps continue to be compatible with new versions of Linux distributions. 

Hundreds of Linux apps are now distributed on Flathub.org, the online flatpak store. Please, consider distributing your Node.js runtimes using flatpak too.

**Comment by richardlau** [comment]
There's previous discussion in https://github.com/nodejs/build/issues/580. Like everything it will require someone to volunteer to do the work and to keep it maintained.

**Comment by sam-github** [comment]
Lets not spread the conversation across multiple issues, I'll close this in favour of the pre-existing one, https://github.com/nodejs/build/issues/580
