### ISSUE TITLE
Create offboarding documentation/policy

### ISSUE THREAD

**Issue by BethGriggs** [nodejs/Release#542]
Inspired by https://github.com/nodejs/build/pull/2142, we should document the offboarding process including: 
 - Removal from teams
 - Removal of release keys (#499)
 - Moving to Releaser emeritus in both `nodejs/node` and `nodejs/release`

**Comment by richardlau** [comment]
>     * Removal from teams

@Trott suggests in https://github.com/nodejs/Release/issues/534#issuecomment-594180996 to add removal from the `@nodejs/security-release` and `@nodejs-private/security-release` teams to the offboarding checklist.

**Comment by BethGriggs** [comment]
Closing as the initial version landed in #644
