### ISSUE TITLE
Auditing current list of LTS members

### ISSUE THREAD

**Issue by MylesBorins** [nodejs/Release#549]
hey @nodejs/lts it has been a little while since we've cleaned up the membership list. If you are currently a member of the list and would like to remain so please chime in with a 👍on the post. If you would like to be removed please chime in with a 👎on this post.

For those who are not on the team but would like to participate please feel free to add a comment to this thread or alternatively reach out to me directly and we will figure something out.

**Comment by MylesBorins** [comment]
If folks do not chime in within 2 weeks time I think it would be fair to automatically remove them for the list, and make it really easy for them to rejoin in the future by just asking. I'll do my best to reach out to folks individually, but I want to make my intentions to do so clear. If anyone has an issue please lmk

**Comment by richardlau** [comment]
I thought I was in the LTS team but I'm not. I probably should be.

**Comment by MylesBorins** [comment]
@richardlau https://github.com/nodejs/Release/issues/550

**Comment by srl295** [comment]
I probably don't need to be… @richardlau can ping me if needed :]

**Comment by MylesBorins** [comment]
@ErisDS @bnoordhuis @trevnorris @othiym23 @geek @shigeki @yunong as this issue has been open for over three weeks without a response I'm going to remove you from the LTS team. If you would like to be re-added please open an issue
