### ISSUE TITLE
Publish a debug version when making a new release

### ISSUE THREAD

**Issue by gengjiawen** [nodejs/Release#555]
Maybe publish a debug version when making a new release, only for debug purpose.
Like `node_pdb` for windows IIUC (https://nodejs.org/download/nightly/v14.0.0-nightly20200322ecfb7b0988/SHASUMS256.txt)

PS: If you want to check the repo in description, see https://github.com/gengjiawen/node-debug.

_Originally posted by @gengjiawen in https://github.com/nodejs/node/issues/32402#issuecomment-603159700_

**Comment by gengjiawen** [comment]
Mainly for linux build. This will help a lot when debugging V8 api and maybe other staff.

**Comment by bnoordhuis** [comment]
The subject of "spins" (for want of a better word) has come up a few times but the problem is that it's confusing to end users.

We don't want people to download `node-v14.15.16-linux-debug.tar.gz` because they think it includes the debugger and then are appalled by the terrible performance.

**Comment by gengjiawen** [comment]
But like `win-x64/node_pdb.7z`, devs generally not using it or see it ? or we add  some note to give users strong suggestion not using it for production env ?

**Comment by bnoordhuis** [comment]
The .pdb isn't executable so it's less of an issue.

I'm skeptical naming it `dev-only` will help. I'm sure some people will think "yeah, I'm using it for dev only."

**Comment by gengjiawen** [comment]
I believe this exe is `pdb-bundled` ? 
![image](https://user-images.githubusercontent.com/3759816/77431081-2c9cd400-6e17-11ea-8fe7-da57585b86b6.png)

Be that as it may, I think it's a good way to improve the debug experience.
Ask user to build debug version seems too much work.

**Comment by gengjiawen** [comment]
Is it okay every time we launch the debug version Node.js, we print warn message like we do when we using an experimental feature ? It could saves lots of trouble.

**Comment by richardlau** [comment]
Do we know how much additional space we will need on the download server for this? We do periodically run out of space.

cc @nodejs/build-infra

**Comment by richardlau** [comment]
Also this seems a good candidate for https://unofficial-builds.nodejs.org/?

**Comment by bnoordhuis** [comment]
> Do we know how much additional space we will need on the download server for this?

Debug builds are pretty big. This is on my Linux machine:
```
$ ls -lh out/Debug/node
-rwxrwxr-x 1 bnoordhuis bnoordhuis 1.2G Mar 20 21:06 out/Debug/node
```

**Comment by gengjiawen** [comment]
on Linux

``` console
root@4e9f389a8912 ~/node# ll out/Debug/node
-rwxr-xr-x 1 root root 699M Mar 25 00:55 out/Debug/node*
```

on macOS

```console
daniel@Daniels-iMac ~/c/node> ll out/Debug/node
-rwxr-xr-x  1 daniel  staff   103M Mar 21 13:59 out/Debug/node
```

Not quite sure the size difference comes from.

**Comment by gengjiawen** [comment]
Maybe we published as a 7zip package `7z a node-debug.7z out/Debug/node`

```console
root@81bad7ca9b64 ~/node# ll node-debug.7z 
-rw-r--r-- 1 root root 141M Mar 25 02:26 node-debug.7z
```

**Comment by rvagg** [comment]
I nearly coughed up the water I was drinking reading those sizes.

Does `xz` get you any smaller? It's more standard than `7z` on Linux. I guess there's a lot of text symbols in there too, maybe bzip2 would even be worth trying, it's very available.

Probably not something we should consider for nightlies or these other automatic channels. _Maybe_ releases, but that's a lot of size to swallow. It could easily be integrated into an unofficial-builds recipe (see that repo, recipes are not hard to make if you want to propose one). We'd just have to run some numbers and extrapolate what the implications for space will be and whether we want to deal with that. We have access to block storage that we can grow but I'd hate to be too dependent on a lot of it if we have to abandon a particular provider and scramble to move our stuff to somewhere else.

**Comment by gengjiawen** [comment]
> Does xz get you any smaller?

```console
-rwxr-xr-x 1 root root 139M Mar 24 02:25 node.xz*
```

**Comment by gengjiawen** [comment]
Another thing is noticeable is 13.11.0 looks much bigger, nearly 220M in 7z (see https://github.com/gengjiawen/node-github-workflow/runs/532947564).

The 118M version is I build master using clang. What do I missing ? Compiler difference or V8 ?

**Comment by gengjiawen** [comment]
> Another thing is noticeable is `13.11.0` looks much bigger, nearly 220M in 7z (see [gengjiawen/node-github-workflow/runs/532947564](https://github.com/gengjiawen/node-github-workflow/runs/532947564)).
> 
> The 118M version is I build master using clang. What do I missing ? Compiler difference or V8 ?

Confirmed, it's compiler issue. Clang debug build just smaller.

**Comment by richardlau** [comment]
We discussed this in [today's Release WG meeting](https://github.com/nodejs/Release/pull/556) and the consensus of the Release WG is that this should first be attempted as an https://unofficial-builds.nodejs.org/ / https://github.com/nodejs/unofficial-builds/ project. 

@MylesBorins may be able to help with storage via Google credits.

**Comment by mmarchini** [comment]
> The 118M version is I build master using clang. What do I missing ? Compiler difference or V8 ?

Maybe clang (or clang on OS X) uses [DWARF5 Fission](https://gcc.gnu.org/wiki/DebugFission) by default, in which case the debug information would be found in separate files? Have you tried clang on Linux as well? What's the size of the out/Debug folder, compared to gcc result? Are there `.dwp` files in `out/Debug`?

TBH I wouldn't be surprised if clang just generates a more economic binary, but going from 1.2G to 103M just by changing the compiler (without changing other build flags) seems a bit unlikely.

**Comment by gengjiawen** [comment]
https://github.com/nodejs/Release/issues/555#issuecomment-603674509

This result is on linux.

**Comment by mmarchini** [comment]
Hum, interesting. OS X's clang is quite different from Linux, Apple has their own build and afaik they change some things. Wouldn't be surprised if they enabled DWARF5 Fission by default.

**Comment by gengjiawen** [comment]
The xz compress make it to 117M on linux, which is also very small compared to original size.

**Comment by mmarchini** [comment]
Sure. I'm just trying to understand why the binary on OS X is so much smaller :). That doesn't change how or if we should publish a debug build. I think it's unlikely that OS X compresses it though.

**Comment by gengjiawen** [comment]
> Maybe clang (or clang on OS X) uses DWARF5 Fission by default,

Can i use on linux for Node.js. I can give a try on https://github.com/gengjiawen/node-github-workflow/blob/master/.github/workflows/CI.yml to see the result.

**Comment by mmarchini** [comment]
Never tried to build Node.js with it, you'll probably need to change our gyp files to get it working. If you have access to the OS X machine from https://github.com/nodejs/Release/issues/555#issuecomment-603584301, you can use `find out/Debug -name "*.dsym"` or `find out/Debug -name "*.dwo"` to see if Apple's clang is splitting the debug info into another file.

**Comment by gengjiawen** [comment]
Is this the one ?
![image](https://user-images.githubusercontent.com/3759816/77812008-6bfa4780-70d9-11ea-9bac-92f47925dbe4.png)

**Comment by mmarchini** [comment]
Looks like it, yes. What's the size of this file? We probably need to publish it as well.

**Comment by gengjiawen** [comment]
> Looks like it, yes. What's the size of this file? We probably need to publish it as well.

```console
-rw-r--r--  1 daniel  staff   593M Mar 12 08:49 node
```

Can user use `out/Debug/node` to debug V8 symbol, or it has to be this one ?

**Comment by mmarchini** [comment]
Users can use `out/Debug/node`, but the information used by debuggers is stored on .dsym, so both should be published (afaik this is transparent for users though, they don't need to do anything special for debuggers to work). Maybe `make install` already copies .dsym files? Someone more familiar with OS X will be able to give a better answer.

**Comment by rvagg** [comment]
`xz -9` is worth trying too if you haven't already, will use a ton of RAM and be slow but will push it as far as it can
