### ISSUE TITLE
Document process of updating schedule

### ISSUE THREAD

**Issue by MylesBorins** [nodejs/Release#561]
We currently don't have this documented and I have to dig through past pr's to figure out how to update the SVG.

```bash
$ npx lts -s 2019-9-30 -e 2021-10-31 -d "$PWD/schedule.json" -g "$PWD/schedule.svg"
$ npx svgo "$PWD/schedule.svg"
```

I was thinking we should document this process somewhere or automate it with a script. Thoughts on how folks think we should do this

**Comment by richardlau** [comment]
Maybe via Actions when the schedule is pushed to the master branch? (and possibly on a chron to shift the time window shown?)
