### ISSUE TITLE
14.0.0 not marked as an LTS version in code?

### ISSUE THREAD

**Issue by shadowspawn** [nodejs/Release#571]
The code name (`fermium`) is not showing up in a couple of places:

- https://nodejs.org/en/about/releases/
- https://nodejs.org/download/release/index.tab

From looking at the code for building the [index](https://github.com/nodejs/nodejs-dist-indexer) and the [Release Process](https://github.com/nodejs/node/blob/19db0e60bdde8ce7cc120f4beddbddc002d92a32/doc/guides/releases.md#lts-releases), I think perhaps the `NODE_VERSION_LTS_CODENAME` macro has not been set.

https://github.com/nodejs/node/blob/v14.x/src/node_version.h

Reporting this because some applications use the `lts` column in `index.tab` to identify the lts versions, in particular of interest to me is `n`. 

```
$ n --lts
12.16.2
$ n lsr 14
Listing remote... Displaying 20 matches (use --all to see all).
14.0.0
```

(Happy to report this somewhere more appropriate if this is not the right place.)

**Comment by okuryu** [comment]
v14 is not LTS yet. It will be LTS from 2020-10-20.

**Comment by shadowspawn** [comment]
Oh sorry, got confused when heard 14 was available.
