### ISSUE TITLE
winget packages

### ISSUE THREAD

**Issue by bzoz** [nodejs/Release#587]
Microsoft recently created a package manager for Windows: [winget](https://docs.microsoft.com/en-us/windows/package-manager/winget/). The project is [open source](https://github.com/microsoft/winget-cli), so is the [package repository](https://github.com/microsoft/winget-pkgs) and there are [some Node.js installers added already](https://github.com/microsoft/winget-pkgs/tree/master/manifests/OpenJS/NodeJS). We should automate adding new packages.

We need to basically generate [a YAML file with link to the .msi and its SHA256](https://github.com/microsoft/winget-pkgs/blob/master/manifests/OpenJS/NodeJS/14.4.0.yaml).

We could use GitHub Actions - one that gets triggered by a new release in Node main repo or one fired when a new blog post with a new version is published on the nodejs.org webpage.

We could also add this to the [upload step of the `vcbuild.bat`](https://github.com/nodejs/node/blob/f645cc73185f1d690e82b01907e2c0da330a26de/vcbuild.bat#L455) or maybe there is some other better place for it.

Anyway, I'm more than happy to handle this, but I would like to know where you all feel this package generation would fit best.

/cc @nodejs/build

**Comment by MylesBorins** [comment]
I think an action triggered by a new tag would be a good place to start

**Comment by bzoz** [comment]
Running this when a tag is created sounds like the best option, but it looks like the tag is created before the installer is published. I don't think there is a way to get the SHA of the .msi before it is published.

That said, it looks like the GitHub release is usually made after the installer is published.

@targos @BethGriggs @codebytere you made the recent releases in https://github.com/nodejs/node/releases, could you confirm that those are done after the .msi was published on https://nodejs.org/dist/?

**Comment by BethGriggs** [comment]
Yes, correct. As per the [release guide](https://github.com/nodejs/node/blob/master/doc/guides/releases.md), it is expected that the promotion to nodejs.org happens before (Step 15) the release is created on GitHub (Step 18). If there is automation relying on that order, it would be worthwhile us adding a small note to Step 18 to check that the .msi is available.

**Comment by targos** [comment]
Note that the tag is pushed before promoting the binaries

**Comment by BethGriggs** [comment]
Closing, as I don't think there's anything for the Release Working group to action. I believe what needs to be done to achieve this is covered by https://github.com/nodejs/node/issues/38877 and https://github.com/nodejs/node/pull/34014.

(Feel free to comment/reopen if you disagree.)
