### ISSUE TITLE
Remnant of io.js fork, iojs user/group, used to create release tarballs

### ISSUE THREAD

**Issue by apaprocki** [nodejs/Release#604]
```
$ tar ztvf node-v14.8.0.tar.gz | head -1     
drwxr-xr-x iojs/iojs         0 2020-08-11 10:32 node-v14.8.0/
```
Should permanent releases transition off using a user/group of `iojs`?

**Comment by richardlau** [comment]
This comes from the build infrastructure -- we set up all CI machines (in both test and release CI with `iojs` user and group). I don't imagine there would be much enthusiasm for changing, but cc @nodejs/build.

**Comment by apaprocki** [comment]
For these archives, all that would really need to change is passing `--owner=nodejs --group=nodejs` to `tar`, not changing anything about the actual account used. I'm not sure if anything about the account name is preserved in the other types of artifacts.

**Comment by richardlau** [comment]
I think we'd still need a nodejs user and group on the machine generating the tarballs though?

**Comment by apaprocki** [comment]
GNU `tar` says when `--owner` and --group` are passed the format `<name>:<number>`, it does not attempt to resolve it against the system.

macOS `tar` says it explicitly does not verify `--gname <name>` or `--uname <name>` against the system.

Another option is to always explicitly force the values to zero.

**Comment by MylesBorins** [comment]
If this doesn't break anything I think it might be fine to keep. It is a fun little easter egg :P

**Comment by BethGriggs** [comment]
Closing as I don't believe we plan to change the ownership. Please feel free to reopen if you disagree.
