### ISSUE TITLE
Proposal: Slack channel for Release WG?

### ISSUE THREAD

**Issue by BethGriggs** [nodejs/Release#607]
Should we create a channel on the Node.js Slack for release-related matters?

I can see it being useful now that we have a larger pool of releasers to share information/provide a venue to ask for help/opinions.

**Comment by richardlau** [comment]
Sounds good to me.

**Comment by BethGriggs** [comment]
@MylesBorins created a #nodejs-release channel in the OpenJS Slack (https://openjs-foundation.slack.com/). I believe sign up is via https://slack-invite.openjsf.org.
