### ISSUE TITLE
Decleration Warning during curl -sL https://deb.nodesource.com/setup_8.x | sudo -E bash - on Ubuntu 18.4

### ISSUE THREAD

**Issue by justmejust** [nodejs/Release#612]
~$ curl -sL https://deb.nodesource.com/setup_8.x | sudo -E bash -

================================================================================
================================================================================

                              DEPRECATION WARNING                            

  Node.js 8.x LTS Carbon is no longer actively supported!

  You will not receive security or critical stability updates for this version.

  You should migrate to a supported version of Node.js as soon as possible.
  Use the installation script that corresponds to the version of Node.js you
  wish to install. e.g.

   * https://deb.nodesource.com/setup_10.x — Node.js 10 LTS "Dubnium"
   * https://deb.nodesource.com/setup_12.x — Node.js 12 LTS "Erbium" (recommended)
   * https://deb.nodesource.com/setup_14.x — Node.js 14 LTS "Fermium"

  Please see https://github.com/nodejs/Release for details about which
  version may be appropriate for you.
is that problem will effect the work ?
if so please update the command 
curl -sL https://deb.nodesource.com/setup_8.x | sudo -E bash -
to directly go to install the suitable version
thank you

**Comment by richardlau** [comment]
https://deb.nodesource.com/setup_8.x is nothing to do with the Node.js project. Please direct your question to https://github.com/nodesource/distributions.
