### ISSUE TITLE
Timeline for final 12.x semver-minor

### ISSUE THREAD

**Issue by MylesBorins** [nodejs/Release#616]
Hey All,

@codebytere is about to wrap up the 12.19.0 release and there are some modules PRs that are not yet ready to land yet. Some only went out last week, some will be going out tomorrow.

We had discussed that there would still be one last Minor... our schedule in fact had one more semver-patch and one more semver-minor before maintenance mode... but we also have a maintenance date of 2022-04-30.  I think we should keep to the original schedule and push out these releases, which in turn would extend the maintenance date by one month.

Due to a number of security releases we've had to delay shipping this minor, so it seems reasonable to me. It is also less than 14 days from the maintenance date so we are still within policy for this change.

With this in mind I think we should do a Semver-Patch on the 27th of October and a Semver-Minor on the 27th of November with a maintenance date of November 30th.

If anyone objects to this we may want to delay the 12.19.0 release so we can get the backlog of modules changes included.

Thoughts?

**Comment by BethGriggs** [comment]
Schedule updated in #618
