### ISSUE TITLE
Nominating @guybedford for the backporting team

### ISSUE THREAD

**Issue by MylesBorins** [nodejs/Release#657]
@guybedford has been very active in keeping the ESM implementation up to date across release lines and it would be great to  add him to the backporting team officially so that he manage things himself without needing to rely on other folks to land things.

**Comment by richardlau** [comment]
+1

**Comment by MylesBorins** [comment]
If there are no objections by Monday I'll go ahead and onboard Guy. I'll work with him to make sure he understands our process / policies and pair on some auditing sessions with him. Most likely he'll focus on specific subsystems (mostly ESM)

**Comment by mhdawson** [comment]
+1

**Comment by MylesBorins** [comment]
onboarded
