### ISSUE TITLE
Release plan - v16.x Maintenance

### ISSUE THREAD

**Issue by BethGriggs** [nodejs/Release#658]
_Draft schedule - all dates subject to change_

| Release Date  | Release                            | Releaser               | 
|----------------|------------------------|------------------|
|   2021-10-26 | v16.13.0 (LTS Transition) | @richardlau         |
|   2021-12-01 | v16.13.1                              | @BethGriggs | 
|   2022-01-10  | v16.13.2 | @danielleadams  |
|   2022-02-08  | v16.14.0 | @danielleadams  |
|   2022-03-08  | v16.14.1| @danielleadams |
|   2022-03-18  | v16.14.2| @richardlau  |
|   2022-04-xx  | v16.15.0 | @danielleadams  |
|   2022-06-01 | v16.15.1  | @BethGriggs  |
|   2022-07-07  | v16.16.0 (Security) |  @danielleadams |
|   2022-08-16  | v16.17.0 | @targos |
|   2022-09-23 | v16.17.1 (Security) | @ruyadorno |
|   2022-10-03  | v16.18.0 | @juanarbol |
|   2022-11-04 | v16.18.1 (Security) | @BethGriggs |
|   2022-12-13  | v16.19.0 | @richardlau |
|   2023-02-16  | v16.19.1 (Security) | @richardlau |
|   2023-03-29  | v16.20.0 |  @BethGriggs 
|   2023-06-20  | v16.20.1 (Security) | @RafaelGSS |
|   2023-08-09  | v16.20.2 (Security) | @RafaelGSS |
|   2023-08-xx  | v16.20.3 |  @richardlau  |

<details>
<summary>Current</summary>

| Release Date | Release              | Releaser            | 
|--------------|-----------------|----------------|
| 2021-04-20  | v16.0.0                | @BethGriggs    |
| 2021-05-04  | v16.1.0                | @targos             |
| 2021-05-19   | v16.2.0               | @targos             |
| 2021-06-02   | v16.3.0              | @danielleadams |
| 2021-06-23   | v16.4.0              | @danielleadams |
| 2021-07-01   | v16.4.1 (Security)              | @BethGriggs      |
| 2021-07-05   | v16.4.2              | @BethGriggs      |
|   2021-07-14 | v16.5.0              |   @targos             |
|   2021-07-29 | v16.6.0              | @BethGriggs      |
|   2021-08-03 | v16.6.1             | @targos      |
|   2021-08-11 | v16.6.2              | @BethGriggs (security) |
|   2021-08-17 | v16.7.0              | @danielleadams |
|   2021-08-25 | v16.8.0              |   @targos          |
|   2021-09-07 | v16.9.0              |   @targos          |
|   2021-09-10 | v16.9.1              | @richardlau      |
|   2021-09-22 | v16.10.0            | @BethGriggs    |
|   2021-10-08 | v16.11.0              | @danielleadams |
|   2021-10-12 | v16.11.1 (Security) | @danielleadams |
|   2021-10-20 | v16.12.0            | @richardlau        |
</details>

**Comment by Max4488** [comment]
> @knksmith57 ***

**Comment by knksmith57** [comment]
> > @knksmith57 ***

what's up @Max4488?

**Comment by danielleadams** [comment]
Contrary to what we discussed at the last Releasers meeting, I wasn't able to get 16.4.0 out on Thursday, so I'm going to push the schedule back 1 week for that release. And we should probably reflect rest of the schedule with the additional week.

**Comment by Divlo** [comment]
The schedule is wrong for the past releases.
Could someone update it, please? @danielleadams @BethGriggs 

I already updated the table :

| **Release Date** | **Release**    | **Releaser**   |
| ---------------- | -------------- | -------------- |
| 2021-04-20       | v16.0.0        | @BethGriggs    |
| 2021-05-04       | v16.1.0        | @targos        |
| 2021-05-19       | v16.2.0        | @targos        |
| 2021-06-02       | v16.3.0        | @danielleadams |
| 2021-06-23       | v16.4.0        | @danielleadams |
| 2021-06-29       | v16.x.x        | @BethGriggs    |
| 2021-07-13       | v16.x.x        |                |
| 2021-07-27       | v16.x.x        |                |
| 2021-08-10       | v16.x.x        |                |
| 2021-08-24       | v16.x.x        |                |
| 2021-09-07       | v16.x.x        |                |
| 2021-09-21       | v16.x.x        |                |
| 2021-10-05       | v16.x.x        |                |
| 2021-10-19       | v16.x.x        |                |
| 2021-10-26       | LTS Transition |                |

In Markdown, it looks like this :
```md
| **Release Date** | **Release**    | **Releaser**   |
| ---------------- | -------------- | -------------- |
| 2021-04-20       | v16.0.0        | @BethGriggs    |
| 2021-05-04       | v16.1.0        | @targos        |
| 2021-05-19       | v16.2.0        | @targos        |
| 2021-06-02       | v16.3.0        | @danielleadams |
| 2021-06-23       | v16.4.0        | @danielleadams |
| 2021-06-29       | v16.x.x        | @BethGriggs    |
| 2021-07-13       | v16.x.x        |                |
| 2021-07-27       | v16.x.x        |                |
| 2021-08-10       | v16.x.x        |                |
| 2021-08-24       | v16.x.x        |                |
| 2021-09-07       | v16.x.x        |                |
| 2021-09-21       | v16.x.x        |                |
| 2021-10-05       | v16.x.x        |                |
| 2021-10-19       | v16.x.x        |                |
| 2021-10-26       | LTS Transition |                |
```

> And we should probably reflect rest of the schedule with the additional week.

Yes, we should postpone all the next releases to one week. :+1: 
I didn't do that yet for the new table.

**Comment by BethGriggs** [comment]
Updated. I'd prefer to keep the schedule as is rather than move all the future dates out - I can make a call next week whether there's enough to warrant a release so soon or skip.

**Comment by targos** [comment]
@BethGriggs I added myself to July 13, but I'm also available on the other one, in case you prefer that date.

**Comment by danielleadams** [comment]
I picked up the August releases, but happy to swap if anyone needs/wants to.

**Comment by danielleadams** [comment]
Pushed back tomorrow's to 8/17.

**Comment by danielleadams** [comment]
In case anyone shows up here wondering where 16.15.0 is, I'm working on it, but hung up on pulling in https://github.com/nodejs/node/pull/36328. It landed fine with minor merge conflicts, but it broke tests that don't appear to be related to the change.

This release won't be out tomorrow but hoping to get it at least prepared by tomorrow and released by Thursday.

**Comment by timescodex** [comment]
@BethGriggs  is there some new schedule for v16.15.0 LTS?

**Comment by danielleadams** [comment]
Following up here - a backport has been opened for https://github.com/nodejs/node/pull/42726 (https://github.com/nodejs/node/pull/42726), but 16.15.0 won't be ready for tomorrow.

**Comment by targos** [comment]
The staging branch for v16.17.0 is almost ready. I'm aiming the release for 2022-08-16.

**Comment by juanarbol** [comment]
The v16.18.0 will have a delay to Monday 03 of October due to many conflicts and work stuff

**Comment by richardlau** [comment]
Node.js 16 reaches End-of-Life in a few weeks on 11 September 2023. I've been looking at [open PRs for v16.x](https://github.com/nodejs/node/pulls?q=is%3Apr+label%3Av16.x+is%3Aopen+) as well as[ closed PR's labelled `lts-watch-v16.x`](https://github.com/nodejs/node/pulls?q=is%3Apr+label%3Alts-watch-v16.x+is%3Aclosed).

I've cherry-picked a commit to fix the V8 CI for Node.js 16, plus two root certificate updates which at first glance appear to be the only notable reason for doing another Node.js 16 release.

We have three open PRs:
title|PR|notes
---|---|---
[v16.x] build, deps, tools: avoid excessive LTO, PGO, debug information | https://github.com/nodejs/node/pull/49066 | Draft. https://github.com/nodejs/node/pull/49063 has not yet landed on `main`.
[v16.x] doc: include git add -f to include folder | https://github.com/nodejs/node/pull/49004 | I don't think this is necessary if following the instructions in the maintenaning OpenSSL guide.
[v16.x backport] deps: update corepack to 0.18.1 | https://github.com/nodejs/node/pull/47337 | corepack is experimental. Current version of corepack in v16.x is 0.17.0 (and main is on 0.19.0).

And lts-watch-v16.x labelled:
title|PR|notes
---|---|---
Add auto to docs' contain-intrinsic-size decl, to prevent jitter/flicker | https://github.com/nodejs/node/pull/48195
url: do not use object as hashmap | https://github.com/nodejs/node/pull/47415
esm: add a runtime warning when using import assertions | https://github.com/nodejs/node/pull/46901
child_process: validate arguments for null bytes | https://github.com/nodejs/node/pull/44782
tools: fix duration_ms to be milliseconds | https://github.com/nodejs/node/pull/44490 
src,lib: print source map error source on demand | https://github.com/nodejs/node/pull/43875 | Labelled baking-for-lts
