### ISSUE TITLE
Node.js releasers email alias?

### ISSUE THREAD

**Issue by BethGriggs** [nodejs/Release#663]
Should we create a Node.js releasers email alias? I think it'd be useful when coordinating security releases where we sometimes need to source volunteers more urgently.

My thoughts were that we'd create an alias for @nodejs/releasers based on the emails in the Node.js README. 

Are there any concerns around creating the alias/would anyone prefer not be included on the alias? Open to other suggestions too.

**Comment by richardlau** [comment]
No objections from me.

**Comment by targos** [comment]
I won't object to it, but I generally dislike discussions that happen by email.

**Comment by MylesBorins** [comment]
We do have this discussion board https://github.com/orgs/nodejs/teams/releasers

**Comment by danielleadams** [comment]
I'm in favor of email for more urgent concerns.

**Comment by danielleadams** [comment]
@BethGriggs Do you think the Security Slack group covers the use case for the email alias? If so, can we close this?
