### ISSUE TITLE
Nominating myself for citgm-admins team

### ISSUE THREAD

**Issue by targos** [nodejs/Release#668]
I'd like to be able to make small changes to the CITGM Jenkins jobs.

See https://github.com/nodejs/build/issues/2643#issuecomment-832587200

The team currently has three members:
![image](https://user-images.githubusercontent.com/2352663/117663118-95bce380-b1a0-11eb-93b9-49b0c23fef3a.png)

**Comment by targos** [comment]
@nodejs/release

**Comment by MylesBorins** [comment]
+1 from me.

Added.
