### ISSUE TITLE
Truncating Pull Request text for large releases

### ISSUE THREAD

**Issue by danielleadams** [nodejs/Release#670]
The Changelog that had been copy and pasted to the PR description for v14.17.0 [here](https://github.com/nodejs/node/pull/38507) was extensive. Presumably, because of this, comments were getting lost, and it became difficult to update the PR the description.

Could we truncate the Changelog for large releases to ensure comments don't get lost? Or is the Changelog important enough that we want the entirety of the text there?

**Comment by BethGriggs** [comment]
I think(?) the benefit of pasting them in is for the mention/reference links in the individual PRs (like the '_ mentioned this pull request 16 days ago in v14.17.0 proposal' in https://github.com/nodejs/node/pull/36755). I still tend to find those references quite useful. Maybe we could post commit lists that exceed the limit as separate comments? We could also consider hiding the longer commit lists under `<details>` sections (assuming that preserves the references)?

**Comment by danielleadams** [comment]
Yeah, I can investigate this and maybe modify guides for noticeable issues. I'll follow up.

**Comment by danielleadams** [comment]
Made a PR for this here: https://github.com/nodejs/node/pull/39186

**Comment by danielleadams** [comment]
Fixed in https://github.com/nodejs/node/commit/223625a0b944ebe540f3448e42c945ccc2b4a4d5
