### ISSUE TITLE
Backport clarification - pattern trailers

### ISSUE THREAD

**Issue by guybedford** [nodejs/Release#690]
I'd like to request some backporting guidance on https://github.com/nodejs/node/pull/39635 as to whether it would be possible to backport this to the 12.x branch.

The reason why this requires clarification is because, strictly speaking, it is a minor change as it extends the ESM resolver to support `"exports"` field mappings like `"./*.js": "./dist/*.js"` whereas previously we only supported `"./*": "./dist/*"` mappings with the `*` always being at the end of the match key on the left.

I'm opening discussion here because if it were possible to backport this PR that would allow us to update our package guidelines sooner for package authors to encourage the new form as a best-practise whereas otherwise we would have to wait until 12 EOL until that could happen (although not that long away either now!).

Thoughts or feedback either way on this would be a great help to understand the best route forward here.

**Comment by MylesBorins** [comment]
I'm waffling on this one. It is a non-trivial feature and it isn't yet battle tested. If we were to backport I'd want to see more usage on 16, a backport to 14, and no major issues first

**Comment by MylesBorins** [comment]
The only thing that I'd point out is that this change is Semver-Minor... so it probably should go out in 14.19.0

**Comment by BethGriggs** [comment]
It looks like this was shipped on Node.js 14 (v14.19.0). We now have no further minor releases scheduled for Node.js 12. And, with only ~2 months left before Node.js 12 goes End-of-Life IMO the impact of backporting is reduced.

If there's now general agreement that we shouldn't ship on Node.js 12, I think this can be closed.
