### ISSUE TITLE
Many missing files in header archive for v17.0.0

### ISSUE THREAD

**Issue by kriszyp** [nodejs/Release#704]
When trying to compile native packages, compiling the v8 include headers fails due to missing header files, including v8-weak-callback-info.h, v8-function-callback.h, v8-callbacks.h, and others. The headers download at https://nodejs.org/dist/v17.0.0/node-v17.0.0-headers.tar.gz does not include all the headers referenced by the included v8 headers. Here is an example compilation error:

```
c:\users\...\appdata\local\node-gyp\cache\17.0.0\include\node\v8-function.h(11): fatal error C1083: Cannot open inclu
de file: 'v8-function-callback.h': No such file or directory (compiling source file ..\src\node-lmdb.cpp) [C:\dev\lmdb-
store\build\lmdb-store.vcxproj]
```

I assume V8 9.5 had some refactoring, splitting up some header files, and the new headers just need to be included header archive.

**Comment by richardlau** [comment]
Refs https://github.com/nodejs/node/pull/40423. cc @targos
