### ISSUE TITLE
v14 maintenance start is today but v16 doesn't become LTS till 26th

### ISSUE THREAD

**Issue by nschonni** [nodejs/Release#705]
Just noticed a gap when generating out the Docker images for 17, since we use these dates to create the tag.
Should the maintenance start be adjusted for 14 to match the updated 16 LTS date?

**Comment by targos** [comment]
Why does it matter?

**Comment by targos** [comment]
Could you point to the logic that determines what is the "current" LTS ?

**Comment by BethGriggs** [comment]
Can this be closed now? It doesn't appear there's an action or further discussion needed, but I didn't want to assume.
