### ISSUE TITLE
Move to monthly Release WG meetings?

### ISSUE THREAD

**Issue by BethGriggs** [nodejs/Release#711]
We've been running the Release WG meetings on two-weekly basis for a while. I've found we've regularly cancelled due to a light agenda or not enough attendees. So, I'd like to propose we move to a monthly meeting.

I also think this cadence would align with our typical release cadence - current releases are mostly routine and involve less discussion, whereas Active LTS are monthly and we tend to discuss those more. We can use the meeting to discuss/schedule the following month's releases.

If members agree, I propose we meet as scheduled on 2nd December and then meet monthly from January. If needed, we can do a new Doodle over December to find a new time for January onwards.

(note: still plan to schedule some separate onboarding sessions)

**Comment by BethGriggs** [comment]
cc: @nodejs/release

**Comment by danielleadams** [comment]
SGTM 👍🏼

**Comment by BethGriggs** [comment]
I have updated the Zoom webinar and Node.js calendar. The next meeting is on 13th January 2022 with the meeting is set to reoccur every 4 weeks. For now, I have just used the same day and time. If there is desire to move the day or time please let me know and I'll arrange a Doodle poll.
