### ISSUE TITLE
Private Slack group?

### ISSUE THREAD

**Issue by danielleadams** [nodejs/Release#720]
I know we like transparency, but for the purposes of closed working group conversations - should we consider creating a private Slack group on the OpenJS Slack?

**Comment by danielleadams** [comment]
I know we discussed https://github.com/nodejs/Release/issues/663 (email group) too, so maybe we could discuss moving forward on a solution for one of these.

**Comment by Trott** [comment]
Based on Slack conversations with @BethGriggs and @danielleadams, maybe it makes sense to add the active security releasers to the private security triage channel.

**Comment by BethGriggs** [comment]
> Based on Slack conversations with @BethGriggs and @danielleadams, maybe it makes sense to add the active security releasers to the private security triage channel.

+1. Most (almost all?) private release discussions are regarding security releases, which often involve a lot of interaction with the security stewards/those involved in the triage.

**Comment by mhdawson** [comment]
+1 from me

**Comment by BethGriggs** [comment]
Releasers that have been involved in recent security releases have been added to `#nodejs-security-triage` in the OpenJS Slack. I believe this resolves the need for us to have a dedicated private Slack group as almost all of our private discussions are coordinating security releases.
