### ISSUE TITLE
Onboarding bengl as a releaser

### ISSUE THREAD

**Issue by BethGriggs** [nodejs/Release#730]
@bengl has prepared their first release (https://github.com/nodejs/node/pull/42072) 🎉

We now need to complete the remaining onboarding actions (from [GOVERNANCE.md](https://github.com/nodejs/Release/blob/main/GOVERNANCE.md#adding-new-releasers)):

- [x] Be added to the GitHub [releasers team](https://github.com/orgs/nodejs/teams/releasers) in the Node.js org (grants ci-release access)
- [x] Be added to the GitHub [security-release team](https://github.com/orgs/nodejs/teams/security-release) in the Node.js and nodejs-private orgs
- [x] Have a single, high quality SSH key added to the "dist" user on the primary www server
- [x] Have a GPG key added to the nodejs/node [README.md](https://github.com/nodejs/node/#release-team)
  - The key should be cherry-picked to all active release branches.
- [x] Open a PR in [nodejs/docker-node](https://github.com/nodejs/docker-node/) to add gpg key to [node.keys](https://github.com/nodejs/docker-node/blob/master/keys/node.keys)
- [x] Add the key to https://github.com/nodejs/release-keys

**Comment by bengl** [comment]
PR for nodejs/node README https://github.com/nodejs/node/pull/42102

**Comment by BethGriggs** [comment]
@bengl has promoted their first release 🎉
