### ISSUE TITLE
New meeting host

### ISSUE THREAD

**Issue by BethGriggs** [nodejs/Release#740]
Would anyone like to take over hosting the monthly Release WG meetings?

(somewhat refs: https://github.com/nodejs/Release/pull/738)

**Comment by ruyadorno** [comment]
I might be able to start hosting them as part of my 20% time in my new role, I'll be there next Thursday and we can chat more about it.

**Comment by ruyadorno** [comment]
Since I agreed to take over hosting and I'm finally all set up with the accesses I guess we can remove this from the agenda / close it now.
