### ISSUE TITLE
Onboarding @RafaelGSS as a releaser

### ISSUE THREAD

**Issue by BethGriggs** [nodejs/Release#747]
Onboarding actions (from [GOVERNANCE.md](https://github.com/nodejs/Release/blob/main/GOVERNANCE.md#adding-new-releasers)):

- [x] @RafaelGSS to prepare a release (promoted by an existing releaser)
- [x] Be added to the GitHub [releasers team](https://github.com/orgs/nodejs/teams/releasers) in the Node.js org (grants ci-release access)
  - [x] Added to backporters team
- [x] Be added to the GitHub [security-release team](https://github.com/orgs/nodejs/teams/security-release) in the Node.js and nodejs-private orgs
- [x] Have a single, high quality SSH key added to the "dist" user on the primary www server
- [x] Have a GPG key added to the nodejs/node [README.md](https://github.com/nodejs/node/#release-team)
  - The key should be cherry-picked to all active release branches.
  - [x] Open a PR in [nodejs/docker-node](https://github.com/nodejs/docker-node/) to add gpg key to [node.keys](https://github.com/nodejs/docker-node/blob/master/keys/node.keys) (nodejs/docker-node#1723)
  - [x] Add the key to https://github.com/nodejs/release-keys (https://github.com/nodejs/release-keys/pull/16)

**Comment by RafaelGSS** [comment]
I think it can be closed now :tada:
