### ISSUE TITLE
Add codename `Hydrogen` for node 18 to `README.md` and `schedule.json` file 

### ISSUE THREAD

**Issue by HonkingGoose** [nodejs/Release#770]
The `CODENAMES.md` file says that version `18.x` has the Codename `Hydrogen`: https://github.com/nodejs/Release/blob/0f3230611ebcae7488e55ad1fffdf989a787a983/CODENAMES.md?plain=1#L11

But these files don't list the `Hydrogen` codename for to the `18.x` release:

https://github.com/nodejs/Release/blob/0f3230611ebcae7488e55ad1fffdf989a787a983/README.md?plain=1#L9

https://github.com/nodejs/Release/blob/0f3230611ebcae7488e55ad1fffdf989a787a983/schedule.json#L98-L104

**Comment by HonkingGoose** [comment]
Oh, I see Node 18.x is not yet released as stable LTS. Is that's why it doesn't have a codename in _all_ the files?

**Comment by richardlau** [comment]
> Oh, I see Node 18.x is not yet released as stable LTS. Is that's why it doesn't have a codename in _all_ the files?

Correct. The codename only applies once the release has become LTS.

**Comment by HonkingGoose** [comment]
Fixed by commit: https://github.com/nodejs/Release/commit/7277c242ca98cf3eb12b4e0c479ec5a5834f02a0
