### ISSUE TITLE
It suspects that "2022Jan" in the timeline is incorrect and "2023Jan" is correct.

### ISSUE THREAD

**Issue by snaka** [nodejs/Release#798]
![image](https://user-images.githubusercontent.com/19329/200476560-b6af62b0-b07b-4715-952a-9fb63d2047d1.png)

**Comment by snaka** [comment]
Ah, now I see that `2023Jan` and `2024Jan` are the same.
Is this intentional?

**Comment by nschonni** [comment]
It's `Oct 2022` and `Jan 2023`. Eg. MMM YYYY format

**Comment by snaka** [comment]
Oh I see, I misunderstood.
Thank you!
