### ISSUE TITLE
No more scheduled meetings?

### ISSUE THREAD

**Issue by richardlau** [nodejs/Release#812]
Looking at the [Node.js Project Calendar](https://nodejs.org/calendar) it looks like we don't have any further Release WG meetings scheduled.

**Comment by targos** [comment]
When should be the next meeting if we follow the cadence?

**Comment by ruyadorno** [comment]
I believe it used to be monthly? Second Thursday of each month, or something similar 🤔 

@mhdawson are you able to help us out here? We could start by setting up meetings second Thursday of each month (starting next Thursday, 12 January and forward) and adjust it later if needed.

**Comment by mhdawson** [comment]
I added it to the calendar.

**Comment by BethGriggs** [comment]
It used to be at a 4 week intervals to keep it in an 'off week' of the Security WG - which meets at our usual time slot every other week. 

(Unfortunately, it looks like next week will now also clash with the Build WG, which would impact streaming and ability to attend.)

**Comment by richardlau** [comment]
> (Unfortunately, it looks like next week will now also clash with the Build WG, which would impact streaming and ability to attend.)

As far as I know we shouldn't have any build WG meetings on Thursdays -- @mhdawson did you mislabel the newly created entries for the Release WG?

**Comment by mhdawson** [comment]
Oops meant to have it be release sorry about that updated

**Comment by ruyadorno** [comment]
TODO: We need to make sure the meeting goes back to its previous 4-week cadence. Make sure the zoom link is included in the calendar invite.

**Comment by richardlau** [comment]
This has been fixed. The Zoom link is in the calendar invite and meetings are set on a four week cadence.
