### ISSUE TITLE
Proposal: `notable-changes` bot comment for summaries

### ISSUE THREAD

**Issue by BethGriggs** [nodejs/Release#821]
Something I've been thinking about for a while is extending the bot to add a comment whenever the notable changes label is added to a PR in `nodejs/node`. I haven't tried crafting it, but I'm assuming it'd be possible to implement.

The comment would say something like:

> The `notable-changes` label has been added by _@user.
>
> Please include your text below if you'd like to include a more detailed summary in the changelog.
> ```md
> [Insert here]
> ```

Why?
 * Releasers don't always have the context to expand on the notable changes - the author(s) are best placed to write these and determine if more detail is warranted.
 * Having the notable changes proposed in the PR rather than the release proposal means the text will be consistent between release lines by default.
 * Potential to extend our release preparation tooling to automatically pick-up the supplied text.
 
 Proposing this here first to see if @nodejs/release thinks it's a good idea. We'll likely need to propose it more widely.

**Comment by targos** [comment]
I think it's a very good idea!

**Comment by RafaelGSS** [comment]
strong +1

**Comment by mhdawson** [comment]
+1 from me, sounds like a good idea :)
