### ISSUE TITLE
I can't find the setup file for version 15.14.0 for platform win x64

### ISSUE THREAD

**Issue by giampq** [nodejs/Release#834]
Hi team and everyone
Currently, I can't find the setup file for version 15.14.0 for platform win x64
https://nodejs.org/dist/v15.14.0/win-x64/

<img width="1169" alt="Screenshot 2023-03-16 at 21 14 36" src="https://user-images.githubusercontent.com/16837400/225644771-f22ba3b8-ebbb-40d5-843a-beedf229a9ae.png">

Please help me review that
Thank

**Comment by mstratis-gr** [comment]
I'm also seeing a 404 with the following:
https://nodejs.org/dist/v14.21.2/node-v14.21.2-linux-x64.tar.gz

**Comment by tniessen** [comment]
Please see https://github.com/nodejs/nodejs.org/issues/5149#issuecomment-1472659075. Depending on your physical location and depending on which particular file you are attempting to access, you might see unexpected 404 status codes. We expect this to be resolved as we manually purge the cache for popular URLs, which takes a few minutes. The remaining URLs should be resolved within a few hours.
