### ISSUE TITLE
Session at the Collaborator Summit

### ISSUE THREAD

**Issue by ruyadorno** [nodejs/Release#880]
There's a Node.js Collaborator Summit coming up September 18th in Spain. (ref: https://github.com/openjs-foundation/summit/issues/360)

Should we submit a session this time? Are there any @nodejs/releasers planning to participate this time around?

**Comment by johnpaul02191981** [comment]
> There's a Node.js Collaborator Summit coming up September 18th in Spain. (ref: [openjs-foundation/summit#360](https://github.com/openjs-foundation/summit/issues/360))
> 
> Should we submit a session this time? Are there any @nodejs/releasers planning to participate this time around?

**Comment by johnpaul02191981** [comment]
> There's a Node.js Collaborator Summit coming up September 18th in Spain. (ref: [openjs-foundation/summit#360](https://github.com/openjs-foundation/summit/issues/360))
> 
> Should we submit a session this time? Are there any @nodejs/releasers planning to participate this time around?



> There's a Node.js Collaborator Summit coming up September 18th in Spain. (ref: [openjs-foundation/summit#360](https://github.com/openjs-foundation/summit/issues/360))
> 
> Should we submit a session this time? Are there any @nodejs/releasers planning to participate this time around?

**Comment by ruyadorno** [comment]
> I won't be on site, but I can probably join remotely.

That brings up a good point, last time the setup was 1-way only for remote participants (no way for remote participants to interact). I'll try to find out if we're going to be repeating the same kind of setup this time.

**Comment by richardlau** [comment]
I will not be attending in person. I could also probably participate remotely.

**Comment by ruyadorno** [comment]
Update from the session today (https://github.com/nodejs/Release/issues/886): We might end up not submitting a session this time around.

**Comment by ruyadorno** [comment]
Thanks @RafaelGSS for cleaning this up! 

To confirm to anyone else that may find this issue in the future, the group has decided not to host a session in the Bilbao Collaborator Summit 2023 since we're not going to have enough (or any?) collaborator there.
