### ISSUE TITLE
Releaser for v21.X

### ISSUE THREAD

**Issue by mhdawson** [nodejs/Release#903]
Talking with @richardlau a few minutes ago it sounds like we don't have a volunteer yet and there is no other issue for discussing how we figure that out. Creating this issue to make sure there is discussion as I think it might be getting close to when work usually starts for a major.

Tagging with release agenda so that it shows up on the agenda for the next release meeting.

**Comment by RafaelGSS** [comment]
I propose to do it in pairs. I can take one slot.

**Comment by targos** [comment]
I might be able to help on this one, but do we already have a date for it? `schedule.json` stops at v20.

**Comment by mhdawson** [comment]
@targos based on past plans I think it should be on Tuesday Oct 17, 2023

**Comment by targos** [comment]
Perfect. I can make that release with you @RafaelGSS
