### ISSUE TITLE
Broken Ubuntu focal (20.04) .deb repository (`Package not found`)?

### ISSUE THREAD

**Issue by eguaj** [nodejs/Release#904]
Hi,

It looks like the Ubuntu focal repo (`deb https://deb.nodesource.com/node_16.x focal main`) is broken and the NodeJS (e.g. v16) package cannot be found anymore:

```
$ cat /etc/apt/sources.list.d/nodesource.list
deb https://deb.nodesource.com/node_16.x focal main
# deb-src https://deb.nodesource.com/node_16.x focal main

$ sudo apt-get install -V nodejs
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following NEW packages will be installed:
   nodejs (16.20.2-deb-1nodesource1)
0 upgraded, 1 newly installed, 0 to remove and 0 not upgraded.
Need to get 27.2 MB of archives.
After this operation, 128 MB of additional disk space will be used.
Err:1 https://deb.nodesource.com/node_16.x focal/main amd64 nodejs amd64 16.20.2-deb-1nodesource1
  404  Not Found [IP: 172.67.10.205 443]
E: Failed to fetch https://deb.nodesource.com/node_16.x/pool/main/n/nodejs/nodejs_16.20.2-deb-1nodesource1_amd64.deb  404  Not Found [IP: 172.67.10.205 443]
E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?
```

Running the `apt-get update --fix-missing` does not fix de problem.

The problem seems to be that the [`Packages`](https://deb.nodesource.com/node_16.x/dists/focal/main/binary-amd64/Packages) repository index file references a .deb package [`pool/main/n/nodejs/nodejs_16.20.2-deb-1nodesource1_amd64.deb`](https://deb.nodesource.com/node_16.x/pool/main/n/nodejs/nodejs_16.20.2-deb-1nodesource1_amd64.deb) that does not exists:

```
$ curl -sL https://deb.nodesource.com/node_16.x/dists/focal/main/binary-amd64/Packages | grep '^Filename'
Filename: pool/main/n/nodejs/nodejs_16.20.2-deb-1nodesource1_amd64.deb
```

Here, we see that the `Packages` index references the .deb package at `pool/main/n/nodejs/nodejs_16.20.2-deb-1nodesource1_amd64.deb`.

But when  we fetch the .deb, we get a HTTP 404 error:

```
$ curl -I https://deb.nodesource.com/node_16.x/pool/main/n/nodejs/nodejs_16.20.2-deb-1nodesource1_amd64.deb
HTTP/2 404 
date: Wed, 30 Aug 2023 14:19:54 GMT
content-type: application/octet-stream
content-length: 158350
last-modified: Tue, 29 Aug 2023 15:45:05 GMT
etag: "c0888f549b391935a19b541e6699944c"
x-amz-error-code: NoSuchKey
x-amz-error-message: The specified key does not exist.
x-amz-error-detail-key: node_16.x/pool/main/n/nodejs/nodejs_16.20.2-deb-1nodesource1_amd64.deb
[...]
```

However, if I remove de `-deb` in the `nodejs_16.20.2-deb-1nodesource1_amd64.deb` filename, then the ressource exists and returns a HTTP 200:

```
$ curl -I https://deb.nodesource.com/node_16.x/pool/main/n/nodejs/nodejs_16.20.2-1nodesource1_amd64.deb
HTTP/2 200 
date: Wed, 30 Aug 2023 14:19:58 GMT
content-type: application/octet-stream
content-length: 27528856
[...]
```

It seems the `Packages` index is not consistent with the filenames of the binary .deb package in the pool?

I also saw that you are now recommending to use the repo from `deb https://deb.nodesource.com/node_16.x nodistro main` instead.

If I switch to this new repository, then I can install NodeJS v16.

Is this the expected behaviour (regarding clients configured with the "old" repo)? Should I consider the "old" repo (`deb https://deb.nodesource.com/node_16.x focal main`) as invalid and migrate my servers to use the new repo? Or the "old" repo is expected to be working?

Regards,
Jérôme

**Comment by richardlau** [comment]
You'll need to file your issue with https://github.com/nodesource/distributions as that package repository is external to the Node.js project.

**Comment by eguaj** [comment]
Oops, sorry for the noise :(

I'll check the nodesource project instead. Thanks.

**Comment by Zackyong70** [comment]
> Hi,
> 
> It looks like the Ubuntu focal repo (`deb https://deb.nodesource.com/node_16.x focal main`) is broken and the NodeJS (e.g. v16) package cannot be found anymore:
> 
> ```
> $ cat /etc/apt/sources.list.d/nodesource.list
> deb https://deb.nodesource.com/node_16.x focal main
> # deb-src https://deb.nodesource.com/node_16.x focal main
> 
> $ sudo apt-get install -V nodejs
> Reading package lists... Done
> Building dependency tree       
> Reading state information... Done
> The following NEW packages will be installed:
>    nodejs (16.20.2-deb-1nodesource1)
> 0 upgraded, 1 newly installed, 0 to remove and 0 not upgraded.
> Need to get 27.2 MB of archives.
> After this operation, 128 MB of additional disk space will be used.
> Err:1 https://deb.nodesource.com/node_16.x focal/main amd64 nodejs amd64 16.20.2-deb-1nodesource1
>   404  Not Found [IP: 172.67.10.205 443]
> E: Failed to fetch https://deb.nodesource.com/node_16.x/pool/main/n/nodejs/nodejs_16.20.2-deb-1nodesource1_amd64.deb  404  Not Found [IP: 172.67.10.205 443]
> E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?
> ```
> 
> Running the `apt-get update --fix-missing` does not fix de problem.
> 
> The problem seems to be that the [`Packages`](https://deb.nodesource.com/node_16.x/dists/focal/main/binary-amd64/Packages) repository index file references a .deb package [`pool/main/n/nodejs/nodejs_16.20.2-deb-1nodesource1_amd64.deb`](https://deb.nodesource.com/node_16.x/pool/main/n/nodejs/nodejs_16.20.2-deb-1nodesource1_amd64.deb) that does not exists:
> 
> ```
> $ curl -sL https://deb.nodesource.com/node_16.x/dists/focal/main/binary-amd64/Packages | grep '^Filename'
> Filename: pool/main/n/nodejs/nodejs_16.20.2-deb-1nodesource1_amd64.deb
> ```
> 
> Here, we see that the `Packages` index references the .deb package at `pool/main/n/nodejs/nodejs_16.20.2-deb-1nodesource1_amd64.deb`.
> 
> But when we fetch the .deb, we get a HTTP 404 error:
> 
> ```
> $ curl -I https://deb.nodesource.com/node_16.x/pool/main/n/nodejs/nodejs_16.20.2-deb-1nodesource1_amd64.deb
> HTTP/2 404 
> date: Wed, 30 Aug 2023 14:19:54 GMT
> content-type: application/octet-stream
> content-length: 158350
> last-modified: Tue, 29 Aug 2023 15:45:05 GMT
> etag: "c0888f549b391935a19b541e6699944c"
> x-amz-error-code: NoSuchKey
> x-amz-error-message: The specified key does not exist.
> x-amz-error-detail-key: node_16.x/pool/main/n/nodejs/nodejs_16.20.2-deb-1nodesource1_amd64.deb
> [...]
> ```
> 
> However, if I remove de `-deb` in the `nodejs_16.20.2-deb-1nodesource1_amd64.deb` filename, then the ressource exists and returns a HTTP 200:
> 
> ```
> $ curl -I https://deb.nodesource.com/node_16.x/pool/main/n/nodejs/nodejs_16.20.2-1nodesource1_amd64.deb
> HTTP/2 200 
> date: Wed, 30 Aug 2023 14:19:58 GMT
> content-type: application/octet-stream
> content-length: 27528856
> [...]
> ```
> 
> It seems the `Packages` index is not consistent with the filenames of the binary .deb package in the pool?
> 
> I also saw that you are now recommending to use the repo from `deb https://deb.nodesource.com/node_16.x nodistro main` instead.
> 
> If I switch to this new repository, then I can install NodeJS v16.
> 
> Is this the expected behaviour (regarding clients configured with the "old" repo)? Should I consider the "old" repo (`deb https://deb.nodesource.com/node_16.x focal main`) as invalid and migrate my servers to use the new repo? Or the "old" repo is expected to be working?
> 
> Regards, Jérôme

#
