### ISSUE TITLE
Release volunteer

### ISSUE THREAD

**Issue by krk** [nodejs/Release#936]
Hi! I would like to volunteer for the release team by becoming a releaser.

**Comment by RafaelGSS** [comment]
Hey, @krk! Sorry for the delay.

We've discussed internally (nodejs/releasers) and per policy is expected that a releaser will either be a existing collaborator or soon to be nominated. So, given the fact you aren't a Node.js collaborator nor an active participant in any of our working groups, your nomination will require more time to be, eventually, approved.

Meanwhile, I highly suggest you keep participating in the calls, helping with backports when needed, and being more active in general (most of us are active in the OpenJS Slack). Note that this isn't a "rejected" but an on-hold nomination.

**Comment by srcn35** [comment]
Ne amk ne bu

11 Kas 2023 Cmt, saat 03:17 tarihinde Rafael Gonzaga <
***@***.***> şunu yazdı:
