### ISSUE TITLE
Releaser for Node.js 22

### ISSUE THREAD

**Issue by richardlau** [nodejs/Release#985]
Node.js 22 is due next month https://github.com/nodejs/Release/blob/220e53361aa0e8832e88c783929ead2a77a55840/schedule.json#L122-L123

We need volunteer(s) to help prepare/do the release.

cc @nodejs/releasers

**Comment by richardlau** [comment]
In today's WG meeting @marco-ippolito volunteered to help preparation and there were other expressions of interest to help out.

**Comment by marco-ippolito** [comment]
I would be available to volunteer

**Comment by marco-ippolito** [comment]
I can start preparing the labels:
```
v22.x
backport-blocked-v22.x
backport-open-v22.x
backport-requested-v22.x
backported-to-v22.x
dont-land-on-v22.x
```

**Comment by marco-ippolito** [comment]
As mention by the doc:
```
A draft release proposal should be created 6 weeks before the release.
```
Which is this week.
May I proceed with creating the proposal branch `v22.0.0-proposal`?

**Comment by mhdawson** [comment]
@marco-ippolito is there any current blockers for you? Just checking in since we are only a few weeks away from the release.

**Comment by marco-ippolito** [comment]
> @marco-ippolito is there any current blockers for you? Just checking in since we are only a few weeks away from the release.

No, me and @RafaelGSS are working on it, afaik he is creating the proposal

**Comment by targos** [comment]
It happened. Thank you @marco-ippolito and @RafaelGSS !
