### ISSUE TITLE
Onboarding @aduh95 as a releaser

### ISSUE THREAD

**Issue by ruyadorno** [nodejs/Release#999]
After our meeting session at the Node.js Collaborator Summit at London 2024, @aduh95 reached out to participate in the Releaser Team :tada:

Onboarding actions (from [GOVERNANCE.md](https://github.com/nodejs/Release/blob/main/GOVERNANCE.md#adding-new-releasers)):

- [x] @aduh95 to prepare a release (promoted by an existing releaser)
- [x] Be added to the GitHub [releasers team](https://github.com/orgs/nodejs/teams/releasers) in the Node.js org (grants ci-release access)
  - [x] Added to backporters team
- [x] Be added to the GitHub [security-release team](https://github.com/orgs/nodejs/teams/security-release) in the Node.js and nodejs-private orgs
- [x] Have a single, high quality SSH key added to the "dist" user on the primary www server
- [x] Have a GPG key added to the nodejs/node [README.md](https://github.com/nodejs/node/#release-team)
  - The key should be cherry-picked to all active release branches.
  - [x] Open a PR in [nodejs/docker-node](https://github.com/nodejs/docker-node/) to add gpg key to [node.keys](https://github.com/nodejs/docker-node/blob/master/keys/node.keys)
  - [x] Add the key to https://github.com/nodejs/release-keys

**Comment by richardlau** [comment]
@aduh95 I've added you to the releasers and security-release GitHub teams

I've also added your key from https://github.com/aduh95.keys to the primary www server. There's a pinned message to the #nodejs-release-private Slack channel (which I added you to) that details the jump host -- you should be able to ssh into that server as the `dist` user now. If you'd rather use a separate ssh key, let me know (also for anyone, the reference for generating a ssh key: https://github.com/nodejs/Release/blob/main/GOVERNANCE.md#ssh-key-guidance).

For your gpg key used to sign the release, please could you open the PRs as per the checklist?

**Comment by richardlau** [comment]
Looks like all the steps have been completed and @aduh95 was able to release Node.js 22.10.0 🎉.
